### ISSUE TITLE
[Documentation] Create a CNTT RA-2 requirements table

### ISSUE THREAD

**Issue by taylor** [cncf/cnf-conformance#118]
Documenting the CNTT RA-2 requirements is related to many items for CNF Platform Conformance and help with CNTT RA2/RI2/RC2 tasks.

Related issues:
- Initial review of RA-2 requirements #103 
- Analysis of K8s test coverage for RA-2 requirements https://github.com/cncf/cnf-conformance/issues/117
- https://github.com/cntt-n/CNTT/issues/1374
- https://github.com/cntt-n/CNTT/issues/1241

Tasks:
- [x]  Create public spreadsheet/table => https://docs.google.com/spreadsheets/d/12EWZVvlumktXoywvmlYPR_DrU34e7Gk_rSED3VyCG4o/edit
- [x] Add requirements from introduction
- [x] Add requirements from chapter 1
- [x] Add requirements from chapter 2
- [x] Add requirements from chapter 3
- [x] Add requirements from chapter 4
- [x] Add requirements from chapter 5
- [x] Add requirements from chapter 6

**Comment by lixuna** [comment]
Closing issue, as table was completed with information available at the time.
