### ISSUE TITLE
[CNF Developer UX] Create binary releases of the CNF Conformance Test Suite

### ISSUE THREAD

**Issue by lixuna** [cncf/cnf-conformance#119]
[Acceptance Criteria](https://github.com/cncf/cnf-conformance/issues/119#issuecomment-614161895)

### [CNF Developer UX] Create binary releases of the CNF Conformance Test Suite

Short Description: 
- to compile and upload binaries to GitHub when tagging by release
- to publish a binary for a vendor to download

MVP Features: 

- Static vs dynamic binary builds => static 
- Manual vs automated CI binary builds => manual
- OS installer packages supported => no
- OS ‘s supported (eg. Windows, Linux, OSX) => POSIX compliant Linux, Static binary
- Arch supported => amd64 only
- Checksum supported => yes
     - Manually create sha256 (suggestion: with same file name and sha256 as extension)
- Curl command? => no
- Attached as Zip or tgz => tgz

---

Documentation tasks:
- [x]  How to build static binary
- [x]  How to create checksum
- [x]  Update/create tagged github release
  - [x]  Updating/creating docs for attaching binary to a new tagged release (manual process)
- [x]  Update CNF Developer Install Guide
     - [ ]  DEFERRED: Change documentation to apply to tgz (not exe)

Implementation tasks: 
- [x]  binary release command
- [x] Create new tagged development release
- [x] Tag 1 or more people to peer review

**QA tasks**

Dev Review: 
- [x] walk through A/C
- [x] do you get the expected result?
- [x] if yes, 
   - [x] move to `Needs Peer Review` column  
   - [ ] create Pull Request and follow check list
   - [x] Assign 1 or more people for peer review
- [ ] if no, document what additional tasks will be needed

Peer review:
- [ ] walk through A/C
- [ ] do you get the expected result?
- [ ] if yes, 
   - [ ] move to `Reviewer Approved` column
   - [ ] Approve pull request
- [ ] if no, 
   - [ ] document what did not go as expected, including error messages and screenshots (if possible)
   - [ ] Add comment to pull request
   - [ ] request changes to pull request

**Comment by lixuna** [comment]
### Acceptance Criteria:

**Comment by lixuna** [comment]
Level of effort in pts: 0,1,2,3,5,8,13,21: 5 pts
---
@taylor 5
@wavell 5
@williscool 5
@nupejosh 8
@lixuna 5
@denverwilliams 5

**Comment by williscool** [comment]
https://crystal-lang.org/reference/using_the_compiler/

**Comment by taylor** [comment]
doc https://github.com/cncf/cnf-conformance/blob/develop/INSTALL.md#optional-build-binary

**Comment by taylor** [comment]
TODO:
- Updating/creating docs for attaching binary  to a new tagged release (manual process)

**Comment by lixuna** [comment]
@williscool what is the status of this?

**Comment by taylor** [comment]
Update sha256 instructions to check binary

**Comment by williscool** [comment]
last thing we need for this to be complete is seperating points.yml out in to seperate repo that can be downloaded by the binary setup

https://vulk.slack.com/archives/GTSL40B47/p1587607970089300?thread_ts=1587605349.085400&cid=GTSL40B47

**Comment by taylor** [comment]
Start with download from the `master`  branch https://raw.githubusercontent.com/cncf/cnf-conformance/master/points.yml

**Comment by taylor** [comment]
Deferred:  Change documentation to apply to tgz (not exe)

**Comment by taylor** [comment]
BUG: Error after every test `Missing hash key: "pass"`



```
Missing hash key: "pass"
/usr/local/crystal-0.31.1-1/share/crystal/src/hash.cr:0:9 in '[]'
/home/pair/workspace/taylor/walkthru/cnf-conformance/src/tasks/utils/sample_utils.cr:323:3 in 'upsert_passed_task'
/home/pair/workspace/taylor/walkthru/cnf-conformance/src/tasks/security.cr:39:7 in '->'
/home/pair/workspace/taylor/walkthru/cnf-conformance/lib/sam/src/sam/task.cr:39:29 in 'call'
/home/pair/workspace/taylor/walkthru/cnf-conformance/lib/sam/src/sam/task.cr:39:29 in 'call'
/home/pair/workspace/taylor/walkthru/cnf-conformance/lib/sam/src/sam.cr:77:7 in '__crystal_main'
/usr/local/crystal-0.31.1-1/share/crystal/src/crystal/main.cr:47:14 in 'main'
/usr/local/crystal-0.31.1-1/share/crystal/src/io/evented.cr:10:9 in 'add_write_event'
_start
???
```

**Comment by taylor** [comment]
All A/C pass on `master` for the binary test.  PASS/FAIL seen for test and a final score.   The bug above is https://github.com/cncf/cnf-conformance/issues/119#issuecomment-621484302 the only issue I see atm

**Comment by taylor** [comment]
@williscool currently released image is dynamic not static

**Comment by williscool** [comment]
@taylor 

will need to add that as well

https://crystal-lang.org/reference/using_the_compiler/#creating-a-statically-linked-executable

but seems like a strong list of caveats
https://github.com/crystal-lang/crystal/wiki/Static-Linking

looks like we'd have to spin up an alpine linux box to get a fully supported build

**Comment by williscool** [comment]
@taylor 

errors from trying to do static build on pair box

```
[pair@dev:~/src/will/cnf-conformance]
☺ ➔  crystal build src/cnf-conformance.cr --release --static
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libcrypto.a(dso_dlfcn.o): In function `dlfcn_globallookup':
(.text+0x11): warning: Using 'dlopen' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libevent.a(evutil.o): In function `test_for_getaddrinfo_hacks':
(.text+0x116): warning: Using 'getaddrinfo' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libevent.a(evutil.o): In function `evutil_getaddrinfo_common':

```

**Comment by williscool** [comment]
so do we spin up an alpine box or have people run `shards install` ?

**Comment by taylor** [comment]
Suggested future improvement:

- make downloads non-verbose by default

```
All prerequisites found.
--2020-05-04 22:36:03--  https://raw.githubusercontent.com/cncf/cnf-conformance/master/scoring_config/points_v1.yml
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 199.232.36.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|199.232.36.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2110 (2.1K) [text/plain]
Saving to: ‘points_v1.yml’
                                                                                                                                                              │··
points_v1.yml                           100%[=============================================================================>]   2.06K  --.-KB/s    in 0s
                                                                                                                                                              │··
                                                                                                                                                              │··
2020-05-04 22:36:03 (14.8 MB/s) - ‘points_v1.yml’ saved [2110/2110]
                                                                                                                                                              │··
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   645  100   645    0     0   3307      0 --:--:-- --:--:-- --:--:--  3324
100 9281k  100 9281k    0     0  19.4M      0 --:--:-- --:--:-- --:--:-- 19.4M
Successfully created directories for cnf-conformance
--2020-05-04 22:36:04--  https://get.helm.sh/helm-v3.1.1-linux-amd64.tar.gz
Resolving get.helm.sh (get.helm.sh)... 2606:2800:11f:1cb7:261b:1f9c:2074:3c, 152.195.19.97
Connecting to get.helm.sh (get.helm.sh)|2606:2800:11f:1cb7:261b:1f9c:2074:3c|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 12270615 (12M) [application/x-tar]
Saving to: ‘/home/pair/workspace/taylor/qa/testmay4/tools/helm/helm-v3.1.1-linux-amd64.tar.gz’
                                                                                                                                                       1s     │··
/home/pair/workspace/taylor/qa/testmay4 100%[=============================================================================>]  11.70M  --.-KB/s    in 0.1s
                                                                                                                                                              │··
2020-05-04 22:36:05 (103 MB/s) - ‘/home/pair/workspace/taylor/qa/testmay4/tools/helm/helm-v3.1.1-linux-amd64.tar.gz’ saved [12270615/12270615]

```

**Comment by taylor** [comment]
A/C testing using [v0.6.0](https://github.com/cncf/cnf-conformance/releases/tag/v0.6.0) following [INSTALL.md#cnf-developer-install-and-usage-guide](https://github.com/cncf/cnf-conformance/blob/master/INSTALL.md#cnf-developer-install-and-usage-guide):

- Downloaded [v0.6.0](https://github.com/cncf/cnf-conformance/releases/tag/v0.6.0)
   - made executable with chmod +x cnf-conformance.  Using with `./cnf-conformance`
- Testing cnf_setup with `./cnf-conformance cnf_setup cnf-path=cnf-conformance-src/example-cnfs/envoy/ `
   -> Result: Successfully setup envoy
-

**Comment by taylor** [comment]
Recommended future update

- Do not create results file when setup / cnf_setup command is run.


Steps to recreate:
- run `cnf-conformance setup`
- run `cnf-conformance cnf_setup ...`
- run `cnf-conformance all`


```
pair@cnfdev03:~/workspace/taylor/qa/testmay4$ ./cnf-conformance all
Do you wish to overwrite the results.yml file? If so, your previous results.yml will be lost.
(Y/N) (Default N): > Y
```

**Comment by taylor** [comment]
Suggested improvement:

- Binary error output should be differentiated from intended end user messages when possible.  Examples could be indent text, surround with dashes and a message, or something.
- Create binaries on CI or in a neutral environment vs dev system


```
/usr/share/crystal/src/gc/boehm.cr:110:5 in '->'
/mnt/c/Users/william/unison-with-dropbox-symlinked-to-linux/vulk_stuff/cnf-conformance/lib/sam/src/sam/task.cr:39:29 in 'call'
/mnt/c/Users/william/unison-with-dropbox-symlinked-to-linux/vulk_stuff/cnf-conformance/lib/sam/src/sam/task.cr:39:29 in 'call'
/mnt/c/Users/william/unison-with-dropbox-symlinked-to-linux/vulk_stuff/cnf-conformance/lib/sam/src/sam.cr:43:5 in '__crystal_main'       
/usr/share/crystal/src/crystal/main.cr:106:5 in 'main'                                                                                    
???                                                                                                                           
???                                                                                                                           
??? 
```
