### ISSUE TITLE
[CNF Developer UX] Document cnf-conformance.yml

### ISSUE THREAD

**Issue by lixuna** [cncf/cnf-conformance#121]
### [CNF Developer UX] Document cnf-conformance.yml

Short Description: 
- to document cnf-conformance.yml to be used in #109 

Tasks:
- [x] Brainstorm and documentation in https://hackmd.io/new  => https://hackmd.io/uaZqwCaTRjm3Z0Jhc3FcTA
- [x] Add a quick overview of the cnf-conformance.yml
- [x] Add new [cnf-conformance.example.yml](https://github.com/cncf/cnf-conformance/blob/master/cnf-conformance.example.yml)
- [ ] Add link to configuration documentation into the example doc
- [x] Annotate the example configuration file with comments for each key / value 
- [ ] Add comment suggesting updates as needed for:
  - [ ] the [test categories markdown](https://github.com/cncf/cnf-conformance/blob/master/TEST-CATEGORIES.md)
  - [ ] the [pseudo code markdown](https://github.com/cncf/cnf-conformance/blob/master/PSEUDO-CODE.md)
  - [ ] slide content updates, LINK_TO_UPDATES
  - [ ] the [README](https://github.com/cncf/cnf-conformance/blob/master/README.md)
- [x] Tag 1 or more people to peer review

**Comment by taylor** [comment]
Estimated effort in points: 3

- @wavell 3
- @williscool 3
- @denverwilliams  2
- @nupejosh 2
- @lixuna 3
- @taylor 2

**Comment by denverwilliams** [comment]
Link for cnf-conformance.yml
https://hackmd.io/uaZqwCaTRjm3Z0Jhc3FcTA

**Comment by taylor** [comment]
Document looks good.

TODO: 
- determine where  doc can go in repo and add into a markdown
- add example configuration

**Comment by denverwilliams** [comment]
Link to committed usage document: https://github.com/cncf/cnf-conformance/blob/develop/CNF_CONFORMANCE_YML_USAGE.md

**Comment by denverwilliams** [comment]
@taylor ^

**Comment by taylor** [comment]
https://github.com/cncf/cnf-conformance/blob/master/cnf-conformance.example.yml

**Comment by taylor** [comment]
Next:
- update [INSTALL doc](https://github.com/cncf/cnf-conformance/blob/master/INSTALL.md#configure-the-conformance-suite-for-testing-a-cnf) to reference the new documentation and example
