### ISSUE TITLE
[CNF Developer UX] Create a test log file which lists binary PASS or FAIL for every test

### ISSUE THREAD

**Issue by lixuna** [cncf/cnf-conformance#125]
### [CNF Developer UX] Create a test log file which lists binary PASS or FAIL for every test

Short description: 
- to create a test log file, eg. cnf-conformance-results-20200401.txt, which lists PASS or FAIL for every test

Tasks:

- [x] Update code to automatically create a log file when the `all` command runs
- [x] Log file name should be timestamped (so that it's unique).  Example: cnf-conformance-results-20200401-1301.txt
- [x] Message on console showing the name of the log file created.  Example: "Results have been saved to cnf-conformance-results-20200401-1301.txt"

**Comment by taylor** [comment]
Create log with flag/option to enable or automatic when running `cnf-conformance all`.  

Example with flag: `cnf-conformance all --create-log`

Also we could have don't create flag. Eg. --no-results-log

- @denverwilliams: flag
- @wavell: automatic (k8s conformance does this)
- @taylor: automatic

**Comment by taylor** [comment]
@denverwilliams comments:

sonobuoy creates the log file by default

k8s e2e tests themselves logs to console

**Comment by taylor** [comment]
Estimated effort in points: 3

- @denverwilliams  3
- @wavell 5
- @nupejosh 5
- @lixuna 3
- @williscool 3
- @taylor 3

/label 3pts

**Comment by wavell** [comment]
Sample output for results file:
name: cnf conformance                                                                                                 
status:                                                                                                               
points:                                                                                                               
items:                                                                                                                
- name: privileged                                                                                                    
  status: failed                                                                                                      
  points: -1                                                                                                          
- name: increase_capacity                                                                                             
  status: passed                                                                                                      
  points: 5                                                                                                           
- name: decrease_capacity                                                                                             
  status: passed                                                                                                      
  points: 5                                                                                                           
- name: ip_addresses                                                                                                  
  status: failed                                                                                                      
  points: -1                                                                                                          
- name: readiness                                                                                                     
  status: passed                                                                                                      
  points: 5                                                                                                           
- name: install_script_helm                                                                                           
  status: passed                                                                                                      
  points: 5                                                                                                           
- name: helm_chart_valid                                                                                              
  status: passed                                                                                                      
  points: 5

**Comment by taylor** [comment]
results.yml created with points for tests which were chosen including `all`
