### ISSUE TITLE
[CNF Developer UX] Update the setup command to Initialize the CNF Conformance Test Suite 

### ISSUE THREAD

**Issue by lixuna** [cncf/cnf-conformance#126]
[Acceptance Criteria:](https://github.com/cncf/cnf-conformance/issues/126#issuecomment-614248403)

### [CNF Developer UX] Update setup command to prepare the suite for accepting a CNF for testing

Short description: 
- the setup command will include a pre-req checker
- the pre-req checker will not if the setup was Success/Fail
- if Fail, URLS to docs will be provided

MVP Features: 
- Add functionality to cnf-conformance setup 
    - Add a Pre-req checker for all requirements (eg. helm)
    - Add an output message if setup is complete
    - Add an output message if something is missing from the CNF Developer pre-reqs (eg. kubectl or KUBECONFIG environment)
    - Note what is missing
    - Add an upstream URL to resolve problems 
    - Give a link to github issues and request a issue to be created

---

Documentation tasks:
- [ ]   TBD

Implementation tasks: TBD
- [ ]  TBD
- [x] Tag 1 or more people to peer review

**QA tasks**

Dev Review: 
- [x] walk through A/C
- [x] do you get the expected result?
- [x] if yes, 
   - [ ] move to `Needs Peer Review` column  
   - [ ] create Pull Request and follow check list
   - [ ] Assign 1 or more people for peer review
- [ ] if no, document what additional tasks will be needed

Peer review:
- [ ] walk through A/C
- [ ] do you get the expected result?
- [ ] if yes, 
   - [ ] move to `Reviewer Approved` column
   - [ ] Approve pull request
- [ ] if no, 
   - [ ] document what did not go as expected, including error messages and screenshots (if possible)
   - [ ] Add comment to pull request
   - [ ] request changes to pull request

**Comment by lixuna** [comment]
### Acceptance Criteria:

### To test a Passing setup example:

- [ ] I follow the CNF Developer install guide
- [ ] I install prerequisites
- [ ] I can run the cnf-conformance setup command
- [ ] The output says, “Setup complete."
- [ ] The cnfs and tools folder are created

### To test a Failing setup example which does not have CNF Developer Prerequisites met:

- [ ] I don’t follow the Prerequisites steps (ie. failure to install Kubectl binary)
- [ ] I can run the cnf-conformance setup command
- [ ] The output says, “Setup failed. Please install the following prerequisites.”
- [ ] The output lists the missing prerequisites with links to how to resolve them
- [ ] When running the integration spec tests prerequisites testing is seen in the output

### When I follow the (Conformance Developer) Test/Source Install instructions to setup the CNF Conformance software for development:

- [ ] I can run the crystal spec -v command
- [ ] The output will have prerequisites tests
- [ ] The output will have internal prerequisites tests
- [ ] The output will have external (CNF Developer) prerequisites tests

**Comment by lixuna** [comment]
Level of effort in pts: 0,1,2,3,5,8,13,21: 5 pts.
---

@taylor 5
@wavell 5
@denverwilliams 5
@nupejosh n/a
@lixuna 5

**Comment by wavell** [comment]
I used sudo apt-get remote wget to test a failed prerequisite list

**Comment by taylor** [comment]
works as expected in QA
