### ISSUE TITLE
[CNFs] Test Envoy as an example CNF with the CNF Conformance Test Suite

### ISSUE THREAD

**Issue by lixuna** [cncf/cnf-conformance#133]
[Acceptance Criteria](https://github.com/cncf/cnf-conformance/issues/133#issuecomment-613662834)

### [CNFs] Test Envoy as an example CNF with the CNF Conformance Test Suite

Planning Tasks:
- [x] Review and update https://github.com/cncf/cnf-conformance/edit/develop/EXAMPLE-CNFS.md
- [x] Select the next one (or two) CNF(s) that will be tested in the CNF Conformance Test Suite => Envoy CNF

Documentation tasks: TBD
- [x]  create [README for Envoy CNF](https://github.com/cncf/cnf-conformance/blob/master/example-cnfs/envoy/README.md) (example: https://github.com/cncf/cnf-conformance/blob/master/sample-cnfs/sample-coredns-cnf/README.md)
- [ ]  

Implementation tasks: TBD
- [x] create [cnf-conformance.yml](https://github.com/cncf/cnf-conformance/blob/master/example-cnfs/envoy/cnf-conformance.yml)  (Example: https://github.com/cncf/cnf-conformance/blob/master/sample-cnfs/sample-coredns-cnf/cnf-conformance.yml)
- [x] Tag 1 or more people to peer review

CNF Testing task:

- [x]  Follow the new example CNF's README.md to test the CNF
- [x]  Add the Final Score in a comment in this ticket
- [x]  Add the entire test result output in a comment in this ticket

**QA tasks**

Dev Review: 
- [x] walk through A/C
- [x] do you get the expected result?
- [ ] if yes, 
   - [ ] move to `Needs Peer Review` column  
   - [ ] create Pull Request and follow check list
   - [ ] Assign 1 or more people for peer review
- [ ] if no, document what additional tasks will be needed

Peer review:
- [ ] walk through A/C
- [ ] do you get the expected result?
- [ ] if yes, 
   - [ ] move to `Reviewer Approved` column
   - [ ] Approve pull request
- [ ] if no, 
   - [ ] document what did not go as expected, including error messages and screenshots (if possible)
   - [ ] Add comment to pull request
   - [ ] request changes to pull request

**Comment by lixuna** [comment]
Acceptance criteria: steps to test during development and peer review
---

- [ ]  I can follow the set up instructions
- [ ]  I should see the Envoy CNF saved somewhere
    - [ ]   Ie. in an example-cnfs folder with each example CNF having it’s own sub-folder with a config
- [ ]  I should see Envoy CNF README with summary and instructions in Envoy directory and in example CNFs
- [ ]  I can run the CNF Conformance Tests w/ the Envoy CNF
- [ ]  I can check the output of the CNF conformance command
- [ ]  I should see which tests passed or failed for the Envoy CNF
- [ ]  I should see a final score for the Envoy CNF

**Comment by lixuna** [comment]
Level of effort in pts: 0,1,2,3,5,8,13,21 = 3 pts
---
@denverwilliams 3
@wavell 3
@nupejosh 5
@taylor 3
@lixuna 3

**Comment by taylor** [comment]
Expected results from A/C https://github.com/cncf/cnf-conformance/issues/133#issuecomment-613662834
-  Tests will fail because steps in the install docs do not cover everything needed

Suggestions for updates can be added in comments to be implemented in new tickets.

**Comment by taylor** [comment]
Problems seen when testing Envoy following the CNF Developer guide:

### helm chart required or tests fails.

the helm test expects a helm chart directory in the cnf folder being tested.  

Possible solutions:
- manually install
- update test suite to automatically retrieve helm chart referenced in the config


Example manual instructions:
- Install helm version 3
- Make the cnfs/envoy/helm_chart directory
- Retrieve the helm chart source: helm pull stable/envoy
- Move the tar file into the cnfs/envoy/helm_chart directory
- Untar the tar file
- Move the contents of the new helm chart source directory into the cnfs/envoy/helm_chart directory (up one level)


cc: @wavell @denverwilliams @lixuna

**Comment by taylor** [comment]
TODO:
- update envoy readme to have a simpler set of instructions which are aligned with the [INSTALL guide](https://github.com/cncf/cnf-conformance/blob/master/INSTALL.md#cnf-developer-install-and-usage-guide).  Example instructions https://hackmd.io/6jfdwZ2_SveUb5lRr7FLuw?view

**Comment by taylor** [comment]
Create new tickets for updates to INSTALL guide
- add automation information https://github.com/cncf/cnf-conformance/tree/96cee8cefc9a71e62e971f8f4abad56e5db59866/example-cnfs/envoy#automated-envoy-installation
- add manual steps, if needed, https://github.com/cncf/cnf-conformance/tree/96cee8cefc9a71e62e971f8f4abad56e5db59866/example-cnfs/envoy#manual-envoy-installation

**Comment by taylor** [comment]
# Manual Envoy installation steps which are handled by the automation CNF setup steps:
1. Install helm version 3
1. Make the cnfs/envoy diretory 
1. If you are testing the cnf source, clone the source into the cnfs/envoy directory
1. Copy the cnf-conformance.yml into the cnfs/envoy directory
1. Install envoy using helm: `helm install envoy stable/envoy`
1. Make the cnfs/envoy/helm_chart directory
1. Retrieve the helm chart source: `helm pull stable/envoy`
1. Move the tar file into the cnfs/envoy/helm_chart directory
1. Untar the tar file
1. Move the contents of the new helm chart source directory into the cnfs/envoy/helm_chart directory (up one level)
1. Wait for the installation to finish (all pods are ready)
1. Run the conformance suite: `export KUBECONFIG=$(pwd)/admin.conf ; crystal src/cnf-conformance.cr all`

**Comment by wavell** [comment]
PASSED: No privileged containers
PASSED: Replicas increased to 3
PASSED: Replicas decreased to 1
FAILURE: IP addresses found
PASSED: Helm liveness probe found
PASSED: Helm readiness probe found
PASSED (by default): No install script provided
Successfully created directories for cnf-conformance
PASSED: Helm Chart helm_chart Lint Passed
Final score: 29

----

# cnf-conformance-results-20200423-130723-852.yml
name: cnf conformance
status:
points:
items:
- name: privileged
  status: passed
  points: 5
- name: increase_capacity
  status: passed
  points: 5
- name: decrease_capacity
  status: passed
  points: 5
- name: ip_addresses
  status: failed
  points: -1
- name: readiness
  status: passed
  points: 5
- name: install_script_helm
  status: passed
  points: 5
- name: helm_chart_valid
  status: passed
  points: 5

**Comment by taylor** [comment]
Works as expected after update for rolling version update test https://github.com/cncf/cnf-conformance/commit/c93bf96b1596f761fc873b87bae574012aa1f8d1
