### ISSUE TITLE
[Documentation] Create a "Platform Test Categories" markdown

### ISSUE THREAD

**Issue by lixuna** [cncf/cnf-conformance#140]
### [Documentation] Create Platform Test Categories markdown

Short description: 
-  to create a markdown file for Platform Test Categories, similar to the [CNF Workload Conformance Test Categories](https://github.com/cncf/cnf-conformance/blob/master/TEST-CATEGORIES.md) markdown file

Tasks:
- [x] Review and add CNF Conformance Workload categories if relevant/missing
- [x] Review and add CNTT cloud native categories if relevant/missing
- [x] Review and add principles from Cloud Native Networking as categories if relevant/missing
- [x] Use K8s test categories available in code as the platform categories
- [x] Triage the individual K8s conformance tests and add them to the new CNF Platform categories (not deep analysis of requirements)

Process:
- [x]  Create 1st draft w/ outline > https://hackmd.io/R18UN9GyQzabHiHPJH9t8w
- [x]  Investigate potential test categories and upstream tests for implementation and document findings in 1st draft
- [x]  Peer review of 1st draft 
- [x]  Update draft to slim down category options and clean up content 
- [ ]  Peer review of 2nd draft
- [ ]  Update draft to be ready to publish
- [ ]  Peer review of 3rd draft
- [ ]  Update draft as needed
- [ ]  Publish on GitHub/develop as PLATFORM-TEST-CATEGORIES.md
- [ ] Tag 1 or more people to peer review

**Comment by lixuna** [comment]
Level of effort: 0,1,2,3,5,8,13,21 => 8 pts
---

@taylor 8
@wavell 8
@denverwilliams 8
@lixuna 8

**Comment by wavell** [comment]
draft 1: https://hackmd.io/Zu-HxxOPSO-Q_H-dw0-Fvg

**Comment by lixuna** [comment]
closing as done, test categories will be the same across workloads and platforms for the MVP
