### ISSUE TITLE
Update high-level README.md for CNF Conformance test categories

### ISSUE THREAD

**Issue by lixuna** [cncf/cnf-conformance#18]
**Goal: Update high-level README.md for CNF Conformance test categories**

Tasks: 

- [x]  Update high-level README.md
- [x]  Add what we are aiming to do w/ CNF Conformance Tests
- [x]  Add high-level CNF Conformance test categories
- [x]  Create an outline based on https://docs.google.com/document/d/1Ncg_Z8Yq-hKixruHfutG-ASi3Qm0Bi1DaRyXF80EJ0g/edit
- [x]  Peer review of outline 
- [x]  Create a rough draft 
- [x]  Peer review of draft 
- [ ]  Iterate as needed, peer review (optional) 
- [x]  Add content to README.md

**Comment by wavell** [comment]
See https://github.com/cncf/cnf-conformance/blob/master/TEST-CATEGORIES.md for the documentation.  It is linked to from the base readme

**Comment by lixuna** [comment]
To do: @lixuna update README with high level test category details
