### ISSUE TITLE
[CNF Developer UX] display the maximum number of points with the final score, aka 99/100

### ISSUE THREAD

**Issue by lixuna** [cncf/cnf-conformance#181]
[Acceptance Criteria](https://github.com/cncf/cnf-conformance/issues/181#issuecomment-632307737)
---

### [Scoring] display the maximum number of points with the final score, aka Final score = 99/100

Short description: 
- display the maximum number of points in the final score

Audience: 
- CNF Developer

Business Value: 
- to display the earned points with the possible maximum score
- to show a CNF Developer where their CNF falls within the scoring ranges

---

**Environment set up tasks:**

**Upstream tool set up tasks: (conformance suite + upstream tools)**
- N/A

**CNF setup Tasks** 

**Sample CNF tasks:**

**Code implementation tasks:**
- [ ] 

**Documentation tasks:**
- [ ] Update [Test Categories md](https://github.com/cncf/cnf-conformance/blob/master/TEST-CATEGORIES.md) if needed 
- [ ] Update [Pseudo Code md](https://github.com/cncf/cnf-conformance/blob/master/PSEUDO-CODE.md) if needed
- [ ] Update [USAGE md](https://github.com/cncf/cnf-conformance/blob/master/USAGE.md) if needed 
- [ ] Update [installation instructions](https://github.com/cncf/cnf-conformance#installation)  if needed 

**QA tasks**

Dev Review: 
- [x] walk through A/C
- [x] do you get the expected result?
- [x] if yes, 
   - [x] move to `Needs Peer Review` column  
   - [x] create Pull Request and follow check list
   - [x] Assign 1 or more people for peer review
- [ ] if no, document what additional tasks will be needed

Peer review:
- [ ] walk through A/C
- [ ] do you get the expected result?
- [ ] if yes, 
   - [ ] move to `Reviewer Approved` column
   - [ ] Approve pull request
- [ ] if no, 
   - [ ] document what did not go as expected, including error messages and screenshots (if possible)
   - [ ] Add comment to pull request
   - [ ] request changes to pull request

**Comment by taylor** [comment]
DRAFT Acceptance Criteria: 
---

### Acceptance Criteria for peer review:
--
### Documentation is updated:
- [ ]  Documentation lists new test name
- [ ]  Test Categories md is updated
- [ ]  USAGE md is updated
- [ ]  Installation instructions is updated


###  Common steps
- [ ]  Find or create a K8s cluster to use
  - [ ] Steps for creating will be in another ticket  
- [ ]  Talk with team for access to an existing cluster
- [ ]  Set the KUBECONFIG environment variable for accessing the target K8s cluster
- [ ]  As a developer, Pull down latest version of CNF conformance test code from {FEATURE} branch
     - [ ]  Check that {FEATURE} Branch passes all A/C 
     - [ ]  Check that {FEATURE} Branch passes tests in Travis CI
- [ ]  As a peer reviewer, check that PR passes Travis CI tests
     - [ ]  if yes, merge PR to master
     - [ ]  if no, make a comment and request that developer make changes to pass tests 
- [ ]  As a peer reviewer, Pull down latest version of CNF conformance test code from `master` branch
- [ ]  Run `shards install`
- [ ]  Run `crystal spec`
- [ ]  I expect to see PASSED for the tests

**Update example CNFs cnf-conformance.yml, if needed**
- N/A

### I would expect the CNF to pass when I run the entire test category suite (`configuration_lifecycle`) the final score should show max number of points (aka 5/10)
- [ ] Follow common steps above
- [ ] Run  `crystal src/cnf-conformance.cr resilience`
- [ ]  I expect to see the output and results from all tests in the test category
- [ ] I expect to see PASSED for the test and test category
- [ ] Note: test category name should have been updated to `statelessness` in #158 

### I would expect the CNF to pass when I run the entire test suite (`all`) the final score should show max number of points (aka 5/10)
- [ ] Follow common steps above
- [ ] Run  `crystal src/cnf-conformance.cr all`
- [ ] I expect to see the output from the test
- [ ] I expect to see PASSED for the test


### When using the latest binary release (or snapshot) I would expect the CNF to pass when I run the entire test suite (`all`)
- [ ] Follow common steps above
- [ ] Download the latest [binary release](https://github.com/cncf/cnf-conformance/releases) (which could be a development snapshot) 
- [ ] Run  `cnf-conformance all`
- [ ] I expect to see the output from the test
- [ ] I expect to see PASSED for the test

**Comment by lixuna** [comment]
Level of effort: 3 pts
---

@wavell 3
@lixuna 3

**Comment by taylor** [comment]
Watson walked through A/C

**Comment by taylor** [comment]
lgtm
