### ISSUE TITLE
[CNFs] Create CoreDNS CNF example in example-cnfs folder, add README, add cnf-conformance.yml, add public helm chart support

### ISSUE THREAD

**Issue by lixuna** [cncf/cnf-conformance#183]
[Acceptance Criteria]https://github.com/cncf/cnf-conformance/issues/183#issuecomment-625003752)

### [CNFs] Update CoreDNS example CNF to move to example-cnfs folder, add README and cnf-conformance.yml

Documentation tasks:
- [x]  create folder for CoreDNS in example-cnfs folder
- [x]  create [README for CoreDNS CNF], based on [Envoy example](https://github.com/cncf/cnf-conformance/blob/master/example-cnfs/envoy/README.md) (example: https://github.com/cncf/cnf-conformance/blob/master/sample-cnfs/sample-coredns-cnf/README.md)

Implementation tasks: TBD
- [x] create [cnf-conformance.yml], based on [Envoy example](https://github.com/cncf/cnf-conformance/blob/master/example-cnfs/envoy/cnf-conformance.yml) 
- [x] add support for public helm chart re: #169 
- [ ] Tag 1 or more people to peer review

CNF Testing task:
- [ ]  Follow the new example CNF's README.md to test the CNF
- [ ]  Add the Final Score in a comment in this ticket
- [ ]  Add the entire test result output in a comment in this ticket

**QA tasks**

Dev Review: 
- [ ] walk through A/C
- [ ] do you get the expected result?
- [ ] if yes, 
   - [ ] move to `Needs Peer Review` column  
   - [ ] create Pull Request and follow check list
   - [ ] Assign 1 or more people for peer review
- [ ] if no, document what additional tasks will be needed

Peer review:
- [ ] walk through A/C
- [ ] do you get the expected result?
- [ ] if yes, 
   - [ ] move to `Reviewer Approved` column
   - [ ] Approve pull request
- [ ] if no, 
   - [ ] document what did not go as expected, including error messages and screenshots (if possible)
   - [ ] Add comment to pull request
   - [ ] request changes to pull request

**Comment by taylor** [comment]
Acceptance criteria: steps to test during development and peer review
---

- [ ]  I can follow the set up instructions as a `CNF Developer` https://github.com/cncf/cnf-conformance/blob/master/INSTALL.md#cnf-developer-install-and-usage-guide
- [ ]  I should see a CoreDNS CNF example folder
    - [ ]   Ie. in an example-cnfs folder with each example CNF having it’s own sub-folder with a config
- [ ]  I should see CoreDNS CNF README with summary and instructions in CoreDNS directory and in example CNFs
- [ ]  I should see a cnf-conformance.yml configuration in the CoreDNS example CNF folder
- [ ]  I can run the CNF Conformance Tests w/ the CoreDNS CNF
- [ ]  I can check the output of the CNF conformance command
   - [ ]  I should see which tests passed or failed for the CoreDNS CNF
   - [ ]  I should see a final score for the CoreDNS CNF
- [ ]  Final Score for CoreDNS CNF = 


Testing A/C task:
- [ ]  Add the Final Score in a comment in this ticket
- [ ]  Add the entire test result output in a comment in this ticket

**Comment by williscool** [comment]
tested this myself with instructions in readme

**Comment by lixuna** [comment]
@williscool did you use the steps in the A/C https://github.com/cncf/cnf-conformance/issues/183#issuecomment-625003752?

What is the final score?

from the A/C:

Testing A/C task:

- [ ]  Add the Final Score in a comment in this ticket
- [ ]  Add the entire test result output in a comment in this ticket

**Comment by williscool** [comment]
Final score: 54

[cnf-conformance-results-20200507-151801-250.yml.txt](https://github.com/cncf/cnf-conformance/files/4595249/cnf-conformance-results-20200507-151801-250.yml.txt)
