### ISSUE TITLE
Bugfix: latest version of kind and crystal not working with Travis

### ISSUE THREAD

**Issue by lixuna** [cncf/cnf-conformance#189]
[Acceptance Criteria:](https://github.com/cncf/cnf-conformance/issues/169#issuecomment-620215415)
---

### Bugfix: latest version of kind and crystal not working with Travis

- found when working on #169 

**Solution:**
- The versions of Kind and Crystal need to be pinned.

EPIC: CNF Conformance Test Suite

---

**Environment set up tasks:**

**Upstream tool set up tasks: (conformance suite + upstream tools)**
- N/A

**CNF setup Tasks** 

**Sample CNF tasks:**

**Code implementation tasks:**
- [x]  resolve issues with crystal spec not working as expected

**Documentation tasks:**
- [ ] Update [Test Categories md](https://github.com/cncf/cnf-conformance/blob/master/TEST-CATEGORIES.md)  
- [ ] Update [Pseudo Code md](https://github.com/cncf/cnf-conformance/blob/master/PSEUDO-CODE.md) 
- [ ] Update [USAGE md](https://github.com/cncf/cnf-conformance/blob/master/USAGE.md) 
- [ ] Update [installation instructions](https://github.com/cncf/cnf-conformance#installation) if needed 

**QA tasks**

Dev Review: 
- [ ] walk through A/C
- [ ] do you get the expected result?
- [ ] if yes, 
   - [ ] move to `Needs Peer Review` column  
   - [ ] create Pull Request and follow check list
   - [ ] Assign 1 or more people for peer review
- [ ] if no, document what additional tasks will be needed

Peer review:
- [ ] walk through A/C
- [ ] do you get the expected result?
- [ ] if yes, 
   - [ ] move to `Reviewer Approved` column
   - [ ] Approve pull request
- [ ] if no, 
   - [ ] document what did not go as expected, including error messages and screenshots (if possible)
   - [ ] Add comment to pull request
   - [ ] request changes to pull request

**Comment by lixuna** [comment]
Level of effort in pts: 01,2,3,5,8,13,21: 
---

**Comment by denverwilliams** [comment]
Now resolved and both master and develop are passing. 

Commits related to this fix:
- https://github.com/cncf/cnf-conformance/commit/60a13922425614f7cbfe96f07849ddd6208e1edc
- https://github.com/cncf/cnf-conformance/commit/7f70217079e72073a70462a9821161cf02aa9e57
- https://github.com/cncf/cnf-conformance/commit/a92f8b22ee2107836fc97dab604d962d38f350c2
- https://github.com/cncf/cnf-conformance/commit/f7259b273df0d99e1d68793ca3265468a2bfa527

**Comment by denverwilliams** [comment]
@taylor @lixuna ^

**Comment by wavell** [comment]
Master travis build passed
