### ISSUE TITLE
[Example CNFs] Create a yml validator that fails an example CNF with incomplete config files

### ISSUE THREAD

**Issue by lixuna** [cncf/cnf-conformance#201]
[Acceptance Criteria](https://github.com/cncf/cnf-conformance/issues/201#issuecomment-628250258)

### [Example CNFs] Create a yml validator that fails an example CNF with incomplete config files

**Short description:** 
- found in https://github.com/cncf/cnf-conformance/pull/185#pullrequestreview-407156665
- Comment: Need a yml validator that fails these config files. The docker_deploy attribute is missing above.

**Environment set up tasks:**

**Upstream tool set up tasks: (conformance suite + upstream tools)**
- N/A

**CNF setup Tasks** 

**Sample CNF tasks:**

**Code implementation tasks:**
- [x] Choose a set of emojis for the test
- [ ] TBD

**Documentation tasks:**
- [ ] Update [Test Categories md](https://github.com/cncf/cnf-conformance/blob/master/TEST-CATEGORIES.md) if needed (Test already documented)
- [x] Update [USAGE md](https://github.com/cncf/cnf-conformance/blob/master/USAGE.md) if needed 
- [ ] Update [installation instructions](https://github.com/cncf/cnf-conformance#installation)  if needed 

**QA tasks**

Dev Review: 
- [x] walk through A/C
- [x] do you get the expected result?
- [x] if yes, 
   - [x] move to `Needs Peer Review` column  
   - [ ] create Pull Request and follow check list
   - [ ] Assign 1 or more people for peer review
- [ ] if no, document what additional tasks will be needed

Peer review:
- [x] walk through A/C
- [x] do you get the expected result?
- [x] if yes, 
   - [x] move to `Reviewer Approved` column
   - [x] Approve pull request
- [ ] if no, 
   - [ ] document what did not go as expected, including error messages and screenshots (if possible)
   - [ ] Add comment to pull request
   - [ ] request changes to pull request

**Comment by lixuna** [comment]
DRAFT: Acceptance Criteria:  
---

### Acceptance Criteria for peer review:
--
### Documentation is updated:
- [ ]  Test Categories md is updated
- [ ]  USAGE md is updated
- [ ]  Installation instructions is updated

###  Common steps
- [ ]  Find or create a K8s cluster to use
  - [ ] Steps for creating will be in another ticket  
- [ ]  Talk with team for access to an existing cluster
- [ ]  Set the KUBECONFIG environment variable for accessing the target K8s cluster
- [ ]  As a developer, Pull down latest version of CNF conformance test code from `develop` branch
- [ ]  As a peer reviewer, Pull down latest version of CNF conformance test code from `master` branch
- [ ]  Run `shards install`
- [ ]  Run `crystal spec`
- [ ]  I expect to see PASSED for the tests

**Update example CNFs cnf-conformance.yml, if needed**
- [ ] continue, If there is an update to cnf-coformance.yml
- [ ] for each CNF Example
- [ ] Update the example CNF's cnf-conformance.yml to include the new changes
- [ ] Update the example CNF's README if needed
- [ ] Test the example CNF following it's README

### When using the test `cnf-conformance hardcoded_ip_addresses_in_k8s_runtime_configuration` command the sample "good" CNF should PASS test successfully:
- [ ]  Run `crystal src/cnf-conformance.cr setup`
- [ ]  Run  `crystal src/cnf-conformance.cr sample_coredns_setup`
- [ ]  Run  `crystal src/cnf-conformance.cr hardcoded_ip_addresses_in_k8s_runtime_configuration`
- [ ]  I expect to see the output and results from the test
- [ ]  I expect to see PASSED for the test
         - [ ] "heavy_check_mark PASSED: No hard-coded IP addresses found in the runtime K8s configuration"

### When using the test `crystal spec --tag `hardcoded_ip_addresses_in_k8s_runtime_configuration`` command the sample "good" CNF should PASS and the "hardcoded ip address bad example CNF"  should FAIL test:
- [ ]  Run `crystal spec --tag hardcoded_ip_addresses_in_k8s_runtime_configuration`
- [ ]  I expect to see the output and results from the test
- [ ]  I expect to see ":heavy_check_mark:  PASSED: No hard-coded IP addresses found in the runtime K8s configuration [EMOJIS]" 
- [ ]  I expect to see ":x: FAILURE: Hard-coded IP addresses found in the runtime K8s configuration [EMOJIS]"

### I would expect the CNF to pass when I run the entire test category suite (`configuration_lifecycle`)
- [ ]  Follow common steps above
- [ ]  Run  `crystal src/cnf-conformance.cr configuration_lifecycle`
- [ ]    I expect to see the output and results from all tests in the test category
- [ ] I expect to see PASSED for the test and test category


### I would expect the CNF to pass when I run the entire test suite (`all`)
- [ ] Follow common steps above
- [ ] Run  `crystal src/cnf-conformance.cr all`
- [ ] I expect to see the output from the test
- [ ] I expect to see PASSED for the test

**Comment by taylor** [comment]
Estimate of effort in points: 5pts

- @lixuna 5
- @denverwilliams 5
- @wavell 5
- @taylor 5

**Comment by taylor** [comment]
*Future A/C* that would help with the Install docs and binary not going out of sync

### When using the latest binary release (or snapshot) I would expect the CNF to pass when I run the entire test suite (`all`)
- [ ] Follow common steps above
- [ ] Download the latest [binary release](https://github.com/cncf/cnf-conformance/releases) (which could be a development snapshot) 
- [ ] Run  `cnf-conformance all`
- [ ] I expect to see the output from the test
- [ ] I expect to see PASSED for the test

**Comment by williscool** [comment]
re the A/C criteria .

the pr I have currently 

https://github.com/cncf/cnf-conformance/pull/216

adds the validator to the loading path of the `cnf-conformance.yml`

I think this is better than having it as a separate test.

This way everytime a cnf-conformance.yml is loaded whether from a test in the spec or from the `cnfs` path the validation will run and give info on whether or not the file has been formated correctly

**Comment by denverwilliams** [comment]
@williscool 
A/C fails on ```crystal src/cnf-conformance.cr validate_config [PATH_TO]/cnf-conformance.yml``` due to there not being a cli command / task to run the validation directly.

Having it run the validation automatically is good, but we'd also like to have a separate command / task for validating the yaml without having to run the whole test suite.

**Comment by williscool** [comment]
@denverwilliams done! #216

**Comment by nupejosh** [comment]
While doing AC I updated the AC instructions for the `validate_config` command to include the required `cnf-config` argument declaration. 

The command appears to work as expected once you use the cnf-config arg. 

However, running ` crystal spec --tag validate_config` has a passing test. This single test does not pass the AC for the spec tests where passing criteria includes several more tests and emojis.

**Comment by wavell** [comment]
![image](https://user-images.githubusercontent.com/29548/84560350-aeaae380-ad08-11ea-8de6-12bf173083b0.png)

![image](https://user-images.githubusercontent.com/29548/84560427-aacb9100-ad09-11ea-988c-ca097f5a4d9f.png)
