### ISSUE TITLE
[CNF Developer UX] Support passing cnf configuration to all and cleanup commands to simplify CLI usage

### ISSUE THREAD

**Issue by lixuna** [cncf/cnf-conformance#213]
[Acceptance Criteria](https://github.com/cncf/cnf-conformance/issues/213#issuecomment-628863851)

### Feature: [CNF Developer UX] Support passing cnf configuration to all and cleanup commands to simplify CLI usage

**Short description:** 
Use reasonable default and minimize number of commands to get started by supporting most options through a configuration file which can be specified when running the `all` test command.

This will support specifying the conformance configuration file for a CNF which will be tested.  Setup and deployment will be handled based on configuration information. The auto cleanup command will also be updated to support use of the configuration file option.

_NOTE: Does the cleanup command does not handle manually deployed CNFs_

**Environment set up tasks:**

**Upstream tool set up tasks: (conformance suite + upstream tools)**
- N/A

**CNF setup Tasks** 

**Sample CNF tasks:**

**Code implementation tasks:**
- [ ] TBD

**Documentation tasks:**
- [ ] Update [Test Categories md](https://github.com/cncf/cnf-conformance/blob/master/TEST-CATEGORIES.md) if needed (Test already documented)
- [x] Update [USAGE md](https://github.com/cncf/cnf-conformance/blob/master/USAGE.md) if needed 
- [x] Update [installation instructions](https://github.com/cncf/cnf-conformance#installation)  if needed 

**QA tasks**

Dev Review: 
- [x] walk through A/C
- [x] do you get the expected result?
- [x] if yes, 
   - [x] move to `Needs Peer Review` column  
   - [ ] create Pull Request and follow check list
   - [ ] Assign 1 or more people for peer review
- [ ] if no, document what additional tasks will be needed

Peer review:
- [x] walk through A/C
- [x] do you get the expected result?
- [x] if yes, 
   - [x] move to `Reviewer Approved` column
   - [ ] Approve pull request
- [ ] if no, 
   - [ ] document what did not go as expected, including error messages and screenshots (if possible)
   - [ ] Add comment to pull request
   - [ ] request changes to pull request

**Comment by lixuna** [comment]
Acceptance Criteria:  
---

### Acceptance Criteria for peer review:
--
### Documentation is updated:
- [ ]  Test Categories md is updated
- [ ]  USAGE md is updated
- [ ]  Installation instructions is updated

###  Common steps
- [ ]  Find or create a K8s cluster to use
  - [ ] Steps for creating will be in another ticket  
- [ ]  Talk with team for access to an existing cluster
- [ ]  Set the KUBECONFIG environment variable for accessing the target K8s cluster
- [ ]  As a developer, Pull down latest version of CNF conformance test code from {FEATURE} branch
     - [ ]  Check that {FEATURE} Branch passes all A/C 
     - [ ]  Check that {FEATURE} Branch passes tests in Travis CI
- [ ]  As a peer reviewer, check that PR passes Travis CI tests
     - [ ]  if yes, merge PR to master
     - [ ]  if no, make a comment and request that developer make changes to pass tests 
- [ ]  As a peer reviewer, Pull down latest version of CNF conformance test code from `master` branch
- [ ]  Run `shards install`
- [ ]  Run `crystal spec`
- [ ]  I expect to see PASSED for the tests

**Update example CNFs cnf-conformance.yml, if needed**
- [ ] continue, If there is an update to cnf-conformance.yml
- [ ] for each CNF Example
- [ ] Update the example CNF's cnf-conformance.yml to include the new changes
- [ ] Update the example CNF's README if needed
- [ ] Test the example CNF following it's README

### I would expect the CNF to pass when I run the entire test suite (`all`)
- [ ] Follow common steps above
- [ ] Run  `crystal src/cnf-conformance.cr setup`
- [ ] Run  `crystal src/cnf-conformance.cr sample_coredns_setup`
- [ ] Run  `crystal src/cnf-conformance.cr all`
- [ ] I expect to see the output from the test
- [ ] I expect to see PASSED for the test

**Comment by lixuna** [comment]
Level of effort: 0,1,2,3,5,8,13,21 pts = 
---

**Comment by taylor** [comment]
@wavell @nupejosh A/C documentation steps are not checked and I noticed some doc updates are needed.

Please update documentation to remove old instructions using cnf_setup command.  See https://github.com/cncf/cnf-conformance/blob/master/INSTALL.md#configure-the-conformance-suite-for-testing-a-cnf

>>> Setup your CNF for testing and deploy it to the cluster by running cnf-conformance cnf_setup cnf-config=path_to_your/cnf_folder
NOTE: if you do not want to automatically deploy the using the helm chart defined in the configuration then you MUST pass deploy_with_chart=false to the cnf_setup command.

**Comment by taylor** [comment]
A/C will not pass if using the latest binary for *I would expect the CNF to pass when I run the entire test suite (all)*. 

@wavell @nupejosh @williscool please create a new tagged release, eg. v0.7.0.


----

Current binary (v0.6.2-snapshot) testing:

 :heavy_check_mark: Follow common steps above
 :heavy_check_mark: Run ./cnf-conformance setup
 :heavy_check_mark: Run ./cnf-conformance all cnf-config=./example-cnfs/coredns/cnf-conformance.yml

Expecations:
- Test show PASSED/FAILED for CNF
- Test result at end
- No errors about using cnf-conformance.yml

Results:
- exceptions / errors using cnf-conformance.yml
 - only 2 PASSED/FAILED messages out of entire set

```
/home/pair/src/will/cnf-conformance/src/tasks/utils/sample_utils.cr:17:5 in 'cnf_conformance_yml'  
/home/pair/src/will/cnf-conformance/src/tasks/microservice.cr:28:16 in '->'         
/home/pair/src/will/cnf-conformance/lib/sam/src/sam/task.cr:39:29 in 'call'                                                   
/home/pair/src/will/cnf-conformance/lib/sam/src/sam/task.cr:39:29 in 'call'                                                             
/home/pair/src/will/cnf-conformance/lib/sam/src/sam.cr:43:5 in '__crystal_main'
/usr/share/crystal/src/crystal/main.cr:106:5 in 'main'                                                                          
???                                                                                                                                     
???                                                                                                 
No cnf_conformance.yml found! Did you run the setup task? 
```

**Comment by taylor** [comment]
A/C on `master` using a compiled binary: PASSES


Commands:
-  Initialize test suite `./cnf-conformance setup`
- Run all tests with a example configuration file for CoreDNS `./cnf-conformance all cnf-config=./example-cnfs/coredns/cnf-conformance.yml`


```
✔️  PASSED: No privileged containers
✔️  PASSED: Replicas increased to 3 📦📈
✔️  PASSED: Replicas decreased to 1 📦📉
✖️  FAILURE: IP addresses found
✔️  PASSED: Helm liveness probe found
✔️  PASSED: Helm readiness probe found
✔️  PASSED: CNF coredns-coredns Rolling Update Passed
✔️  PASSED: NodePort is not used
✔️  PASSED: No hard-coded IP addresses found in the runtime K8s configuration
✔️  PASSED: Helm Chart cnfs/coredns/helm_chart/coredns Lint Passed
✔️  PASSED: Published Helm Chart Found
✖️  FAILURE: Helm deploy failed
✔️  PASSED: Image size is good
✔️  PASSED: CNF had a reasonable startup time 🚀
Final score: 73
Results have been saved to cnf-conformance-results-20200520-222657-261.yml
```

**Comment by wavell** [comment]
@taylor  After running Crystal spec as in the instructions you get a binary.  So you don't need to build one or download

**Comment by taylor** [comment]
We can look at how to handle tagged releases being out of sync with the default master branch which is what's seen when folks click through.  

Linking to a specific tagged version of docs may be needed to make sure a binary release works with the docs.

cc: @lixuna @wavell
