### ISSUE TITLE
[CNF Developer UX] reorganize INSTALL.md to display "CNF Developer Install and Usage guide" at the top of the page

### ISSUE THREAD

**Issue by lixuna** [cncf/cnf-conformance#220]
### [CNF Developer UX] reorganize INSTALL.md to display "CNF Developer Install and Usage guide" at the top of the page

**Documentation tasks:**
- [x] Update [installation instructions](https://github.com/cncf/cnf-conformance#installation) 
- [x] Move CNF Developer Install and Usage guide to the top of the page, above SOURCE INSTALL section
- [ ] 

**QA tasks**

Dev Review: 
- [x] walk through A/C
- [x] do you get the expected result?
- [x] if yes, 
   - [x] move to `Needs Peer Review` column  
   - [x] create Pull Request and follow check list
   - [x] Assign 1 or more people for peer review
- [ ] if no, document what additional tasks will be needed

Peer review:
- [ ] walk through A/C
- [ ] do you get the expected result?
- [ ] if yes, 
   - [ ] move to `Reviewer Approved` column
   - [ ] Approve pull request
- [ ] if no, 
   - [ ] document what did not go as expected, including error messages and screenshots (if possible)
   - [ ] Add comment to pull request
   - [ ] request changes to pull request

**Comment by williscool** [comment]
lgtm
