### ISSUE TITLE
[Beta Test] Beta Test Instructions - Phase 1 

### ISSUE THREAD

**Issue by lixuna** [cncf/cnf-conformance#232]
### [Beta Test] Beta Test Instructions - Phase 1

Tasks:
- [x] brainstorming
- [x] draft of beta instructions at https://hackmd.io/QjLxg3FAS16oUupRs8ki5A
- [x] peer review of beta instructions draft
- [x] 2nd draft of beta instructions
- [x] peer review of beta instructions draft
- [x] finalize and publish instructions

Instructions by section: 
- [x] Intro
- [x] Outline
- [x] Requirements
- [x] Detailed Steps
- [x] FAQ

**QA tasks**

**Clusters tested**
- [x] cluster 1
- [x] cluster 2
- [x] cluster 3
- [x] cluster 4
- [x] cluster 5
- [x] cluster 6
- [x] cluster 7
- [x] cluster 8
- [x] cluster 9
- [x] cluster 10
- [x] cluster 11

Peer review DRAFT:
- [x] Review draft
- [x] provide feedback on what's missing
- [x] make corrections if needed

Peer review walk through of instructions:
- [x] walk through beta test instructions
- [x] do you get the expected result?
- [x] if yes, 
   - [x] Click the check mark for the cluster in the description
   - [ ] add a comment to this ticket which includes the cluster tested on, date tested, and the result
- [ ] if no, 
   - [ ] document what did not go as expected, including error messages and screenshots (if possible)
   - [ ] Add comment with documented information to this ticket

**Comment by lixuna** [comment]
Intro has been added to  https://hackmd.io/QjLxg3FAS16oUupRs8ki5A#Intro

**Comment by lixuna** [comment]
Level of effort: 0,1,2,3,5,8,13,21:
---

**Comment by taylor** [comment]
Clusters for testing were created in #238.

Peer review testers:
- @agentpoyo: clusters 1, 2
- @taylor : clusters 3, 4
- @denverwilliams clusters 5, 6
- @wavell: cluster 7
- @lixuna: cluster 8
- @williscool: cluster 9
- @nupejosh: cluster 10

**Comment by agentpoyo** [comment]
Did another run through on Beta Test instructions:

Had to add `cnf-conformance cnf_setup cnf-path=./path-to-example` as it as missing and still required.
