### ISSUE TITLE
[Documentation] Create "New Example CNF" issue template

### ISSUE THREAD

**Issue by lixuna** [cncf/cnf-conformance#237]
### [Documentation] Create "New Example CNF" issue template

Tasks:
- [x] Create a drafted issue template for adding new CNF Examples to  https://github.com/cncf/cnf-conformance/tree/master/example-cnfs
- [ ] Add comment suggesting updates as needed for:
  - [ ] the [README](https://github.com/cncf/cnf-conformance/blob/master/README.md)
  - [ ] the contributing.md guide #26 
  - [ ] any presentation slides
- [ ] Tag 1 or more people to peer review

**QA tasks**

Dev Review: 
- [ ] walk through A/C
- [ ] do you get the expected result?
- [ ] if yes, 
   - [ ] move to `Needs Peer Review` column  
   - [ ] create Pull Request and follow check list
   - [ ] Assign 1 or more people for peer review
- [ ] if no, document what additional tasks will be needed

Peer review:
- [ ] walk through A/C
- [ ] do you get the expected result?
- [ ] if yes, 
   - [ ] move to `Reviewer Approved` column
   - [ ] Approve pull request
- [ ] if no, 
   - [ ] document what did not go as expected, including error messages and screenshots (if possible)
   - [ ] Add comment to pull request
   - [ ] request changes to pull request

**Comment by taylor** [comment]
lgtm
