### ISSUE TITLE
Bugfix: microservice test doesn't clean up envoy

### ISSUE THREAD

**Issue by wavell** [cncf/cnf-conformance#240]
### Bug fix: Bugfix: microservice test doesn't clean up envoy

**Short description:** 
cleanup needs new cnf-config option and a force option to ensure cleanup happens

**Environment set up tasks:**

**Upstream tool set up tasks: (conformance suite + upstream tools)**
- N/A

**CNF setup Tasks** 

**Sample CNF tasks:**

**Code implementation tasks:**
- [ ] TBD

**Documentation tasks:**
- [ ] Update [Test Categories md](https://github.com/cncf/cnf-conformance/blob/master/TEST-CATEGORIES.md) if needed (Test already documented)
- [ ] Update [USAGE md](https://github.com/cncf/cnf-conformance/blob/master/USAGE.md) if needed 
- [ ] Update [installation instructions](https://github.com/cncf/cnf-conformance#installation)  if needed 

**QA tasks**

Dev Review: 
- [ ] walk through A/C
- [ ] do you get the expected result?
- [ ] if yes, 
   - [ ] move to `Needs Peer Review` column  
   - [ ] create Pull Request and follow check list
   - [ ] Assign 1 or more people for peer review
- [ ] if no, document what additional tasks will be needed

Peer review:
- [ ] walk through A/C
- [ ] do you get the expected result?
- [ ] if yes, 
   - [ ] move to `Reviewer Approved` column
   - [ ] Approve pull request
- [ ] if no, 
   - [ ] document what did not go as expected, including error messages and screenshots (if possible)
   - [ ] Add comment to pull request
   - [ ] request changes to pull request

**Comment by taylor** [comment]
@wavell @denverwilliams add A/C please and I will test.  Feel free to also add a comment that it's been tested as working..

**Comment by lixuna** [comment]
@wavell @denverwilliams what is remaining on this issue?

Also what is the level of effort in points?

**Comment by wavell** [comment]
![image](https://user-images.githubusercontent.com/29548/84683719-41ac6f00-aefd-11ea-8979-e4669585ac04.png)

![image](https://user-images.githubusercontent.com/29548/84683675-30fbf900-aefd-11ea-9410-542e2471b0ce.png)

**Comment by wavell** [comment]
Acceptance Criteria:  
---


### Acceptance Criteria for peer review:
--

###  Common steps
- [ ]  Find or create a K8s cluster to use
  - [ ] Steps for creating will be in another ticket  
- [ ]  Talk with team for access to an existing cluster
- [ ]  Set the KUBECONFIG environment variable for accessing the target K8s cluster
- [ ]  As a developer, Pull down latest version of CNF conformance test code from {FEATURE} branch
     - [x]  Check that {FEATURE} Branch passes all A/C 
     - [x]  Check that {FEATURE} Branch passes tests in Travis CI
- [x]  As a peer reviewer, check that PR passes Travis CI tests
     - [x]  if yes, merge PR to master
     - [ ]  if no, make a comment and request that developer make changes to pass tests 
- [x]  As a peer reviewer, Pull down latest version of CNF conformance test code from `master` branch
- [x]  Run `shards install`
- [x]  Run `crystal spec`
- [x]  I expect to see PASSED for the tests


### I would expect the CNF to pass when I run the microservice spec in the test suite 
- [ ] Follow common steps above
- [ ] Run  `crystal spec spec/microservice_spec.cr -v`
- [ ] I expect to see the output from the test
- [ ] Run `ls cnfs`
- [ ] I expect to see an empty directory

**Comment by wavell** [comment]
![image](https://user-images.githubusercontent.com/29548/84683719-41ac6f00-aefd-11ea-8979-e4669585ac04.png)

![image](https://user-images.githubusercontent.com/29548/84683675-30fbf900-aefd-11ea-9410-542e2471b0ce.png)

**Comment by wavell** [comment]
1 point

**Comment by williscool** [comment]
verifed removal.
