### ISSUE TITLE
[Beta Test] in QA, error found "****Warning**** task [command] not found in points.yml"

### ISSUE THREAD

**Issue by lixuna** [cncf/cnf-conformance#248]
### [Beta Test] in QA, error found "****Warning**** task [command] not found in points.yml"

Short description:
- during QA of the beta test instructions, several warnings appeared for various workload tests.

Examples: 

-  ****Warning**** task reasonable_startup_time not found in points.yml
-  ****Warning**** task nodeport_not_used not found in points.yml
-  ****Warning**** task hardcoded_ip_addresses_in_k8s_runtime_configuration not found in points.yml
-  ****Warning**** task helm_chart_published not found in points.yml
-  ****Warning**** task helm_deploy not found in points.yml
-  ****Warning**** task reasonable_image_size not found in points.yml

**Environment set up tasks:**

**Upstream tool set up tasks: (conformance suite + upstream tools)**
- N/A

**CNF setup Tasks** 

**Sample CNF tasks:**

**Code implementation tasks:**
- [ ] TBD

**Documentation tasks:**
- [ ] Update [Test Categories md](https://github.com/cncf/cnf-conformance/blob/master/TEST-CATEGORIES.md) if needed (Test already documented)
- [ ] Update [USAGE md](https://github.com/cncf/cnf-conformance/blob/master/USAGE.md) if needed 
- [ ] Update [installation instructions](https://github.com/cncf/cnf-conformance#installation)  if needed 

**QA tasks**

Dev Review: 
- [ ] walk through A/C
- [ ] do you get the expected result?
- [ ] if yes, 
   - [ ] move to `Needs Peer Review` column  
   - [ ] create Pull Request and follow check list
   - [ ] Assign 1 or more people for peer review
- [ ] if no, document what additional tasks will be needed

Peer review:
- [ ] walk through A/C
- [ ] do you get the expected result?
- [ ] if yes, 
   - [ ] move to `Reviewer Approved` column
   - [ ] Approve pull request
- [ ] if no, 
   - [ ] document what did not go as expected, including error messages and screenshots (if possible)
   - [ ] Add comment to pull request
   - [ ] request changes to pull request

**Comment by lixuna** [comment]
Root Cause: 
- points.yml was not looking at the latest binary 

Solution: 
- add another step to the instructions to download a specific points.yml file

**Comment by taylor** [comment]
Updated instructions
