### ISSUE TITLE
[BUG] in Beta QA, max score is too high for the actual tests that are running

### ISSUE THREAD

**Issue by lixuna** [cncf/cnf-conformance#251]
**Describe the bug**
- During pre-Beta QA, the CoreDNS score was 73 out of 210. The max score is way too high for the actual tests that are running. 

**To Reproduce**
1. Clone repo (eg. `git clone git@github.com:cncf/cnf-conformance.git qa251`)
1. Run `shards install`
1. Run `crystal build src/cnf-conformance.cr`
1. Run `./cnf-conformance setup`
1. Run `./cnf-conformance sample_coredns_setup`
1. Run `./cnf-conformance all`

**Expected behavior**
- I would expect to see a final score of 73 out of 75, to reflect the -2 points from the 2 failed tests 
- to see default score values on all tests: pass= +5, fail= -1

**Screenshots**
- N/A - seen on screenshare of someone else's terminal

**Workstation (please complete the following information):**
 - 

**Desktop (please complete the following information): - N/A**

**Smartphone (please complete the following information): - N/A**

**Comment by taylor** [comment]
Quick fix shown in https://github.com/cncf/cnf-conformance/pull/259

All tests listed in points.yml which are not implemented can be "removed" from scoring by setting pass and fail to zero (0).

**Comment by taylor** [comment]
A/C: Running `all` should result in a final score where max score is not higher than the number of points for test which ran:

1. Clone repo (eg. `git clone git@github.com:cncf/cnf-conformance.git qa251`)
1. Run `shards install`
1. Run `crystal build src/cnf-conformance.cr`
1. Run `./cnf-conformance setup`
1. Run `./cnf-conformance sample_coredns_setup`
1. Run `./cnf-conformance all`

Expectation: Final score will have a max score based on sum of max possible points for test which ran.

**Comment by wavell** [comment]
![image](https://user-images.githubusercontent.com/29548/84449765-f7cd3b80-ac13-11ea-9ad8-fea580944a72.png)
