### ISSUE TITLE
[Documentation] create a CONTRIBUTING.md

### ISSUE THREAD

**Issue by lixuna** [cncf/cnf-conformance#26]
### [Documentation] create a CONTRIBUTING.md

Short description:
- to provide potential project contributors with a short guide to how they can help with the CNF Conformance Test Suite

Location: 
- https://github.com/cncf/cnf-conformance

Tasks:
- [x]  Reference upstream contributor guides such as https://github.com/kubernetes/community/tree/master/contributors/guide
- [x]  Create an outline
- [x]   Create a rough draft
- [x]   Peer review of draft
- [x]   Iterate as needed, peer review (optional)
- [x]   Add content to https://github.com/cncf/cnf-conformance/blob/master/CONTRIBUTING.md

**Comment by taylor** [comment]
Maybe add [2020-02-25 - CNF Conformance User Profiles
](https://hackmd.io/-ide30W2SL2keYVdRLryZQ?view)

**Comment by lixuna** [comment]
Starting rough draft at https://hackmd.io/3VBXoMbeQoGVFaF67htl9w

**Comment by lixuna** [comment]
updated draft, review for peer review https://hackmd.io/3VBXoMbeQoGVFaF67htl9w
