### ISSUE TITLE
Sample CNFs for testing in with the CNF Conformance suite

### ISSUE THREAD

**Issue by taylor** [cncf/cnf-conformance#27]
To help with developing and continually testing the CNF Conformance suite it would be nice to have a set of sample CNFs to use.

General requirements or guidelines for the samples:
- Easy to install (eg. helm v3.0)
- No host modifications
- Easy to install K8s extensions (if required), with no host reboot required
- Information on how the CNF is used in a real world use case (so it's purpose can be communicated)

Feel free to ideas for CNFs
-  directly to the ticket
-  more extended info to the [hackmd shared markdown](https://hackmd.io/VJV3YYtuRHqvs5_syRYj9A) (or a new one if needed)

**Comment by taylor** [comment]
https://hackmd.io/VJV3YYtuRHqvs5_syRYj9A

**Comment by taylor** [comment]
https://01.org/intel-data-plane-performance-demonstrators/prox-overview

**Comment by petorre** [comment]
We moved PROX documentation from 01.org to OPNFV web:
- Automation scripts documentation https://wiki.opnfv.org/display/SAM/Rapid+scripting and
- code https://git.opnfv.org/samplevnf/tree/VNFs/DPPD-PROX/helper-scripts/rapid .

Latest version there is now containerized.

For NFVI Performance Characterization: @michaelspedersen and I plan to contribute it to CNF Testbed and Conformance suite.

**Comment by lixuna** [comment]
New example CNF ideas may be added to the documentation at https://github.com/cncf/cnf-conformance/blob/master/EXAMPLE-CNFS.md via pull request

Closing this issue.
