### ISSUE TITLE
[Beta Test] Delete beta test clusters

### ISSUE THREAD

**Issue by lixuna** [cncf/cnf-conformance#292]
Description

- [x]  delete most of the clusters used during beta testing cnf conformance test
- [x]  keep the following machines active until TBD
     - [x] beta-ewr1-c1
     - [x] beta-ewr1-c4 

Tasks:
- [x]  delete:
     - [x] beta-ams1-c1
     - [x] beta-ams1-c2
     - [x] beta-ams1-c3
     - [x] beta-ams1-c4
     - [x] beta-ams1-c5
     - [x] beta-ams1-c6
     - [x] beta-ewr1-c2
     - [x] beta-ewr1-c3
     - [x] beta-ewr1-c5

**Comment by agentpoyo** [comment]
![bulk_delete_beta_tests_clusters](https://user-images.githubusercontent.com/14348948/85794761-c157ec00-b6fc-11ea-909d-71dbc95eb417.png)

**Comment by agentpoyo** [comment]
All instances have been deleted besides ewr1-c1 and ewr1-c4 clusters.
