### ISSUE TITLE
[BUG] SSL_connect failures when running tool

### ISSUE THREAD

**Issue by fkautz** [cncf/cnf-conformance#295]
**Describe the bug**
When running conformance tests, I get the following error:

SSL_connect: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed
/usr/local/depot/crystal-0.33.0-1/share/crystal/src/openssl/ssl/socket.cr:15:11 in 'socket'
/usr/local/depot/crystal-0.33.0-1/share/crystal/src/http/client.cr:656:19 in 'exec_internal_single'
/usr/local/depot/crystal-0.33.0-1/share/crystal/src/http/client.cr:581:5 in 'perform'
/home/pair/workspace/taylor/qa/jun8/lib/halite/src/halite/client.cr:115:9 in 'request'
/home/pair/workspace/taylor/qa/jun8/lib/halite/src/halite/chainable.cr:485:7 in '->'
/home/pair/workspace/taylor/qa/jun8/src/tasks/utils/utils.cr:255:3 in 'task_runner'
/home/pair/workspace/taylor/qa/jun8/src/tasks/microservice.cr:93:3 in '->'
/home/pair/workspace/taylor/qa/jun8/lib/sam/src/sam/task.cr:39:29 in 'call'
/home/pair/workspace/taylor/qa/jun8/lib/sam/src/sam/task.cr:39:29 in 'call'
/home/pair/workspace/taylor/qa/jun8/lib/sam/src/sam.cr:43:5 in '__crystal_main'
/usr/local/depot/crystal-0.33.0-1/share/crystal/src/crystal/main.cr:106:5 in 'main'
???
???
Warning: kubectl apply should be used on resource created by either kubectl create --save-config or kubectl apply
Warning: kubectl apply should be used on resource created by either kubectl create --save-config or kubectl apply

**To Reproduce**
```
./cnf-conformance microservice
```

see error

**Expected behavior**
No error.

**Workstation (please complete the following information):**
 - OS Linux
 - Distro NixOS
 - Version 20.03
 - Architecture x86_64

**Comment by agentpoyo** [comment]
@fkautz 

What does `kubectl cluster-info` display?

Were you able to run `./cnf-conformance all` successfully prior to running he `microservice`?

If so, did you run `./cnf-conformance setup` prior to running `./cnf-conformance microservice`?

Thanks.

**Comment by taylor** [comment]
pair@cnfdev03:~/workspace/taylor/qa/r/qa157$ ./cnf-conformance setup
Global helm found. Version: v3.1.2
Local helm found. Version: v3.1.1
Global wget found. Version: 1.19.4
No Local wget version found
Global curl found. Version: 7.58.0
No Local curl version found
Global kubectl found. Version: 1.14
No Local kubectl version found
All prerequisites found.
create_results_yml
file exists?:false
Successfully created directories for cnf-conformance
Setup complete


pair@cnfdev03:~/workspace/taylor/qa/r/qa157$ ./cnf-conformance microservice
✔️  PASSED: Image size is good
Error from server (AlreadyExists): namespaces "startup-test" already exists
✔️  PASSED: CNF had a reasonable startup time 🚀
Microservice final score: 10 of 10

**Comment by agentpoyo** [comment]
Cannot reproduce error.
