### ISSUE TITLE
[Feature] Provide a list of CNF commands to run if no command is given. (CLI help getting started)

### ISSUE THREAD

**Issue by fkautz** [cncf/cnf-conformance#297]
# Current behavior
```
$ ./cnf-conformance
Hm, nothing to do...
```

# Requested behavior
Something that explains how the cnf conformance tool works.
```
$ ./cnf-conformance
Hi, I'm CNF conformance, and I have Super Cow Powers! Here is how to run me!
* setup
* all
* microservice
* test_name
```

**Comment by lixuna** [comment]
merging issue with #223

**Comment by wavell** [comment]
### Draft/Needs updated - Acceptance Criteria based on #632

---
###  Common steps
- [x]  Find or create a K8s cluster to use
   - Talk with team for access to an existing cluster
   - [Kind K8s clusters](https://github.com/cncf/cnf-conformance/blob/master/KIND-INSTALL.md) will work as well
- [x]  Set the KUBECONFIG environment variable for accessing the target K8s cluster
- [ ]  As a developer, Pull down latest version of CNF conformance test code from {FEATURE} branch
     - [ ]  Check that {FEATURE} Branch passes all A/C 
     - [ ]  Check that {FEATURE} Branch passes tests in GitHub Actions
- [ ]  As a peer reviewer, check that PR passes in GitHub Actions
     - [ ] if yes, merge PR to master
     - [ ]  if no, make a comment and request that developer make changes to pass tests 
- [x]   As a peer reviewer, Pull down latest version of CNF conformance test code from `master` branch
- [x]  Run `shards install`

### Spec test should pass
- [x]  Run `crystal spec`
- [x]  I expect to see PASSED for the tests

### Update documentation 

### Update Prerequisite checker
- [ ] N/A (check for dockerd install)

### Update yml validator, if needed
- [ ] N/A

## Show message on console output for remediation

### When running cnf-conformance with no arguments, I would expect to see list of cnf commands:
- [ ] Follow common steps above
- [ ]  Run `./cnf-conformance`
- [ ]  I expect to see the output from the test
- [ ]  I would expect to help output from the test

**Comment by agentpoyo** [comment]
If no command or argument given, ./cnf-conformance prints out the `help` by default:

![default_output_no_arg_given](https://user-images.githubusercontent.com/14348948/111380185-04cefd80-8672-11eb-96b9-d4cc0efab605.png)

**Comment by lixuna** [comment]
Level of effort in points: 0,1,2,3,5,8,13,21
@wavell 
@agentpoyo

**Comment by agentpoyo** [comment]
3 pts
