### ISSUE TITLE
Migrate off Packet systems needing maintenance July 2020

### ISSUE THREAD

**Issue by taylor** [cncf/cnf-conformance#299]
# Migrate off Packet systems needing July 2020 maintenance 

**Description:**

Systems identified at Packet under the CNF Testbed and CNCF Sandbox project that are in need of hardware maintenance:

- [workstation-01](https://app.packet.net/devices/ad88bdf3-d39b-4048-8625-57d36528e724) (CNF Testbed) - created 11/6/2018 by Vulk Coop
- [workstation-josh](https://app.packet.net/devices/0839fa38-8be9-4df0-b1db-d24dd658e783) (CNF Testbed) - created 5/30/2019 by Joshua Smith, Vulk
- [x1smallworkstation-02](https://app.packet.net/devices/fe85784b-9670-4c44-9743-890ab581b31b) (CNCF Sandbox) - created 11/6/2018 by Vulk Coop 

Tasks:
- [ ] Identify if system is in use and needed
   - [x] workstation-01 (CNF Testbed)
   - [ ] workstation-josh (CNF Testbed)
   - [x] x1smallworkstation (CNCF Sandbox)
- [ ] Migrate to a new system if needed
   - [x] workstation-01 (CNF Testbed)
   - [ ] workstation-josh (CNF Testbed)
   - [x] x1smallworkstation (CNCF Sandbox)
- [x] Release or Delete the instance back to Packet
   - [x] workstation-01 (CNF Testbed)
   - [x] workstation-josh (CNF Testbed)
   - [x] x1smallworkstation (CNCF Sandbox)
- [x] Let Packet know systems are available for maintenance
   - [x] workstation-01 (CNF Testbed)
   - [x] workstation-josh (CNF Testbed)
   - [x] x1smallworkstation (CNCF Sandbox)

**Comment by taylor** [comment]
@denverwilliams, @michaelspedersen  I do not see anything on x1smallworkstation which needs to be saved.  I think this system can be deleted.

**Comment by taylor** [comment]
@nupejosh  please check and handle [workstation-josh ](https://app.packet.net/devices/0839fa38-8be9-4df0-b1db-d24dd658e783)

**Comment by taylor** [comment]
@michaelspedersen do you want or need anything on workstation-01, https://app.packet.net/devices/ad88bdf3-d39b-4048-8625-57d36528e724.  You have a workspace folder (michael_intel)

**Comment by taylor** [comment]
I've backed up my work from workstation-01 under workspace/taylor

**Comment by michaelspedersen** [comment]
@taylor I don't have anything relevant on any of the above mentioned machines.

**Comment by denverwilliams** [comment]
@taylor I went though all the machines and i didn't see anything that's in active use or worth keeping.

**Comment by taylor** [comment]
@agentpoyo please go ahead and delete
-  workstation-01 (CNF Testbed)
-  x1smallworkstation (CNCF Sandbox)

**Comment by agentpoyo** [comment]
workstation-01 (CNF Testbed)
x1smallworkstation (CNCF Sandbox)

Have been deleted.

**Comment by taylor** [comment]
@agentpoyo, from  Packet email:

> These systems are
> 
> workstation-josh (CNF Testbed) - created 5/30/2019 by Joshua Smith, Vulk
> workstation-01 (CNF Testbed) - created 11/6/2018 by Vulk Coop
> x1smallworkstation-02 (CNCF Sandbox) - created 11/6/2018 by Vulk Coop
> 
> I can provide additional identifying info for each if needed. They are all x1.small systems in our EWR facility.

**Comment by agentpoyo** [comment]
@nupejosh 

Can you handle workstation-josh (CNF Testbed) - created 5/30/2019 by Joshua Smith, Vulk

**Comment by taylor** [comment]
@nupejosh, I've deleted workstation-josh

cc: @agentpoyo

**Comment by vielmetti** [comment]
Thank you!
