### ISSUE TITLE
[Process] Adopt CNCF's Code of conduct

### ISSUE THREAD

**Issue by lixuna** [cncf/cnf-conformance#317]
[Process] Adopt and add CNCF's Code of conduct to GitHub repo
---

- [ ] Review https://github.com/cncf/foundation/blob/master/code-of-conduct.md
- [ ] Vote/agree on adoption of CoC
- [ ] Add CoC to cnf-conformance GitHub repo

**Comment by taylor** [comment]
+1 on adopting to follow the CNCF Code of Conduct for CNF Conformance community

**Comment by taylor** [comment]
@agentpoyo, @denverwilliams, @lixuna, @nupejosh, @wavell, @williscool please review the Code of Conduct, https://github.com/cncf/foundation/blob/master/code-of-conduct.md, and vote on adopting it for CNF Conformance with a +1 in this issue.

Note, there is a related PR for adding the code of conduct file created #329

**Comment by agentpoyo** [comment]
+1 on adoption. LGTM.

**Comment by lixuna** [comment]
+1 on adopting CNCF CoC

**Comment by nupejosh** [comment]
+1 for adopting

**Comment by denverwilliams** [comment]
+1
