### ISSUE TITLE
[Feature] Replace hardcoded emojis with variables

### ISSUE THREAD

**Issue by lixuna** [cncf/cnf-conformance#336]
**Problem:** 
- emojis are hardcoded in the code with tests,
- if would be nice to create variables for each emoji set

**Possible solution:**
- Replace hardcoded emojis with variables

**Example of test with hardcoded emojis - to be updated:**
- tbd

**Example of test with emoji variable (what we'd like to see):**
- [chaos_cpu_hog](https://github.com/cncf/cnf-conformance/blob/17f4bd9abed012fced408fe512ece5e0364b064f/src/tasks/resilience.cr#L91)

**Comment by sakshamgurbhele** [comment]
**can I work on this issue?**

**Comment by lixuna** [comment]
Yes and thank you, @sakshamgurbhele!

Here is a link to the [CONTRIBUTING guide](https://github.com/cncf/cnf-conformance/blob/master/CONTRIBUTING.md#coding-style) to help you get started.

**Comment by lixuna** [comment]
FYI - This enhancement has been included in v1.10.0. If any issues are found during peer review, please open a new bug ticket.

**Comment by agentpoyo** [comment]
![emoji_clusterapi_enabled](https://user-images.githubusercontent.com/14348948/105223514-80547880-5b21-11eb-8451-045cd7b72c82.png)

Emoji looks good to me.

**Comment by agentpoyo** [comment]
![emoji_litmus_network](https://user-images.githubusercontent.com/14348948/105223911-0c66a000-5b22-11eb-9e70-f0ca92c267aa.png)
