### ISSUE TITLE
[BUG] Date format for "Releases" is incorrect

### ISSUE THREAD

**Issue by lixuna** [cncf/cnf-conformance#348]
**Problem**
- The releases are showing a typo in the release date

**What I see now:**
- "August, 07 2020" on https://github.com/cncf/cnf-conformance/releases 

**What I would expect to see instead:**
- August 07, 2020

**Alternate approaches**
- Use a shorter date format, like `2020-08-07` (see example https://github.com/prometheus/prometheus/releases) 
- Remove the date from the release notes (see example https://github.com/kubernetes/kubernetes/releases)

**Comment by wavell** [comment]
![image](https://user-images.githubusercontent.com/29548/97928716-3bdcec00-1d2d-11eb-9fae-6464e95f1897.png)

**Comment by lixuna** [comment]
@wavell Has this been merged?

I see the master-0aa8add has the correct date, but the 2 pre-releases after this are not correct: 
- see https://github.com/cncf/cnf-conformance/releases/tag/master-23a4b5a and https://github.com/cncf/cnf-conformance/releases/tag/master-18a3cb6

**Comment by lixuna** [comment]
@wavell @denverwilliams Please add your estimate in points (0,1,2,3,5,8,13,21) in the comments below

**Comment by wavell** [comment]
> @wavell Has this been merged?
> 
> I see the master-0aa8add has the correct date, but the 2 pre-releases after this are not correct:
> 
> * see https://github.com/cncf/cnf-conformance/releases/tag/master-23a4b5a and https://github.com/cncf/cnf-conformance/releases/tag/master-18a3cb6

Those were earlier changes.  The release page doesn't sort properly so those earlier ones appear at the top.

**Comment by lixuna** [comment]
Level of effort in pts: 1
---

@denverwilliams 1
@lixuna 1
