### ISSUE TITLE
Fix platform tests so they can be run independent of a workload cnf

### ISSUE THREAD

**Issue by denverwilliams** [cncf/cnf-conformance#365]
Fix platform tests so they can be run independent of a workload cnf.

**Comment by nupejosh** [comment]
This was tested and works as expected without declaring a `cnf-config` or `cnf-path`.

**Comment by lixuna** [comment]
### Level of effort in pts: 01,2,3,5,8,13,21:

**Comment by williscool** [comment]
@williscool  5 pts

**Comment by nupejosh** [comment]
@nupejosh 3 pts

**Comment by lixuna** [comment]
@denverwilliams @wavell @taylor @agentpoyo Can you please estimate the level of effort on this bug fix issue?

**Comment by lixuna** [comment]
@taylor said 3

**Comment by lixuna** [comment]
@denverwilliams said 3

**Comment by agentpoyo** [comment]
@agentpoyo says 3
