### ISSUE TITLE
[BUG] Errors when setting up cnf-conformance

### ISSUE THREAD

**Issue by lixuna** [cncf/cnf-conformance#369]
**Describe the bug**
https://cloud-native.slack.com/archives/C014TNCEX8R/p1598376537001100

Sravan G Today at 12:28 PM

> Hi,
> I am working on cnf-conformance setup locally in my system, have followed installation guide from the below link provided
> https://github.com/cncf/cnf-conformance/blob/master/INSTALL.md
> I am facing Not found config file cnf-conformance after executing below command
> cnf-conformance all cnf-config=./cnf-conformance.yml
> and also below error
> Unhandled exception: Error opening file 'cnf-conformance' with mode 'r': No such file or directory (Errno)
> Failed to raise an exception: END_OF_STACK.
> for cnf-conformance.yml I am referring to https://github.com/cncf/cnf-conformance/blob/master/cnf-conformance.example.yml.

**To Reproduce**
- [ ] TBD

**Screenshots**

**Workstation (please complete the following information):**
 - OS [e.g. Linux]
 - Distro [e.g. Ubuntu]
 - Version [e.g. 18.04]
 - Architecture [e.g. x86, arm]

**Desktop (please complete the following information):**

**Additional context**

**Comment by wavell** [comment]
```
I am facing Not found config file cnf-conformance after executing below command
cnf-conformance all cnf-config=./cnf-conformance.yml
and also below error
Unhandled exception: Error opening file 'cnf-conformance' with mode 'r': No such file or directory (Errno)
Failed to raise an exception: END_OF_STACK.
for cnf-conformance.yml 
```
The problem seems to be when you ran  `cnf-conformance all cnf-config=./cnf-conformance.yml` there wass not a ./cnf-conformance.yml in your local directory.  
There are two ways to solve this problem.  
1. When running the cnf conformance suite against the existing examples
  - Run something like `cnf-conformance all cnf-config=./example-cnfs/coredns/cnf-conformance.yml` or you can use any of the other cnfs under example-cnfs
2.  When running the cnf conformance suite against an external cnf (perhaps one you are working on)
  - In the Install.md:  
  ```
Create a Conformance configuration file called cnf-conformance.yml under 
your CNF folder (eg. cnfs/my_ipsec_cnf/cnf-conformance.yml)
...
cnf-conformance all cnf-config=<path to your config yml>/cnf-conformance.yml
```
  - So you'll need to do something like`cnf-conformance all cnf-config=./my_ipsec_cnf/coredns/cnf-conformance.yml` with the directory of your cnf-conformance.yml file

**Comment by agentpoyo** [comment]
I posted this in the slack channel but posting here for good measure:

The following works for me using one of our example cnf-conformance.yml files follwing the basic steps and the latest binary curl install method:

```
source <(curl https://raw.githubusercontent.com/cncf/cnf-conformance/master/curl_install.sh)
cnf-conformance setup 
wget https://raw.githubusercontent.com/cncf/cnf-conformance/master/example-cnfs/coredns/cnf-conformance.yml
cnf-conformance all cnf-config=./cnf-conformance.yml
```
![cnf-conformance](https://user-images.githubusercontent.com/14348948/91325740-2a092680-e789-11ea-93cf-8a2279da51b2.png)


I believe something is wrong with the cnf-conformance.yml being used. Either it's empty or not valid.

**Comment by williscool** [comment]
Recognize that a comment I made on the install doc stuff is actually pertinent to this ticket

https://github.com/cncf/cnf-conformance/issues/370#issuecomment-684534283

**Comment by williscool** [comment]
useful for this

https://github.com/cncf/cnf-conformance/tree/master/tools/curl_install_tester_docker_setup

**Comment by wavell** [comment]
#398 was probably causing an issue with this as well

**Comment by agentpoyo** [comment]
> #398 was probably causing an issue with this as well

The user didn't specify but I would say if they pull down the latest binary, this error should be fixed. There was previous binary around this time frame that no argument passed would work, failing with the error the user saw.

**Comment by agentpoyo** [comment]
Marking this as reviewer approved, this bug should be addressed now.
