### ISSUE TITLE
[Documentation] update INSTALL.md for clarity and ease of use

### ISSUE THREAD

**Issue by lixuna** [cncf/cnf-conformance#370]
**Is your feature request related to a problem? Please describe.**
The [INSTALL.md](https://github.com/cncf/cnf-conformance/blob/master/INSTALL.md) documentation could be improved. 

**Describe the solution you'd like**
Please walk through the set up process(es) and update the [INSTALL.md](https://github.com/cncf/cnf-conformance/blob/master/INSTALL.md) as needed

**Comment by taylor** [comment]
@williscool After the INSTALL.md is updated the installation section for the README can be simplified to have less choices -- specifically for curl (pick one)

that can be another ticket 🤷 

cc: @lixuna

**Comment by agentpoyo** [comment]
@williscool you can look at my response in Bug #369 where I did the basic steps to run a test after pulling down one of our example cnf-conformance.yml for use. https://github.com/cncf/cnf-conformance/issues/369#issuecomment-680961684

They can use ours or they use their own (outlined in the steps).

**Comment by lixuna** [comment]
Note: the [install guide](https://github.com/cncf/cnf-conformance/blob/9327b50a695ba6a8d84575b523ac523c0f0476eb/INSTALL.md#configure-the-conformance-suite-for-testing-a-cnf) says: Create a Conformance configuration file called cnf-conformance.yml under the your CNF folder (eg. `cnfs/my_ipsec_cnf/cnf-conformance.yml`)

 Please replace  (eg. `cnfs/my_ipsec_cnf/cnf-conformance.yml`) with a working example

**Comment by williscool** [comment]
@denverwilliams  @wavell 

getting

```
root@d19507a019ae:/# cnf-conformance sample_coredns_setup
Successfully created directories for cnf-conformance
--: 1: wget: not found
tar: //tools/helm/helm-v3.1.1-linux-amd64.tar.gz: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now
--: 1: //tools/helm/linux-amd64/helm: not found
I, [2020-08-31 19:30:36 UTC #2860]  INFO -- cnf-conformance-verbose: sample_setup_args
find: 'sample-cnfs/sample-coredns-cnf/*': No such file or directory
Unhandled exception: Error opening file 'cnf-conformance' with mode 'r': No such file or directory (Errno)
Failed to raise an exception: END_OF_STACK
[0x7f0931e75e76] ???
on the latest docker ubuntu image after following the curl isntall instuctions like so
docker pull ubuntu
docker run --rm -it ubuntu
apt-get update
apt-get install curl
source <(curl https://raw.githubusercontent.com/cncf/cnf-conformance/master/curl_install.sh)
cnf-conformance sample_coredns_setup

```



wharris3  12 hours ago
also I think the logs when you don't have helm / wget could be more clear

```
root@264f70370ed2:/# cnf-conformance setup
--: 1: helm: not found
Global helm found. Version:
Local helm found. Version:
--: 1: wget: not found
No Global wget version found
No Local wget version found
Setup failed. Some prerequisites are missing. Please install all of the prerequisites before continuing.
```


wharris3  12 hours ago
was just about to update after having done so still getting the same issue. also looks like wget and helm both need to be added as deps
apt-get install wget
curl -LO "https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl"
chmod +x ./kubectl
mv ./kubectl /usr/local/bin/kubectl
root@264f70370ed2:~# cnf-conformance setup
Global helm found. Version: v3.3.1
Local helm found. Version: v3.1.1
Global wget found. Version: 1.20.3
No Local wget version found
Global curl found. Version: 7.68.0
No Local curl version found
The connection to the server localhost:8080 was refused - did you specify the right host or port?
Global kubectl found. Version: 1.19
No Local kubectl version found
All prerequisites found.
Successfully created directories for cnf-conformance
Setup complete
root@264f70370ed2:~# cnf-conformance sample_coredns_setup
Successfully created directories for cnf-conformance
I, [2020-08-31 19:48:37 UTC #3201]  INFO -- cnf-conformance-verbose: sample_setup_args
find: 'sample-cnfs/sample-coredns-cnf/*': No such file or directory
Unhandled exception: Error opening file 'cnf-conformance' with mode 'r': No such file or directory (Errno)
Failed to raise an exception: END_OF_STACK
[0x7fbb51b0ae76] ???
[0x7fbb518df89b] ???
[0x7fbb518e0185] ???
[0x7fbb518ecf34] ???
[0x7fbb518e525c] ???
[0x7fbb518e4a79] ???
[0x7fbb51931df5] ???
[0x7fbb5190015c] ???
[0x7fbb518e28f7] ???
[0x7fbb51d86054] ???
root@264f70370ed2:~#




wharris3  12 hours ago
setup  is working but sample_coredns_setup  is now




denverwilliams  12 hours ago
Oh.... I forgot. We warn if dependencies aren't installed, but it's up to the user to installed the packages setup says are missing.




denverwilliams  12 hours ago
Setup failed. Some prerequisites are missing. Please install all of the prerequisites before continuing.




wharris3  12 hours ago
yeah im updating the doc to reflect that now




wharris3  12 hours ago
but sample_coredns_setup  doesn't work with the curl install
but
wget -O cnf-conformance.yml https://raw.githubusercontent.com/cncf/cnf-conformance/release-v0.7-beta1/example-cnfs/coredns/cnf-conformance.yml
cnf-conformance cnf_setup cnf-config=./cnf-conformance.yml
does though...
how should we deal with that?
have them just do the wget  of the conformance yml ?
or add more setups to download so sample_coredns_setup  works out of the box?

**Comment by williscool** [comment]
also added a docker file we can use to test curl install

https://github.com/cncf/cnf-conformance/tree/maint/%23370_update_install_doc/tools/curl_install_tester_docker_setup
