### ISSUE TITLE
[BUG] `Not found config: Helm chart` error when installing cnf conformance

### ISSUE THREAD

**Issue by lixuna** [cncf/cnf-conformance#375]
**Describe the bug**
[BUG] `Not found config: Helm chart` error when installing cnf conformance

**Short description:** 
- error reported on slack https://cloud-native.slack.com/archives/C014TNCEX8R/p1598523119005400 

**Screenshots**
![image (10)](https://user-images.githubusercontent.com/11701267/91455736-153f9800-e848-11ea-85e4-0eb33ec876c5.png)
![image (9)](https://user-images.githubusercontent.com/11701267/91455739-1670c500-e848-11ea-8bb1-2a60750d1287.png)

**Workstation (please complete the following information):**
- TBD

**Additional context**
- TBD

**Comment by taylor** [comment]
The https://github.com/cncf/cnf-conformance/blob/master/cnf-conformance.example.yml is no longer valid unfortunately.


Please try copying https://github.com/cncf/cnf-conformance/blob/master/example-cnfs/coredns/cnf-conformance.yml

**Comment by taylor** [comment]
Example helm charts
- https://github.com/cncf/cnf-testbed/tree/master/examples/use_case/ipsec/ipsec
- https://hub.helm.sh/charts/stable/coredns
