### ISSUE TITLE
[BUG] Platform Resilience Totals inaccurate

### ISSUE THREAD

**Issue by wavell** [cncf/cnf-conformance#382]
**Describe the bug**
Platform Resilience totals inaccurate

![image](https://user-images.githubusercontent.com/29548/91490172-a11ce880-e877-11ea-8709-31ff4a5f5719.png)

```
# cmd line
./cnf-conformance platform:resilence

**Comment by wavell** [comment]
![image](https://user-images.githubusercontent.com/29548/91491006-00c7c380-e879-11ea-8d6b-03b4109a6b7f.png)

**Comment by lixuna** [comment]
@wavell what was the level of effort (in points) to resolve this bug?

01,2,3,5,8,13,21?

**Comment by williscool** [comment]
looks like a 2 to me

**Comment by lixuna** [comment]
sharing: @wavell said 3
