### ISSUE TITLE
[BUG] Travis KIND cluster fails intermittently with etcd failures

### ISSUE THREAD

**Issue by wavell** [cncf/cnf-conformance#384]
**Describe the bug**
Travis KIND cluster fails intermittently with etcd failures

![image](https://user-images.githubusercontent.com/29548/91495280-f78e2500-e87f-11ea-81d8-002ff6dd7b05.png)

**To Reproduce**
1. Create a new build for cnf-conformance and push it to travis

**Comment by taylor** [comment]
@williscool or @agentpoyo please peer review

**Comment by agentpoyo** [comment]
+1 LGTM

Not reproduced, reviewed travis builds since merging; confirmed with @watson and @denverwilliams code is being used in production builds and the error has not been seen since merging into master branch.
