### ISSUE TITLE
[Feature] Update pre-req checker to include Git

### ISSUE THREAD

**Issue by lixuna** [cncf/cnf-conformance#385]
### [Feature] Update pre-req checker to include Git

**Describe the solution you'd like**
- Currently Pre-req checker does not include Git 
- Add Git to pre-req checker

### Implementation Tasks: TBD

**Environment set up tasks:**
- [ ]  N/A

**Upstream tool set up tasks: (conformance suite + upstream tools)**
- [ ]  N/A

**Code implementation tasks:**
- [ ]  update pre-req checker

**Documentation tasks:**
- [ ] Update [Test Categories md](https://github.com/cncf/cnf-conformance/blob/master/TEST-CATEGORIES.md) if needed 
- [ ] Update [Pseudo Code md](https://github.com/cncf/cnf-conformance/blob/master/PSEUDO-CODE.md) if needed
- [ ] Update [USAGE md](https://github.com/cncf/cnf-conformance/blob/master/USAGE.md) if needed 
- [ ] Update [installation instructions](https://github.com/cncf/cnf-conformance#installation)  if needed 

### QA tasks

Dev Review: 
- [ ] walk through A/C
- [ ] do you get the expected result?
- [ ] if yes, 
   - [ ] move to `Needs Peer Review` column  
   - [ ] create Pull Request and follow check list
   - [ ] Assign 1 or more people for peer review
- [ ] if no, document what additional tasks will be needed

Peer review:
- [ ] walk through A/C
- [ ] do you get the expected result?
- [ ] if yes, 
   - [ ] move to `Reviewer Approved` column
   - [ ] Approve pull request
- [ ] if no, 
   - [ ] document what did not go as expected, including error messages and screenshots (if possible)
   - [ ] Add comment to pull request
   - [ ] request changes to pull request

**Comment by lixuna** [comment]
### Level of effort in pts: 01,2,3,5,8,13,21:

**Comment by taylor** [comment]
### Acceptance Criteria:

### Acceptance Criteria for peer review:
--
### Documentation is updated:
- No specific `git` documentation needed
- General documentation for prereqs is being handled in #387 and #374 

###  Common steps
- [ ]  Find or create a K8s cluster to use
  - [ ] Steps for creating will be in another ticket  
- [ ]  Talk with team for access to an existing cluster
- [ ]  Set the KUBECONFIG environment variable for accessing the target K8s cluster
- [ ]  As a developer, Pull down latest version of CNF conformance test code from {FEATURE} branch
     - [ ]  Check that {FEATURE} Branch passes all A/C 
     - [ ]  Check that {FEATURE} Branch passes tests in Travis CI
- [ ]  As a peer reviewer, check that PR passes Travis CI tests
     - [ ]  if yes, merge PR to master
     - [ ]  if no, make a comment and request that developer make changes to pass tests 
- [ ]  As a peer reviewer, Pull down latest version of CNF conformance test code from `master` branch
- [ ]  Run `shards install`

### Spec test should pass
- [ ]  Run `crystal spec`
- [ ]  I expect to see PASSED for the tests

### The git tool should show as installed when running the prereqs command
- [ ] Run `./cnf-conformance prereqs`
- [ ] I should see git is installed

### The cnf-conformance setup should should show git is installed and setup should complete successfully if git (and other prereqs) are installed
- [ ] I follow the [CNF Developer install guide](https://github.com/cncf/cnf-conformance/blob/master/INSTALL.md#cnf-developer-install-and-usage-guide)
- [ ] I can run the `./cnf-conformance setup` command
- [ ] I should see git is installed
- [ ] The output says, “Setup complete."

### The cnf-conformance setup should FAIL and communicate git is not installed when it is not found on the system
- [ ] I follow the [CNF Developer install guide](https://github.com/cncf/cnf-conformance/blob/master/INSTALL.md#cnf-developer-install-and-usage-guide)
- [ ] I can run the `PATH="" ./cnf-conformance setup` command
- [ ] The output says, “Setup failed. Please install the following prerequisites.”
- [ ] The output lists the missing prerequisites with links to how to resolve them
- [ ] When running the integration spec tests prerequisites testing is seen in the output

**Comment by taylor** [comment]
@agentpoyo or @williscool please peer review.

**Comment by agentpoyo** [comment]
LGTM +1

```
root@ubuntu-bionic:~/tmp/cnf-conformance# ./cnf-conformance version
I, [2020-09-15 16:02:45 +00:00 #10791]  INFO -- cnf-conformance: Results file
I, [2020-09-15 16:02:45 +00:00 #10791]  INFO -- cnf-conformance: file exists?:false
I, [2020-09-15 16:02:45 +00:00 #10791]  INFO -- cnf-conformance: VERSION: feature/#385-git-prereq-5b7c3b4
CNF Conformance version: feature/#385-git-prereq-5b7c3b4

root@ubuntu-bionic:~/tmp/cnf-conformance# ./cnf-conformance prereqs
I, [2020-09-15 16:02:49 +00:00 #10793]  INFO -- cnf-conformance: Results file
I, [2020-09-15 16:02:49 +00:00 #10793]  INFO -- cnf-conformance: file exists?:false
Global helm found. Version: v3.1.1
Local helm found. Version: v3.1.1
Global wget found. Version: 1.19.4
No Local wget version found
Global curl found. Version: 7.58.0
No Local curl version found
The connection to the server localhost:8080 was refused - did you specify the right host or port?
Global kubectl found. Version: 1.18
No Local kubectl version found
Global git found. Version: 2.17.1
No Local git version found
All prerequisites found.
```

**Comment by agentpoyo** [comment]
### Acceptance Criteria:

### Acceptance Criteria for peer review:
--
### Documentation is updated:
- No specific `git` documentation needed
- General documentation for prereqs is being handled in #387 and #374 

###  Common steps
- [ ]  Find or create a K8s cluster to use
  - [ ] Steps for creating will be in another ticket  
- [ ]  Talk with team for access to an existing cluster
- [ ]  Set the KUBECONFIG environment variable for accessing the target K8s cluster
- [ ]  As a developer, Pull down latest version of CNF conformance test code from {FEATURE} branch
     - [ ]  Check that {FEATURE} Branch passes all A/C 
     - [ ]  Check that {FEATURE} Branch passes tests in Travis CI
- [ ]  As a peer reviewer, check that PR passes Travis CI tests
     - [ ]  if yes, merge PR to master
     - [ ]  if no, make a comment and request that developer make changes to pass tests 
- [ ]  As a peer reviewer, Pull down latest version of CNF conformance test code from `feature/#385-git-prereq` branch
- [ ]  Run `shards install`

### Spec test should pass
- [ ]  Run `crystal spec`
- [ ]  I expect to see PASSED for the tests

### The git tool should show as installed when running the prereqs command
- [ ] Run `./cnf-conformance prereqs`
- [ ] I should see git is installed

### The cnf-conformance setup should should show git is installed and setup should complete successfully if git (and other prereqs) are installed
- [ ] I follow the [CNF Developer install guide](https://github.com/cncf/cnf-conformance/blob/master/INSTALL.md#cnf-developer-install-and-usage-guide)
- [ ] I can run the `./cnf-conformance setup` command
- [ ] I should see git is installed
- [ ] The output says, “Setup complete."

### The cnf-conformance setup should FAIL and communicate git is not installed when it is not found on the system
- [ ] I follow the [CNF Developer install guide](https://github.com/cncf/cnf-conformance/blob/master/INSTALL.md#cnf-developer-install-and-usage-guide)
- [ ] I can run the `PATH="" ./cnf-conformance setup` command
- [ ] The output says, “Setup failed. Please install the following prerequisites.”
- [ ] The output lists the missing prerequisites with links to how to resolve them
- [ ] When running the integration spec tests prerequisites testing is seen in the output

**Comment by agentpoyo** [comment]
If removal of `git`, prereqs detects missing git:

```
root@ubuntu-bionic:~/tmp/cnf-conformance# ./cnf-conformance prereqs
I, [2020-09-15 16:08:38 +00:00 #10858]  INFO -- cnf-conformance: Results file
I, [2020-09-15 16:08:38 +00:00 #10858]  INFO -- cnf-conformance: file exists?:false
Global helm found. Version: v3.1.1
Local helm found. Version: v3.1.1
Global wget found. Version: 1.19.4
No Local wget version found
Global curl found. Version: 7.58.0
No Local curl version found
The connection to the server localhost:8080 was refused - did you specify the right host or port?
Global kubectl found. Version: 1.18
No Local kubectl version found
--: 1: --: git: not found
No Global git version found
No Local git version found
Setup failed. Some prerequisites are missing. Please install all of the prerequisites before continuing.
```

**Comment by taylor** [comment]
@agentpoyo if specs did not pass for you please run again.  PR #394 added some of the items including specs which I just merged.

If everything passed move to reviewer approved, please.
