### ISSUE TITLE
[Feature] Document where prereqs can be found and that they are automatically checked.

### ISSUE THREAD

**Issue by taylor** [cncf/cnf-conformance#387]
**Is your feature request related to a problem? Please describe.**
- Markdown documentation does not show all needed prereqs.    
- Kubectl is listed but no other ones so it looks like the only required tool.
- This issue was raised in [slack](https://cloud-native.slack.com/archives/CV69TQW7Q/p1598859701005700)

**Describe the solution you'd like**

Update INSTALL guide [PREREQ section](https://github.com/cncf/cnf-conformance/blob/master/INSTALL.md#prerequisites) to make it clear prereqs are automatically checked and only list what is required to run the binary -- which may be NO prerqs.

Possibly add a FAQ item (with a link from the install prereq section), with something like:
- Q: What are the prereqs?
- A: See https://github.com/cncf/cnf-conformance/blob/master/src/tasks/prereqs.cr for the most up to date list.   The prerequisites are checked automatically when the test suite is used and any missing dependencies will be shown on the CLI.

**Describe alternatives you've considered**
Add all prereqs to install guide.  This would lead to the docs being out of date with the code at times.

**Additional context**

**Comment by taylor** [comment]
See #374  for current updates

**Comment by lixuna** [comment]
### Level of effort in pts: 0,1,2,3,5,8,13,21 -

**Comment by lixuna** [comment]
### Acceptance Criteria:

### Documentation is updated:

- [ ]  Documentation for prereqs is added to https://github.com/cncf/cnf-conformance/blob/master/INSTALL.md

**Comment by agentpoyo** [comment]
These do not make sense to me in the AC, what exactly are we asking:

"I do not see any prerequisites listed which are automatically checked by the prereq checker
    kubectl is removed"

There is still no FAQ.md available. Perhaps I can start one?

**Comment by lixuna** [comment]
re: FAQ. @agentpoyo assistance welcomed on a new FAQ. Here is an issue to help you get started https://github.com/cncf/cnf-conformance/issues/390

**Comment by agentpoyo** [comment]
Once we merge FAQ.md into master, it will satisfy the rest of this AC that was checked off.

### FAQ.md has a Q/A for the prereq checker
- [x] I go to the [FAQ](https://github.com/cncf/cnf-conformance/blob/master/FAQ.md)
- [x] I see the Q/A for the prereq checker
- [x] I see a link to the source for the prereq checker
