### ISSUE TITLE
[BUG] wget not found when LANG environment variable is not set to C (English) and when busybox

### ISSUE THREAD

**Issue by collivier** [cncf/cnf-conformance#388]
**Describe the bug**

Following the tutorial in tree (both binary and source): https://github.com/cncf/cnf-conformance/blob/master/INSTALL.md. wget is undetected.

wget check (cnf-conformance setup) fails if
 - LANG=fr_FR.UTF-8 (wget could rather be called vs LANG=C)
 - wget is a link to busybox (Alpine)

```
$ ./cnf-conformance setup ; which wget
Global helm found. Version: v3.3.0
Local helm found. Version:
No Global wget version found
No Local wget version found
Setup failed. Some prerequisites are missing. Please install all of the prerequisites before continuing.
/usr/bin/wget
```

**To Reproduce**
1. Download cnf-conformance binary
2. Set LANG: `export LANG=fr_FR.UTF-8`
3. `./cnf-conformance setup`

**Expected behavior**
wget is found as a prereq

**Workstation (please complete the following information):**
 - OS Linux
 - Distro Debian
 - Architecture x86

**Comment by collivier** [comment]
I also noted a possible issue in 0.0.9 when cnf-conformance is in $PATH (rather than the current dir)
E, [2020-09-02 17:15:44 UTC #539] ERROR -- cnf-conformance: getaddrinfo: Try again
Unhandled exception: Error opening file 'cnf-conformance' with mode 'r': No such file or directory (Errno)
Failed to raise an exception: END_OF_STACK

**Comment by denverwilliams** [comment]
Closing in favour of https://github.com/cncf/cnf-conformance/issues/679
