### ISSUE TITLE
[Feature] Add an FAQ.md to address commonly asked questions

### ISSUE THREAD

**Issue by lixuna** [cncf/cnf-conformance#390]
### [Feature] Add an FAQ.md to address commonly asked questions

**Short description**
- Create a new file for FAQ
- Add common questions/concerns related to CNF Conformance

**Describe alternatives you've considered**
- Add items from [beta test instructions FAQ](https://hackmd.io/QjLxg3FAS16oUupRs8ki5A#FAQ)
- Add items that have been asked in slack or GitHub issues
- Add other items that have been asked to the team

**Comment by debugleader** [comment]
@lixuna I would like to do this, can you guide me through and give me more explanation?

**Comment by lixuna** [comment]
Good day, @debugleader

Thanks in advance for your help in improving the documentation for CNF Conformance. You're welcome to join our weekly community meetings on Thursdays at 14:15 UTC to meet the team and talk about the status of the CNF Conformance test suite. See [here](https://github.com/cncf/cnf-conformance/blob/master/CONTRIBUTING.md#community-meeting) for meeting details.

In this issue, we'd like to see a new file called `FAQ.md` for https://github.com/cncf/cnf-conformance. 

To get started, here is the link for our [Contributing guide](https://github.com/cncf/cnf-conformance/blob/master/CONTRIBUTING.md#contribution-flow).

Here is an article on [creating new files in a GitHub repo](https://docs.github.com/en/github/managing-files-in-a-repository/creating-new-files).

Here is an article on [Getting Started with Markdown](https://www.markdownguide.org/getting-started/).

The formatting of the FAQ.md can be whatever you like. Here are some examples of FAQs from CNCF projects for reference: 
- https://www.prometheus.io/docs/introduction/faq/
- https://linkerd.io/2/faq/

Content for the FAQ can be added incrementally, especially as we receive new questions and requests. 
- Here are a few [Q&A items](https://hackmd.io/QjLxg3FAS16oUupRs8ki5A?view#FAQ) that could be added to the initial FAQ.md 

If you have any questions about the CNF Conformance test suite that you think should be included in the FAQ, please let us know. We look forward to collaborating with you!

**Comment by lixuna** [comment]
@agentpoyo What's your estimate in points for the FAQ?

I think I'd go with 2 or 3 pts

**Comment by agentpoyo** [comment]
2 pts
