### ISSUE TITLE
Review using Cruise K-rails as a conformance tool

### ISSUE THREAD

**Issue by taylor** [cncf/cnf-conformance#4]
Possibly use K8s policy enforcement tool [k-rail](https://github.com/cruise-automation/k-rail) to validate that CNFs continue to carry traffic when appropriate policies are enforced

**Comment by wavell** [comment]
K-rails has a monitor mode that allows default 'violations' to be monitored and reported on.  K-rails has default violations/policies that need very little configuration.  The violations are stored in a log and can be scraped.  This can be useful for testing a cluster for containers that have privileged mode turned on, among other things.

**Comment by lixuna** [comment]
OPA Gatekeeper seems like a better fit for the CNF Conformance. OPA Gatekeeper is more standard within the K8s community. OPA is more rigorous and all inclusive than K-Rails and has a language on how to configure policies.
