### ISSUE TITLE
[BUG] LOG_LEVEL=debug not showing LOGGING.debug messages

### ISSUE THREAD

**Issue by wavell** [cncf/cnf-conformance#400]
**Describe the bug**
debug not showing LOGGING.debug messages for the crystal specs 

```
LOG_LEVEL=debug crystal spec spec/platform/observability_spec.cr -v  
```

**To Reproduce**
1. use LOGGING.debug to send log messages in the observability code
2. Run the specs e.g. `LOG_LEVEL=debug crystal spec spec/platform/observability_spec.cr -v `

**Expected behavior**
Debug logs should show

**Comment by williscool** [comment]
So after thinking it was some weird macro stuff ...

turns out I had it setup for `LOGLEVEL` and NOT `LOG_LEVEL` note the **underscore** 

pr fixes

**Comment by williscool** [comment]
tests pass  thanks to  https://github.com/cncf/cnf-conformance/commit/b0b68678de271c4daa398104e8b3174b7a1ea8f8
![image](https://user-images.githubusercontent.com/394931/97640857-06c45700-1a18-11eb-9318-5e561b61bd8b.png)
