### ISSUE TITLE
[BUG]  Ephemeral Dev environment not returning exit code

### ISSUE THREAD

**Issue by wavell** [cncf/cnf-conformance#404]
**Describe the bug**
Ephemeral Dev environment not returning exit code

**To Reproduce**
1. Run a build on travis with a spec that errors out
2. View the build logs
3. Note that the build has an error
4. Note that travis displays the build as passed

**Expected behavior**
When the build has an error, travis should not pass

**Screenshots**
https://travis-ci.org/github/cncf/cnf-conformance/builds/729120113
![image](https://user-images.githubusercontent.com/29548/93913754-235bc980-fccb-11ea-9c42-cd04b8c58624.png)

**Comment by williscool** [comment]
Looks good to me latest build that didn't error with (#414 being the issue with the latest biuild) passes with no failues.

https://api.travis-ci.org/v3/job/729711370/log.txt

also the previous build before that correctly fails with spec test failures

https://api.travis-ci.org/v3/job/729425213/log.txt

compared with build before the changes in pr #405 

https://travis-ci.org/github/cncf/cnf-conformance/builds/729120113

that fails spec test suite but shows passing in travis
