### ISSUE TITLE
[Bugfix] rename command to run all of the scalability tests from "scaling" to "scalability"

### ISSUE THREAD

**Issue by lixuna** [cncf/cnf-conformance#42]
### [Bugfix] rename command to run all of the scalability tests from "scaling" to "scalability"

**Scalability Tests**

What we see now on https://github.com/cncf/cnf-conformance/edit/master/USAGE.md, 
#### To run all of the scalability tests
```
crystal src/cnf-conformance.cr scaling
```

What I would like to see: 
#### To run all of the scalability tests
```
crystal src/cnf-conformance.cr scalability
```

**Comment by wavell** [comment]
### Acceptance Criteria for peer review:
---
###  Common steps
- [ ]  Find or create a K8s cluster to use
       - [ ] Steps for creating will be in another ticket 
       - [ ] Talk with team for access to an existing cluster
- [ ] Set the KUBECONFIG environment variable for accessing the target K8s cluster
- [ ]  Pull down latest version of CNF conformance test code from `develop` branch
- [ ]  Run shard install
- [ ]  Run the cleanup task
- [ ]  Run the setup task
###  Run the scalability task (on the sample coredns cnf):
```
crystal src/cnf-conformance.cr scalability
```
- [ ] You should see that the replicas increase and decrease (text in green)
```
PASSED: Replicas increased to 3
PASSED: Replicas decreased to 1
```
### Run the conformance automated tests:
```
crystal spec
```
- [ ] You should see all tests passing
```
Finished in 2:11 minutes
2 examples, 0 failures, 0 errors, 0 pending
```
###  check the USAGE documentation
- [ ] You should see that usage code says crystal src/cnf-conformance.cr scalability

**Comment by taylor** [comment]
@wavell @lixuna the USAGE document still says `scaling`
> crystal src/cnf-conformance.cr scaling

**Comment by taylor** [comment]
It looks like USAGE is fixed in https://github.com/cncf/cnf-conformance/pull/76

**Comment by taylor** [comment]
@wavell I'm bumping spec from the rename.  I'll check it out when I have spec testing running

**Comment by taylor** [comment]
### Run the conformance automated tests:
```
crystal spec
```
- [ ] You should see all tests passing
```
Finished in 2:11 minutes
2 examples, 0 failures, 0 errors, 0 pending
```

**Comment by lixuna** [comment]
USAGE.md has been updated after merging PR #76 


check the USAGE documentation

- [x]  You should see that usage code says crystal src/cnf-conformance.cr scalability

> Scalability Tests
> ✔️ To run all of the scalability tests
> crystal src/cnf-conformance.cr scalability
