### ISSUE TITLE
[BUG] Runner needs to clean up jobs, even when the build fails

### ISSUE THREAD

**Issue by wavell** [cncf/cnf-conformance#422]
**Describe the bug**

Packet runner needs to have its kind clusters clean up **even when the build fails**
Here is the error that it gives after too many kind clusters appear:
```
Error from server (NotFound): error when deleting "/cnf-conformance/spec/fixtures/chaos_network_loss.yml": networkchaos.pingcap.com "network-loss-test" not found
Error from server (NotFound): error when deleting "/cnf-conformance/spec/fixtures/chaos_cpu_hog.yml": stresschaos.pingcap.com "cpu-hog-test" not found
The job exceeded the maximum time limit for jobs, and has been terminated.
```

**To Reproduce**
1. Build on travis where the builds fail repeatedly

**Expected behavior**
No build errors

**Comment by williscool** [comment]
LGTM 

failure_func cleans jobs after a failed job

https://travis-ci.org/github/cncf/cnf-conformance/builds/733198313
