### ISSUE TITLE
[BUG] Binary should exit with an error code when tasks fail to run

### ISSUE THREAD

**Issue by williscool** [cncf/cnf-conformance#426]
**Describe the bug**

Follow steps to reproduce to see that when the binary fails to complete ...

- a single task run
- if the `cnf-conformance setup` task is not run
-  the binary exits with code 0

even though the error for the missing cnfs directory is shown by the logger

**To Reproduce**

using the dockerfile from branch feature/#398_test_binary_in_empty_folder as of 10-6-2020

https://raw.githubusercontent.com/cncf/cnf-conformance/101a2f46590af9c17d2d4564d430dbba184e2f8e/tools/curl_install_tester_docker_setup/Dockerfile

``` bash
# build bin
docker run --rm -it -v \$(pwd):/workspace -w /workspace crystallang/crystal:0.35.1-alpine shards install
docker run --rm -it -v \$(pwd):/workspace -w /workspace crystallang/crystal:0.35.1-alpine crystal build src/cnf-conformance.cr --release --static --link-flags '-lxml2 -llzma'
cp cnf-conformance tools/curl_install_tester_docker_setup/ 
docker build tools/curl_install_tester_docker_setup/ -t curl_install_tester --target ci_test
docker run --rm -it curl_install_tester ./cnf-conformance ip_addresses cnf-config=./cnf-conformance.yml
echo $?
0
```

take care to make sure you **DO NOT** run the `setup` task before running the `ip_addresses` task

Note that the exit code you get is 0 which is a non error code

**Expected behavior**

I expect to get an error exit code i.e. 1

**Comment by williscool** [comment]
lgtm

![image](https://user-images.githubusercontent.com/394931/99340778-abd39200-2856-11eb-90b3-9dd14116b11a.png)

**Comment by lixuna** [comment]
Thanks for noting and addressing this bug, @wavell @williscool @agentpoyo. 

Please add you level of effort in pts (0,1,2,3,5,8,13,21) to the comments :)

**Comment by williscool** [comment]
@lixuna 3pts

**Comment by agentpoyo** [comment]
@lixuna 3pts
