### ISSUE TITLE
[BUG] Invalid memory access address during build

### ISSUE THREAD

**Issue by wavell** [cncf/cnf-conformance#429]
**Describe the bug**
docker run --rm -it -v $PWD:/workspace -w /workspace crystallang/crystal:0.35.1-alpine crystal build src/cnf-conformance.cr --release --static --link-flags "-lxml2 -llzma"
Invalid memory access (signal 11) at address 0x7f332e561b28

**Will get this error about 3 times out of 10 builds**
```
# cmd line
docker run --rm -it -v $PWD:/workspace -w /workspace crystallang/crystal:0.35.1-alpine crystal build src/cnf-conformance.cr --release --static --link-flags "-lxml2 -llzma"
Invalid memory access (signal 11) at address 0x7f332e561b28
```

**Expected behavior**
Should not get an error

**Additional context**
See https://forum.crystal-lang.org/t/invalid-memory-access-in-crystal-compiler-pre-solved/2237/7
```
pfischer
Jun 17
LLVM 10.0.0 looks good (tested now). It’s the reason, why Crystal on 
alpine:edge is not segfaulting - there is also LLVM 10.0.0.
```

**Comment by wavell** [comment]
https://github.com/crystal-lang/crystal-infrastructure/blob/main/docker/alpine-aarch64-build/Dockerfile

**Comment by williscool** [comment]
lgtm haven't seen any of these failures since this change

https://github.com/cncf/cnf-conformance/actions

**Comment by lixuna** [comment]
@wavell @denverwilliams @williscool Please add your estimate in points (0,1,2,3,5,8,13,21) in the comments below

**Comment by williscool** [comment]
5
