### ISSUE TITLE
[Implementation] rename command to Run all hardware resources and scheduling tests 

### ISSUE THREAD

**Issue by lixuna** [cncf/cnf-conformance#44]
[Implementation] rename command to Run all hardware resources and scheduling tests 

What I see now in https://github.com/cncf/cnf-conformance/edit/master/USAGE.md:

#### :heavy_check_mark: Run all hardware resources and scheduling tests
```
crystal src/cnf-conformance.cr hardware_affinity
```

# What I would like to see: 
```
crystal src/cnf-conformance.cr hardware_and_scheduling

```

**Comment by lixuna** [comment]
What we currently call the hardware workload test category: `hardware_affinity`

What I would like to see instead: 
- I would expect the workload test category to be called `hardware_and_scheduling`
- This is based on #327, where the platform test category is called `platform:hardware_and_scheduling'

**Comment by lixuna** [comment]
Please add your estimate in points (0,1,2,3,5,8,13,21) in the comments below

**Comment by wavell** [comment]
2 points

**Comment by nupejosh** [comment]
I've confirmed that all references to hardware_affinity has now been changed to hardware_and_scheduling, but I may not be getting the expected behavior. 
```crystal src/cnf-conformance.cr hardware_affinity```
![Screen Shot 2020-11-10 at 9 41 48 AM](https://user-images.githubusercontent.com/3164983/98696067-f75add00-2338-11eb-8a14-b0a2e915d2b3.png)

I'm able to get the following response when I run
 ```crystal src/cnf-conformance.cr platform:hardware_and_scheduling```
![Screen Shot 2020-11-10 at 9 39 30 AM](https://user-images.githubusercontent.com/3164983/98695786-a4812580-2338-11eb-8ee6-73503935fc9d.png)

However, I'm not able to receive a proper response when I run 
```crystal src/cnf-conformance.cr hardware_and_scheduling```
![Screen Shot 2020-11-10 at 9 40 57 AM](https://user-images.githubusercontent.com/3164983/98695965-d7c3b480-2338-11eb-9aa0-eb441bc913d3.png)

Does AC require the `hardware_and_scheduling` command to work without the `platform` prefix?
@lixuna @taylor @wavell @denverwilliams

**Comment by lixuna** [comment]
@nupejosh this command is for workload tests, do you need to add the prefix workload?

**Comment by nupejosh** [comment]
@lixuna ok cool, I'll standby for AC.. I was going by the command in the initial "What I would like to see" section above. and the docs here https://github.com/cncf/cnf-conformance/blob/master/USAGE.md#hardware-resources-and-scheduling-tests

**Comment by lixuna** [comment]
### Acceptance Criteria for peer review (https://github.com/cncf/cnf-conformance/issues/402#issuecomment-708526547)
--
### Documentation is updated:
- [ ] https://github.com/cncf/cnf-conformance/blob/master/USAGE.md#hardware-resources-and-scheduling-tests


###  Common steps
- [ ] Find or create a K8s cluster to use
   - Talk with team for access to an existing cluster
   - [Kind K8s clusters](https://github.com/cncf/cnf-conformance/blob/master/KIND-INSTALL.md) will work as well
- [ ] Set the KUBECONFIG environment variable for accessing the target K8s cluster
- [ ]  As a developer, Pull down latest version of CNF conformance test code from {FEATURE} branch
     - [ ]  Check that {FEATURE} Branch passes all A/C 
     - [ ]  Check that {FEATURE} Branch passes tests in Travis CI
- [ ] As a peer reviewer, check that PR passes Travis CI tests
     - [ ]  if yes, merge PR to master
     - [ ]  if no, make a comment and request that developer make changes to pass tests 
- [ ]  As a peer reviewer, Pull down latest version of CNF conformance test code from `master` branch
- [ ]  Run `shards install`

### Spec test should pass
- [ ]  Run `crystal spec`
- [ ]   I expect to see PASSED for the tests

### Update Prerequisite checker
- [ ] N/A

### Update example CNFs cnf-conformance.yml, if needed
- [ ] N/A

### Update yml validator, if needed
- [ ] N/A

### I would expect the CoreDNS CNF to pass the ip address test when I run the category tests: (hardware_and_scheduling)
- [ ]  Follow common steps above, if you have not done so already
- [ ]  Run `./cnf-conformance setup`, if you have not done so already
- [ ]  Run `./cnf-conformance hardware_and_scheduling`
- [ ] I expect to see the output from the test
- [ ]  I expect to see PASSED for the test

### Screenshots of workload test category command output
- [ ]  I can see a screenshot of all command for A/C above
- [ ]  I can see a screenshot of `hardware_and_scheduling` category command for A/C above

**Comment by lixuna** [comment]
@nupejosh as far as I can see, we do not have any tests in this [test category](https://github.com/cncf/cnf-conformance/blob/master/USAGE.md#hardware-resources-and-scheduling-tests). I am not sure what it should look like when you run a test category name that does not include tests yet. @wavell what was your experience in running this renamed test category?

**Comment by wavell** [comment]
![image](https://user-images.githubusercontent.com/29548/98709253-c2a25200-2347-11eb-8549-8e2d6e622843.png)
There are no hardware and scheduling tests for workload yet.  Only for platform (the oci runtime test)
@lixuna @nupejosh

**Comment by williscool** [comment]
0 mentions of `hardware_affinity` as of today

![image](https://user-images.githubusercontent.com/394931/99497104-693bb380-2943-11eb-919a-d609bc2a86ea.png)


so lgtm
