### ISSUE TITLE
[Documentation] update USAGE.md

### ISSUE THREAD

**Issue by lixuna** [cncf/cnf-conformance#472]
Short description:

- ongoing improvements to usage documentation https://github.com/cncf/cnf-conformance/blob/master/USAGE.md 

Suggestions for improvement:

- [x] "Validating cnf", https://github.com/cncf/cnf-conformance/blob/master/USAGE.md#validating-a-cnf-conformanceyml-file should come after "building executable" https://github.com/cncf/cnf-conformance/blob/master/USAGE.md#building-the-executable

**Comment by williscool** [comment]
lgtm 

![image](https://user-images.githubusercontent.com/394931/99496389-2decb500-2942-11eb-9bc7-2090c20e32f1.png)
