### ISSUE TITLE
[BUG] Error: failed to download "stable/coredns" (hint: running `helm repo update` may help)

### ISSUE THREAD

**Issue by wavell** [cncf/cnf-conformance#474]
**Describe the bug**
  'helm_chart_valid' should fail on a bad helm chart
Error: failed to download "stable/coredns" (hint: running `helm repo update` may help)
Error: failed to fetch https://charts.helm.sh/stable/coredns-1.13.8.tgz : 404 Not Found

**To Reproduce**
1. helm repo update 
2. helm install coredns stable/coredns
3. See error

**Expected behavior**
I expect for coredns to be installable

**Screenshots**

![image](https://user-images.githubusercontent.com/29548/99299927-8cfedc80-2811-11eb-97b6-54d0d5163f52.png)
![image](https://user-images.githubusercontent.com/29548/99300178-df3ffd80-2811-11eb-8fcb-a576fa99503c.png)

**Workstation (please complete the following information):**
 - OS [e.g. Linux]
 - Distro [e.g. Ubuntu]
 - Version [e.g. 18.04]
 - Architecture [e.g. x86, arm]

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
https://github.com/helm/charts/blob/master/README.md#deprecation-timeline

**Comment by williscool** [comment]
didn;t see this today while workign on #82 

so looks good to me

**Comment by haoshuwei** [comment]
The same issue, see logs below:
```
[root@minikube-cluster03 ~]# helm repo list
NAME   	URL
stable 	https://charts.helm.sh/stable
bitnami	https://charts.bitnami.com/bitnami
[root@minikube-cluster03 ~]# helm upgrade -i my-coredns stable/coredns  --values values.yaml
Release "my-coredns" does not exist. Installing it now.
Error: failed to download "stable/coredns" (hint: running `helm repo update` may help)
```

**Comment by thewolfpack** [comment]
Addressed on master
