### ISSUE TITLE
[BUG] The build should not be triggered for documentation changes

### ISSUE THREAD

**Issue by wavell** [cncf/cnf-conformance#478]
**Describe the bug**
The build should not be triggered for documentation changes

**To Reproduce**
1. Make a change to a .md file
2. Push the change up
3. See the build occur

**Expected behavior**
The build should not be triggered for documentation changes

**Screenshots**

![image](https://user-images.githubusercontent.com/29548/99317179-3bfbe200-282b-11eb-9fcd-5ec2ae3030a9.png)

**Workstation (please complete the following information):**
 - OS [e.g. Linux]
 - Distro [e.g. Ubuntu]
 - Version [e.g. 18.04]
 - Architecture [e.g. x86, arm]

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by agentpoyo** [comment]
LGTM +1

See https://github.com/cncf/cnf-conformance/pull/496 which did not trigger a full spec build.
