### ISSUE TITLE
[Feature] Add support for testing multiple containers within a deployment

### ISSUE THREAD

**Issue by lixuna** [cncf/cnf-conformance#485]
[Acceptance Criteria](https://github.com/cncf/cnf-conformance/issues/485#issuecomment-729209204)

### [Feature] Add support for testing multiple containers within a deployment

**What we have now:** 
- Test a CNF with one container in a single deployment

**What we'd like to have:**
- Test a CNF w/ more than one container in a single deployment

**Out of scope for this issue:**
- Test a CNF with more than one deployment (this will be addressed in separate issue)

---

### Implementation Tasks: TBD

**Environment set up tasks:**
- [ ]  if needed

**Upstream tool set up tasks: (conformance suite + upstream tools)**
- [ ]  if needed

**Code implementation tasks:**
- [ ]  update pre-req checker - N/A

**Documentation tasks:**
- [ ] Update [Test Categories md](https://github.com/cncf/cnf-conformance/blob/master/TEST-CATEGORIES.md) if needed 
- [ ] Update [USAGE md](https://github.com/cncf/cnf-conformance/blob/master/USAGE.md) if needed 
- [ ] Update [installation instructions](https://github.com/cncf/cnf-conformance#installation)  if needed 

### QA tasks

Dev Review: 
- [ ] walk through A/C
- [ ] do you get the expected result?
- [ ] if yes, 
   - [ ] move to `Needs Peer Review` column  
   - [ ] create Pull Request and follow check list
   - [ ] Assign 1 or more people for peer review
- [ ] if no, document what additional tasks will be needed

Peer review:
- [ ] walk through A/C
- [ ] do you get the expected result?
- [ ] if yes, 
   - [ ] move to `Reviewer Approved` column
   - [ ] Approve pull request
- [ ] if no, 
   - [ ] document what did not go as expected, including error messages and screenshots (if possible)
   - [ ] Add comment to pull request
   - [ ] request changes to pull request

**Comment by lixuna** [comment]
Acceptance Criteria: building on A/C from #402 and #269 
---

### Acceptance Criteria for peer review:
--
### Documentation is updated:
- [ ]  USAGE lists new test name
- [ ]  Test Categories md is updated
- [ ]  Installation instructions is updated


###  Common steps
- [ ]  Find or create a K8s cluster to use
   - Talk with team for access to an existing cluster
   - [Kind K8s clusters](https://github.com/cncf/cnf-conformance/blob/master/KIND-INSTALL.md) will work as well
- [ ]  Set the KUBECONFIG environment variable for accessing the target K8s cluster
- [ ]  As a developer, Pull down latest version of CNF conformance test code from {FEATURE} branch
     - [ ]  Check that {FEATURE} Branch passes all A/C 
     - [ ]  Check that {FEATURE} Branch passes tests in GHA CI
- [ ] As a peer reviewer, check that PR passes GHA CI tests
     - [ ] if yes, merge PR to master
     - [ ]  if no, make a comment and request that developer make changes to pass tests 
- [ ]  As a peer reviewer, Pull down latest version of CNF conformance test code from `master` branch
- [ ]  Run `shards install`

### Spec test should pass
- [ ]  Run `crystal spec`
- [ ]   I expect to see PASSED for the tests


### Update Prerequistite checker
- N/A

### Update example CNFs cnf-conformance.yml, if needed
- [ ] continue, If there is an update to cnf-conformance.yml
- [ ] for each CNF Example
- [ ] Update the example CNF's cnf-conformance.yml to include the new changes
- [ ] Update the example CNF's README if needed
- [ ] Test the example CNF following it's README

### Update yml validator, if needed
- N/A

### When using the test `cnf-conformance no_local_volume` command the sample "good" CNF should PASS test successfully:
- [ ]  Follow common steps above, if you have not done so already
- [ ]  Run `./cnf-conformance setup`
- [ ]  Run  `./cnf-conformance sample_coredns_setup`
- [ ]  Run  `./cnf-conformance no_local_volume_configuration`
- [ ]  I expect to see the output and results from the test
- [ ]  I expect to see PASSED for the test. Example:
         - [ ] "✔️ PASSED: local storage configuration volumes not found [EMOJI]"

### When using the test `crystal spec --tag `no_local_volume`` command the sample "good" CNF should PASS and the "bad example CNF"  should FAIL test:
- [ ]  Run `crystal spec --tag no_local_volume_configuration`
- [ ]  I expect to see the output and results from the test
- [ ] I expect to see "✔️ PASSED: local storage configuration volumes not found [EMOJI]
- [ ]  I expect to see "❌ FAIL: local storage volumes found [EMOJI]"

### I would expect the CNF to pass when I run the entire test category suite (`statelessness`)
- [ ]  Follow common steps above
- [ ]   Run  `./cnf-conformance sample_coredns_setup`
- [ ]  Run  `./cnf-conformance statelessness`
- [ ]   I expect to see the output and results from all tests in the test category
- [ ]   I expect to see PASSED for the test and test category 

### I would expect the CNF to pass when I run the entire test suite (`workload`) for a downloaded cnf-conformance.yml config
- [ ]  Follow common steps above
- [ ]  Download the conformance configuration to test CoreDNS: `wget -O cnf-conformance.yml https://raw.githubusercontent.com/cncf/cnf-conformance/master/example-cnfs/coredns/cnf-conformance.yml`
- [ ]  Prepare the test suite to use the CNF by running: ./cnf-conformance cnf_setup cnf-config=./cnf-conformance.yml
- [ ]  Run  `./cnf-conformance workload`
- [ ]  I expect to see the output from the test
- [ ]  I expect to see PASSED for the test

### Screenshots of new test and results in the comments
- [ ]  New test should be added to the points file
- [ ]  New test score should be added to the final score
- [ ]  I can see a screenshot of the new test in the comments of this ticket

**Comment by lixuna** [comment]
Level of effort in points: 0,1,2,3,5,8,13,21:
---

@wavell 
@denverwilliams 
@williscool 
@agentpoyo 
@taylor 
@lixuna

**Comment by williscool** [comment]
@lixuna 13

**Comment by agentpoyo** [comment]
`crystal spec` no longer runs setup, so for now you must run `setup` so it downloads pre-reqs.

### Spec test should pass
- [x]  Run `crystal spec src/cnf-conformance.cr setup`
- [x]  Run `crystal spec`
- [x]   I expect to see PASSED for the tests

**Comment by agentpoyo** [comment]
There is no spec/workload to run `crystal spec spec/workload`

```
$ ls spec/
cnf_conformance_all              curl_install_spec.cr    microservice_spec.cr  resilience           setup_spec.cr          utils
configuration_lifecycle_spec.cr  fixtures                platform              scalability_spec.cr  spec_helper.cr
cpu_hog_spec.cr                  installability_spec.cr  prereqs_spec.cr       security_spec.cr     statelessness_spec.cr
```

**Comment by agentpoyo** [comment]
![container_workload_k8s-sidecar1](https://user-images.githubusercontent.com/14348948/100025119-c1dcd780-2dad-11eb-89a6-49ef808e3547.png)

**Comment by agentpoyo** [comment]
![work_error1](https://user-images.githubusercontent.com/14348948/100025790-1c2a6800-2daf-11eb-93d9-4a92084e117e.png)

**Comment by agentpoyo** [comment]
![specific_helm_error](https://user-images.githubusercontent.com/14348948/100027000-775d5a00-2db1-11eb-9030-75a5f9c9d3f4.png)

**Comment by lixuna** [comment]
@agentpoyo Can you please create a new Bug issue for the setup not working in spec? https://github.com/cncf/cnf-conformance/issues/485#issuecomment-732469962

**Comment by agentpoyo** [comment]
![workload1](https://user-images.githubusercontent.com/14348948/100288159-b0293a80-2f3b-11eb-891c-ce1f7e38db3e.png)

**Comment by agentpoyo** [comment]
![workload2](https://user-images.githubusercontent.com/14348948/100289891-95f15b80-2f3f-11eb-9302-a3de2f8889bb.png)

**Comment by agentpoyo** [comment]
Microservice was failing docker tag v1.9.9:

![microservice_nastiness](https://user-images.githubusercontent.com/14348948/100292548-6db92b00-2f46-11eb-8728-ce079bd18b9e.png)

When we changed from v1.9.9 to 1.16.0, it would run without failing:

![microservice_nastiness_fix](https://user-images.githubusercontent.com/14348948/100292600-90e3da80-2f46-11eb-87c1-337a52171ffd.png)

**Comment by agentpoyo** [comment]
### When using the test `crystal spec spec/workload` command the sample "good" CNF should PASS and the "bad example CNF"  should FAIL test:
- [x]  Run `crystal spec spec/workload`
- [x]  I expect to see the output and results from all workload tests in the spec/workload directory
- [x] I expect to see PASSED for all specs
  - Bad CNFs fail as expected
  - Good CNFs pass as expected

![485_workload_good1](https://user-images.githubusercontent.com/14348948/100524343-01743c80-317d-11eb-9247-dbe62e40300e.png)

**Comment by agentpoyo** [comment]
Run `./cnf-conformance workload`

![workload_error](https://user-images.githubusercontent.com/14348948/100524805-d390f700-3180-11eb-9f56-59412984d40b.png)

But overall still passes:

![485_workload_good2](https://user-images.githubusercontent.com/14348948/100524818-f3c0b600-3180-11eb-9a00-007ea1e9bcf6.png)

@wavell

**Comment by agentpoyo** [comment]
Did not see any errors after Tag 1.16.0 was used instead of v1.9.9 after the PR. @wavell
