### ISSUE TITLE
[BUG] Rolling update test should derive image from k8s api 

### ISSUE THREAD

**Issue by wavell** [cncf/cnf-conformance#489]
**Describe the bug**
Rolling update test should derive image from k8s api 
E, [2020-11-18 17:45:31 -05:00 #4660] ERROR -- cnf-conformance: Missing hash key: "image"  

**To Reproduce**
1. Install a cnf that has no values file (and hence no images derived from its helm chart values file)
2. LOG_LEVEL=debug ./cnf-conformance rolling_update verbose 
3. See error

**Expected behavior**
I expect to see no errors and have the image names derived from the k8s api

**Screenshots**
![image](https://user-images.githubusercontent.com/29548/99598299-f1ab6a00-29be-11eb-9e9c-bdfa45af9c55.png)

**Workstation (please complete the following information):**
 - OS [e.g. Linux]
 - Distro [e.g. Ubuntu]
 - Version [e.g. 18.04]
 - Architecture [e.g. x86, arm]

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by lixuna** [comment]
FYI - This update has been included in v1.10.0. If any issues are found during peer review, please open a new bug ticket.

**Comment by williscool** [comment]
looks good to me

![image](https://user-images.githubusercontent.com/394931/105329119-9ed67480-5bf2-11eb-8013-24f46fae01cd.png)
