### ISSUE TITLE
[BUG] helm chart in coredns example not working in latest release

### ISSUE THREAD

**Issue by taylor** [cncf/cnf-conformance#491]
**Describe the bug**

@collivier

> I got 404 vs https://cncf.gitlab.io/ and I'm not able to run your latest release.

https://github.com/cncf/cnf-conformance/blob/master/example-cnfs/coredns/cnf-conformance.yml#L14
example-cnfs/coredns/cnf-conformance.yml:14
  ```
repo_url: https://cncf.gitlab.io/stable
<https://github.com/cncf/cnf-conformance|cncf/cnf-conformance>cncf/cnf-conformance
```

All Functest releases are failing due to this helm repo changes. https://build.opnfv.org/ci/view/functest-kubernetes/

**To Reproduce**

**Expected behavior**

**Screenshots**

**Workstation (please complete the following information):**
 - OS [e.g. Linux]
 - Distro [e.g. Ubuntu]
 - Version [e.g. 18.04]
 - Architecture [e.g. x86, arm]

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by agentpoyo** [comment]
The repo at https://cncf.gitlab.io/stable is working, it will not load in a browser though, only via helm:

```
$ ./helm repo add stable https://cncf.gitlab.io/stable
"stable" has been added to your repositories
```
```
$ ./helm search repo stable
NAME                           	CHART VERSION	APP VERSION	DESCRIPTION                                       
stable/backend                 	0.0.1        	           	Chart for the CNCF CI Backend                     
stable/coredns                 	1.13.8       	1.7.1      	CoreDNS is a DNS server that chains plugins and...
stable/envoy                   	1.9.4        	1.11.2     	Envoy is an open source edge and service proxy,...
stable/exciproxy               	0.0.1        	           	Chart for the CNCF CI Backend                     
stable/fluentd                 	2.5.3        	v2.4.0     	A Fluentd Elasticsearch Helm chart for Kubernetes.
stable/frontend                	0.0.1        	           	Chart for the CNCF CI Frontend                    
stable/gitlab-omnibus          	0.1.36       	           	GitLab Omnibus all-in-one bundle                  
stable/kube-state-metrics      	2.9.4        	1.9.7      	Install kube-state-metrics to generate and expo...
stable/prometheus              	11.12.1      	2.20.1     	Prometheus is a monitoring system and time seri...
stable/prometheus-adapter      	2.5.1        	v0.7.0     	A Helm chart for k8s prometheus adapter           
stable/prometheus-node-exporter	1.11.2       	1.0.1      	A Helm chart for prometheus node-exporter
```

**Comment by collivier** [comment]
uhm I may be wrong when using the latest cnf-conformance.yml vs v0.9.4 this morning.
(the 2 latest repo changes didn't work).

**Comment by agentpoyo** [comment]
@collivier 

From your link, it looks like the last attempted run was on November 18th, is that right or am I reading that right? If so, can you try running another build? We caught this error late on the 18th and it should be fixed.

Thanks.

**Comment by collivier** [comment]
@agentpoyo Yes I'm testing vs cnf-conformance master rather than v0.9.4 (whatever the repos in cnf-conformance.yml). Functest leverages an old alpha release v0.7.2-beta1.

**Comment by agentpoyo** [comment]
@collivier 

What happens if you run `helm repo update`?

Thanks.

**Comment by collivier** [comment]
@agentpoyo when? as far as I understand cnf-conformance doesn't create the repo listed in cnf-conformance.yml
There is no repo in functest-kubernetes-cnf by default.

bash-5.0# helm repo update
Error: no repositories found. You must add one before updating

Adding the repo in Dockerfile bypasses the issue (I'm adapting the Functest test case to fit the last changes).

**Comment by collivier** [comment]
Please see https://gerrit.opnfv.org/gerrit/c/functest-kubernetes/+/71441 updating cnf-conformance to v0.9.4 in Functest.
https://gerrit.opnfv.org/gerrit/gitweb?p=functest-kubernetes.git;f=docker/cnf/Dockerfile;hb=refs/changes/41/71441/2#l27

I will merge it on Monday as OpenStack gerrit is in maintenance (our python upper-constraints are synced with OpenStack)

**Comment by agentpoyo** [comment]
@collivier 

Following your links to the functests, seems like most are now passing and it's not getting the helm errors as seen previously.

Was there anything else needed or other concerns with the builds with cnf-conformance?

Thanks.
