### ISSUE TITLE
[Feature] Add support for testing multiple deployments found in a helm chart or K8s manifest

### ISSUE THREAD

**Issue by lixuna** [cncf/cnf-conformance#494]
[Acceptance Criteria](https://github.com/cncf/cnf-conformance/issues/494#issuecomment-732427632)

### [Feature] Add support for testing multiple deployments found in a helm chart or K8s manifest

**What we have now:** 
- Test a CNF with one deployment in a single helm chart or K8s manifest

**What we'd like to have:**
- Test a CNF w/ more than one deployment in a single helm chart or K8s manifest

Features/enhancements:
- Only support deployments thru helm chart or K8s manifest
  - Helm chart for K8s workload to test
  - Directory or chart name
  - K8s Manifest directory to test
  - K8s manifest or helm chart are required for testing
- Simplify conformance.yml
   - Automatically determine deployment name from manifest or helm chart
   - Remove configuration items which are now determined dynamically
   - Remove configuration items which are not used anywhere anymore
- Synchronous deployments, test one deployment at a time
   - If a test fails on any deployment, the CNF fails that test
- Test results
   - Each test console message shows the deployment and container being tested
   - Results file - No change

**Terms and Definitions**
- K8s workload resource is defined by K8s = eg. a single deployment
- K8s workload is 1 or more workload resources 
- CNF = K8s workload + any dependencies such as Operators, CNI, NSM
   - Can contain multiple workload resources

**Out of scope for this issue:**
- Provide insight on which container failed as an enhancement of [[Feature] Add support for testing multiple containers - within a deployment](#485) 
- Add tracking of deployment failures as enhancement of this issue
- Aggregate top level CNF, apply points based on individual deployment

---

### Implementation Tasks: TBD

**Environment set up tasks:**
- [ ]  if needed

**Upstream tool set up tasks: (conformance suite + upstream tools)**
- [ ]  if needed

**Code implementation tasks:**
- [ ]  update pre-req checker - N/A

**Documentation tasks:**
- [ ] Update [Test Categories md](https://github.com/cncf/cnf-conformance/blob/master/TEST-CATEGORIES.md) if needed 
- [ ] Update [USAGE md](https://github.com/cncf/cnf-conformance/blob/master/USAGE.md) if needed 
- [ ] Update [installation instructions](https://github.com/cncf/cnf-conformance#installation)  if needed 

### QA tasks

Dev Review: 
- [ ] walk through A/C
- [ ] do you get the expected result?
- [ ] if yes, 
   - [ ] move to `Needs Peer Review` column  
   - [ ] create Pull Request and follow check list
   - [ ] Assign 1 or more people for peer review
- [ ] if no, document what additional tasks will be needed

Peer review:
- [ ] walk through A/C
- [ ] do you get the expected result?
- [ ] if yes, 
   - [ ] move to `Reviewer Approved` column
   - [ ] Approve pull request
- [ ] if no, 
   - [ ] document what did not go as expected, including error messages and screenshots (if possible)
   - [ ] Add comment to pull request
   - [ ] request changes to pull request

**Comment by lixuna** [comment]
DRAFT - Acceptance Criteria: Copy of A/C from #485 - needs updated:
---

### Acceptance Criteria for peer review:
--
### Documentation is updated:
- [ ]  USAGE updated as needed
- [ ]  Test Categories md is updated
- [ ]  Installation instructions is updated

Note: CNF configuration may or may not change in this ticket. Update docs accordingly.


###  Common steps
- [ ]  Find or create a K8s cluster to use
   - Talk with team for access to an existing cluster
   - [Kind K8s clusters](https://github.com/cncf/cnf-conformance/blob/master/KIND-INSTALL.md) will work as well
- [ ]  Set the KUBECONFIG environment variable for accessing the target K8s cluster
- [ ]  As a developer, Pull down latest version of CNF conformance test code from {FEATURE} branch
     - [ ]  Check that {FEATURE} Branch passes all A/C 
     - [ ]  Check that {FEATURE} Branch passes tests in GHA CI
- [ ] As a peer reviewer, check that PR passes GHA CI tests
     - [ ] if yes, merge PR to master
     - [ ]  if no, make a comment and request that developer make changes to pass tests 
- [ ]  As a peer reviewer, Pull down latest version of CNF conformance test code from `master` branch
- [ ]  Run `shards install`

### Spec test should pass
- [ ]  Run `crystal spec`
- [ ]   I expect to see PASSED for the tests


### Update Prerequistite checker
- N/A

### Update example CNFs cnf-conformance.yml, if needed
- [ ] continue, If there is an update to cnf-conformance.yml
- [ ] for each CNF Example
- [ ] Update the example CNF's cnf-conformance.yml to include the new changes
- [ ] Update the example CNF's README if needed
- [ ] Test the example CNF following it's README

Note: CNF configuration may or may not change in this ticket. Update example CNFs and cnf-conformance.yml example files accordingly. 


### Update yml validator, if needed
- [ ] Update yaml to support any changes in CNF configuration
- [ ] N/A


### When using the test `crystal spec spec/workload` command the sample "good" CNF should PASS and the "bad example CNF"  should FAIL test:
- [ ]  Run `crystal spec spec/workload`
- [ ]  I expect to see the output and results from all workload tests in the spec/workload directory
- [ ] I expect to see PASSED for all specs
  - Bad CNFs fail as expected
  - Good CNFs pass as expected

### I would expect the CNF to pass when I run the entire test suite (`workload`) for a "good" CNF which has multiple containers in a single Deployment
- [ ]  Follow common steps above
- [ ]  Prepare the test suite to use the CNF by running: `./cnf-conformance cnf_setup cnf-config=./sample_multi_container_deployment`
- [ ]  Run  `./cnf-conformance workload`
- [ ]  I expect to see the output from the test
- [ ]  I expect to see PASSED for the test


### I would expect a "bad" CNF to fail when I run the entire test suite (`workload`) for a "bad" CNF which has multiple containers in a single Deployment
- [ ]  Follow common steps above
- [ ]  Prepare the test suite to use the CNF by running: `./cnf-conformance cnf_setup cnf-config=./sample_multi_container_deployment_bad_cnf`
- [ ]  Run  `./cnf-conformance workload`
- [ ]  I expect to see the output from the test
- [ ]  I expect to see FAILED for the test


### Screenshots of spec and tests runs with results in the comments
- [ ]  I can see a screenshot of the spec run in the comments of this ticket
- [ ]  I can see a screenshot of the test run in the comments of this ticket
- [ ] I can see the test results in the comments of this ticket

**Comment by lixuna** [comment]
Level of effort in points: 0,1,2,3,5,8,13,21: 
---

@wavell 
@denverwilliams 
@williscool 
@agentpoyo 
@taylor 
@lixuna

**Comment by agentpoyo** [comment]
`crystal spec` is broke as it no longer runs setup. You may need to run setup prior to running `spec`

### Spec test should pass
- [ ]  Run `crystal spec src/cnf-conformance.cr setup`
- [ ]  Run `crystal spec`
- [ ]   I expect to see PASSED for the tests

**Comment by agentpoyo** [comment]
There is no spec/workload directory.
```
crystal spec spec/workload
```

There is no `./sample-cnfs/k8s-multiple-deployments/cnf-conformance.yml` file to run cnf-config= against.

@wavell @denverwilliams

**Comment by agentpoyo** [comment]
```
pair@cnfdev03:~/workspace/drew/cnf-conformance$ LOG_LEVEL=error ./cnf-conformance cnf_setup cnf-config=./sample-cnfs/sample-bad_helm_coredns-cnf/cnf-conformance.yml deploy_with_chart=false
Successfully created directories for cnf-conformance
Error: parse error at (coredns/templates/deployment.yaml:16): function "sdfskfsdf" not defined
No resources found.
Error from server (NotFound): deployments.apps "bad-helm-coredns-coredns" not found
Error from server (NotFound): deployments.apps "bad-helm-coredns-coredns" not found
No resources found.
Error from server (NotFound): deployments.apps "bad-helm-coredns-coredns" not found
```

**Comment by agentpoyo** [comment]
![workload_494](https://user-images.githubusercontent.com/14348948/102418145-c66a6980-3fc2-11eb-9551-edc06467fb2b.png)

**Comment by agentpoyo** [comment]
![workload_494_2](https://user-images.githubusercontent.com/14348948/102418151-c9655a00-3fc2-11eb-9a88-9262fe364102.png)

**Comment by agentpoyo** [comment]
The bad CNF fails at cnf_setup:

```
pair@cnfdev03:~/workspace/drew/cnf-conformance$ LOG_LEVEL=error ./cnf-conformance cnf_setup cnf-config=./sample-cnfs/sample-bad_helm_coredns-cnf/cnf-conformance.yml deploy_with_chart=false
Successfully created directories for cnf-conformance
Error: parse error at (coredns/templates/deployment.yaml:16): function "sdfskfsdf" not defined
No resources found.
Error from server (NotFound): deployments.apps "bad-helm-coredns-coredns" not found
Error from server (NotFound): deployments.apps "bad-helm-coredns-coredns" not found
No resources found.
Error from server (NotFound): deployments.apps "bad-helm-coredns-coredns" not found
Error from server (NotFound): deployments.apps "bad-helm-coredns-coredns" not found
No resources found.
Error from server (NotFound): deployments.apps "bad-helm-coredns-coredns" not found
Error from server (NotFound): deployments.apps "bad-helm-coredns-coredns" not found
```

**Comment by agentpoyo** [comment]
The above was expected behavior.

LGTM, this is complete.
