### ISSUE TITLE
Upstream tools and projects which can be used for testing CNF Conformance

### ISSUE THREAD

**Issue by taylor** [cncf/cnf-conformance#5]
What are open source tools and projects which can be used in testing CNF Compliance.

Some examples could be of tools and areas to test

- APIsnoop: Use Kubernetes audit logs to track every K8s API call used by a CNF and therefore specify what version of K8s is required and any beta or alpha API usage
- Helm v3 chart testing (ct): linting and testing
- Helm v3 installation: Functional test on CNF Testbed
- Validate Prometheus metrics using promtool
- Validate OpenTelemetry metrics
- Validate Fluentd-compatible logging

**Comment by taylor** [comment]
OPA Gatekeeper and/or k-rails could enforce policies to test items.

See tickets
- OPA Gatekeeper #3 
- K-rails #4

**Comment by lixuna** [comment]
upstream tests have been added to slides, test categories, and usage markdowns.
