### ISSUE TITLE
[Enhancement] Show only the issues addressed since the last development snapshots (master-GITCOMMIT) for new dev snapshots

### ISSUE THREAD

**Issue by taylor** [cncf/cnf-conformance#527]
**Is your feature request related to a problem? Please describe.**
There is too much noise and duplicate/redundant information on the https://github.com/cncf/cnf-conformance/releases specifically with the dev snapshots as a result of every snapshot having all issues listed since the last non-dev snapshot for every new snapshot.

The redundant information makes it so the releases page contains less releases per page requiring to go back further and further.

It also makes it more difficult for those who want to pick a specific dev snapshot or for whatever reason want to understand what occurred since the last dev snapshot.

**Describe the solution you'd like**
Update the new dev snapshots to only include the issues addressed *since the last dev snapshot*.

<img width="1126" alt="Screen Shot 2020-12-11 at 9 51 10 AM" src="https://user-images.githubusercontent.com/26697/101924791-b43d9500-3b96-11eb-984d-50a0814e42c5.png">

**Describe alternatives you've considered**
Have no issues addressed listed for dev snapshots

**Additional context**

Example:

master-408bd64 December 11, 2020

### UPDATES
- Issues addressed in this release:
- issue: #522 Title: release manager now uses first entry in rev-parse
- issue: #524 Title: hopefully fix array order test break
- issue: #82 Title: Installable test: Can the CNF perform a rolling downgrade of the CNF version?
- ... (30+ issues listed)

and 

master-ff50711 December 10, 2020

### UPDATES
- Issues addressed in this release:

- issue: #524 Title: hopefully fix array order test break
- issue: #82 Title: Installable test: Can the CNF perform a rolling downgrade of the CNF version?
- ... (the same 30+ issues listed)

![image](https://user-images.githubusercontent.com/26697/101923648-4ba1e880-3b95-11eb-948b-8a1d64d36917.png)

![image](https://user-images.githubusercontent.com/26697/101923744-68d6b700-3b95-11eb-8d1d-79e4a44b08df.png)

**Comment by lixuna** [comment]
Note: the current information seems to show every pull request.

**Comment by taylor** [comment]
This dev snapshot has duplicate old updates: 
![image](https://user-images.githubusercontent.com/26697/102239861-e7489700-3ebc-11eb-877a-31bd511470db.png)

After removing the updates we can see the last dev snapshot

![image](https://user-images.githubusercontent.com/26697/102240160-2aa30580-3ebd-11eb-91e1-bf0a65d3cc96.png)

**Comment by taylor** [comment]
Note: I've retroactively updated a large number of the dev snapshots to only show the differences.  They are still there if you go further back in the history. See https://github.com/cncf/cnf-conformance/releases?after=master-6fd2ce3

**Comment by lixuna** [comment]
FYI - This enhancement has been included in v1.10.0. If any issues are found during peer review, please open a new bug ticket.

**Comment by agentpoyo** [comment]
![528_master_release_format](https://user-images.githubusercontent.com/14348948/105224606-fc02f500-5b22-11eb-83c5-13ea16bb5c51.png)

releases only display updates included in the release since the last release.
