### ISSUE TITLE
[Enhancement] Use markdown bullets and remove unnecessary pre text from dev snapshot UPDATEs section to

### ISSUE THREAD

**Issue by taylor** [cncf/cnf-conformance#528]
**Is your feature request related to a problem? Please describe.**
The section `Issues addressed in this release:` has the unneeded text:
- "issue:" at the start of the line
- "Title:" after the issue numbers

It would also be nice to have some type of indention for the issues addressed instead of a large block of text

**Describe the solution you'd like**

- Add a markdown bullet for issues addressed items.  Eg. `-`
- Remove the pre-text "issue:" at the start of each line
- Remove the pre-text "Title:" after the issue number

**Describe alternatives you've considered**
na

**Additional context**

See https://github.com/cncf/cnf-conformance/blob/bcb8929a287889315e683b38a9ffbe94ed9d16e4/src/tasks/utils/release_manager.cr#L73-L75

---

*Current output and suggested change*

<img width="898" alt="Screen Shot 2020-12-11 at 10 16 27 AM" src="https://user-images.githubusercontent.com/26697/101927571-44310e00-3b9a-11eb-8866-0ddb7e1c654c.png">

**Comment by sakshamgurbhele** [comment]
Can I work on this sir?

**Comment by taylor** [comment]
@sakshamgurbhele sure.  See https://github.com/cncf/cnf-conformance/blob/bcb8929a287889315e683b38a9ffbe94ed9d16e4/src/tasks/utils/release_manager.cr#L73-L75

Something like...
```
   acc + "  - #{x} - #{ReleaseManager.issue_title(x)}\n" 
```

**Comment by lixuna** [comment]
FYI - This update has been included in v1.10.0. If any issues are found during peer review, please open a new bug ticket.

**Comment by agentpoyo** [comment]
![528_master_release_format](https://user-images.githubusercontent.com/14348948/105224291-9c0c4e80-5b22-11eb-9bb1-55c3bf5ca598.png)

LGTM :+1:
