### ISSUE TITLE
[Feature] Add the date or a date+time to the dev snapshots tag for auto sorting on GitHub release page

### ISSUE THREAD

**Issue by taylor** [cncf/cnf-conformance#530]
**Is your feature request related to a problem? Please describe.**
[GitHub release page](https://github.com/cncf/cnf-conformance/releases) sorts based on the tag name and when using commits for the only difference from other snapshots (which all have the prefix `master`) ordering ends up being incorrect.

Updating title of release does not help unfortunately as the ordering is based on the tags.

**Describe the solution you'd like**
Add date or date + time.  Date will usually be enough unless there are multiple snapshots in the same day which also happen to have commits which cause ordering to be off.  Date + time should work any time.

Date + commit:
- `master-20201211-408bd64`

Date + time + commit (with and without timezone)
- `master-20201211-2056UTC-408bd64`
- `master-20201211-2056-408bd64`
- `master-202012112056-408bd64`

**Describe alternatives you've considered**
Date + time + commit with no branch (eg. `master`
- 202012102056UTC-408bd64

date + commit w/o branch
- `20201210-408bd64`

Date + build number:
- `master-202001210-310-408bd64`

**Additional context**

<img width="1021" alt="Screen Shot 2020-12-13 at 9 08 20 PM" src="https://user-images.githubusercontent.com/26697/102036244-ee21bd80-3d87-11eb-8302-1c774982f863.png">

**Comment by taylor** [comment]
It appears that draft releases are auto-sorted with the newest draft release at the top. 

![image](https://user-images.githubusercontent.com/26697/105411074-82d5d180-5bf8-11eb-9bbe-3cbbefb43691.png)

**Comment by lixuna** [comment]
Level of effort in pts needed: 0,1,2,3,5,8,13,21:

**Comment by taylor** [comment]
@lixuna my effort estimate is 3

@denverwilliams said 3 as well

**Comment by taylor** [comment]
When the first test release, abc1 (tag v0.9.17) published it did not show at all on the first page of releases

![image](https://user-images.githubusercontent.com/26697/105411579-2e7f2180-5bf9-11eb-8243-99b40d2e2099.png)

**Comment by taylor** [comment]
Publishing the last test release "abc20 test release with existing tag v0.9.15"  it goes to the 3rd page after v0.9.17 https://github.com/cncf/cnf-conformance/releases?after=v0.9.17

![image](https://user-images.githubusercontent.com/26697/105412017-c5e47480-5bf9-11eb-8435-34d87ff41361.png)


![image](https://user-images.githubusercontent.com/26697/105412171-f7f5d680-5bf9-11eb-848b-44adf5116849.png)

**Comment by taylor** [comment]
Creating a new release name "master-20210121-2106UTC-d3adb33f January 21, 2021 using v0.9.16 for #530" and selecting the prexisting tag v0.9.16 (which uses commit 5b61559) sorted in draft mode as expected (to the top), but went to page https://github.com/cncf/cnf-conformance/releases?after=v0.9.17 between v0.9.17 and v0.9.15. 

![image](https://user-images.githubusercontent.com/26697/105412777-c9c4c680-5bfa-11eb-9267-772f10bf0a85.png)

**Comment by taylor** [comment]
Unfortunately I just realized that those test releases overwrote the release notes for the existing ones w/o warning from github in the browser!

cc: @lixuna @wavell

**Comment by taylor** [comment]
sorting by tag works as expected
- master-20210121-2017UTC-d3adb33f27
- master-20210121-2017UTC-d3adb33f27


![image](https://user-images.githubusercontent.com/26697/105413884-5c199a00-5bfc-11eb-8288-737a83743f98.png)

**Comment by taylor** [comment]
@lixuna watson said 3pts for estimate

**Comment by taylor** [comment]
@lixuna all of the old releases content seems to have returned after deleting our pre-releases
- v0.9.15
- v0.9.16
- v0.9.17

**Comment by lixuna** [comment]
@taylor is this issue ready for peer review?

**Comment by agentpoyo** [comment]
![530_release_tags_format](https://user-images.githubusercontent.com/14348948/106506828-db765b80-648f-11eb-8cfe-e4ea241ad420.png)

@taylor latest release tags format ^^ if looks good, peer review is completed.

**Comment by taylor** [comment]
![image](https://user-images.githubusercontent.com/26697/107401968-0df40a00-6ac9-11eb-9e87-9fb1999692f4.png)


lgtm
