### ISSUE TITLE
[Feature]  Add support for additional K8s workload resource kinds: Pod, ReplicaSet, StatefulSet, Daemonset

### ISSUE THREAD

**Issue by lixuna** [cncf/cnf-conformance#531]
[Acceptance Criteria](https://github.com/cncf/cnf-conformance/issues/531#issuecomment-745458752)

### [Feature] Add support for additional K8s workload resource kinds: Pod, ReplicaSet, StatefulSet, Daemonset

**What we have now:** 
- Test a CNF that uses K8s workload kind: Deployment

**What we'd like to have:**
- Test a CNF that uses one of several K8s workload kinds: Deployment, Pod, ReplicaSet, StatefulSet, Daemonset
- Reference: https://kubernetes.io/docs/concepts/workloads/
- Update code to not expect Deployment as the only workload resource type
- Need at least one sample for each new K8s workload resource type

**Out of scope for this issue:**
- Test a CNF that uses K8s workload resource kind Job or CronJob (to be addressed in a separate issue as needed)

---

### Implementation Tasks: TBD

**Environment set up tasks:**
- [ ]  if needed

**Upstream tool set up tasks: (conformance suite + upstream tools)**
- [ ]  if needed

**Code implementation tasks:**
- [ ]  update pre-req checker - N/A

**Documentation tasks:**
- [ ] Update [Test Categories md](https://github.com/cncf/cnf-conformance/blob/master/TEST-CATEGORIES.md) if needed 
- [ ] Update [USAGE md](https://github.com/cncf/cnf-conformance/blob/master/USAGE.md) if needed 
- [ ] Update [installation instructions](https://github.com/cncf/cnf-conformance#installation)  if needed 

### QA tasks

Dev Review: 
- [ ] walk through A/C
- [ ] do you get the expected result?
- [ ] if yes, 
   - [ ] move to `Needs Peer Review` column  
   - [ ] create Pull Request and follow check list
   - [ ] Assign 1 or more people for peer review
- [ ] if no, document what additional tasks will be needed

Peer review:
- [ ] walk through A/C
- [ ] do you get the expected result?
- [ ] if yes, 
   - [ ] move to `Reviewer Approved` column
   - [ ] Approve pull request
- [ ] if no, 
   - [ ] document what did not go as expected, including error messages and screenshots (if possible)
   - [ ] Add comment to pull request
   - [ ] request changes to pull request

**Comment by lixuna** [comment]
DRAFT - Acceptance Criteria: 
---

**Comment by lixuna** [comment]
DRAFT - Level of effort in points: 0,1,2,3,5,8,13,21:
---

**Comment by taylor** [comment]
Brainstorming items

- Update code to not expect Deployment as the only workload resource type
- Need at least one sample for each new K8s workload resource type
   - Create a single sample for each Workload Resource type and run the entire test against each of them
      - Can run this in sync or async
   - Create an sample CNF (or helm chart) that uses all the Workload Resource types
   - Duplicate every existing sample for every Workload Resource type
      - Probably not needed for every test and every sample
- Create an example CNF (or helm chart) with all Workload Resource types
- Only support resource types listed by K8s
   - Not needed if we test that a CNF works on certified K8s vs a vendor specific platform

**Comment by agentpoyo** [comment]
![531_spec_results](https://user-images.githubusercontent.com/14348948/103232992-8af46700-4901-11eb-8ff4-40660653c9fd.jpg)

**Comment by agentpoyo** [comment]
![531_spec_workload_results](https://user-images.githubusercontent.com/14348948/103234602-b37e6000-4905-11eb-8ac4-0ef0da135092.jpg)

**Comment by agentpoyo** [comment]
![531_workload_results_2](https://user-images.githubusercontent.com/14348948/103236262-09550700-490a-11eb-9a21-fd52eb026906.jpg)

**Comment by agentpoyo** [comment]
LGTM, opened a bug for the helm repo issue; workaround is to add manually.

https://github.com/cncf/cnf-conformance/issues/546
