### ISSUE TITLE
[Documentation] Updates to CNF_CONFORMANCE_YML_USAGE.md document.

### ISSUE THREAD

**Issue by agentpoyo** [cncf/cnf-conformance#537]
** Update the CNF_CONFORMANCE_YML_USAGE.md document **

Need to update the document with most up to date relevant information on building your own CNF to test with cnf-conformance suite.

- Overview of format
- Examples and building cnf-conformance.yml file

**Comment by lixuna** [comment]
@agentpoyo what would your estimate be for these updates (using the scale: 0,1,2,3,5,8,13,21 pts)?

**Comment by agentpoyo** [comment]
1 point
