### ISSUE TITLE
[Feature] Support multiple services

### ISSUE THREAD

**Issue by wavell** [cncf/cnf-conformance#545]
### [Acceptance Criteria](https://github.com/cncf/cnf-conformance/issues/545#issuecomment-788352793)

**Is your feature request related to a problem? Please describe.**

The service name for a CNF is currently statically defined (only one may be defined) in the cnf-conformance.yml

**Describe the solution you'd like**
Remove service_name from the cnf-conformance.yml
Loop through cnf's potential services that are installed dynamically by accessing the generated helm template or manifest files.

**Additional context**

The config key `service_name` is a 1 to 1 mapping for the [K8s Service](https://kubernetes.io/docs/concepts/services-networking/service/) [defined in K8s manifest](https://kubernetes.io/docs/concepts/services-networking/service/#defining-a-service)

 K8s Services are attached to [K8s Workload Resources](https://kubernetes.io/docs/concepts/workloads/). (See `app` name in selector section for defining a service for association)

See
- [configuration_lifecycle.cr test "nodeport_not_used"](https://github.com/cncf/cnf-conformance/blob/cb93dd6e02c64cab7aa8854c2d1ece8ea8567779/src/tasks/workload/configuration_lifecycle.cr#L276) 
- [configuration_lifecycle.cr task "retrieve_manifest"](https://github.com/cncf/cnf-conformance/blob/6ba442e2313fe6dc3830b3bc143ad056f628e234/src/tasks/workload/configuration_lifecycle.cr#L114)

---

### Scenario 1 - CNF with multiple services will not check for nodeport being used for all services

1. Configure cnf-conformance.yml for a CNF with multiple K8s services
2. Deploy the CNF
3. Run test nodeport_not_used

Expected:
- All services would be tested for CNF to see if [NodePort](https://kubernetes.io/docs/concepts/services-networking/service/#nodeport) is used

Current:
- Only the single service defined in cnf-conformance.yml will be tested

**Comment by taylor** [comment]
What test(s) use(s) services?
- node_port

**Comment by taylor** [comment]
## Scenario 1 - CNF with multiple services will not check for nodeport being used for all services

1. Configure cnf-conformance.yml for a CNF with multiple K8s services
2. Deploy the CNF
3. Run test nodeport_not_used

Expected:
- all services would be tested for CNF to see if [NodePort](https://kubernetes.io/docs/concepts/services-networking/service/#nodeport) is used

Result:
- only the single service defined in cnf-conformance.yml will be tested

**Comment by lixuna** [comment]
Please add level of effort in pts (scale: 0,1,2,3,5,8,13,21)

@wavell 
@williscool
@agentpoyo 
@denverwilliams

**Comment by wavell** [comment]
### Documentation is updated:
- [x] Update the cnf-conformance.yml documentation to reflect that service_name is no longer needed

###  Common steps
- [ ]  Find or create a K8s cluster to use
   - Talk with team for access to an existing cluster
   - [Kind K8s clusters](https://github.com/cncf/cnf-conformance/blob/master/KIND-INSTALL.md) will work as well
- [ ]  Set the KUBECONFIG environment variable for accessing the target K8s cluster
- [ ]  As a developer, Pull down latest version of CNF conformance test code from {FEATURE} branch
     - [ ]  Check that {FEATURE} Branch passes all A/C 
     - [ ]  Check that {FEATURE} Branch passes tests in GitHub Actions
- [ ]  As a peer reviewer, check that PR passes in GitHub Actions
     - [ ] if yes, merge PR to master
     - [ ]  if no, make a comment and request that developer make changes to pass tests 
- [ ]   As a peer reviewer, Pull down latest version of CNF conformance test code from `master` branch
- [ ]  Run `shards install`

### Spec test should pass
- [ ]  Run `crystal spec`
- [ ]  I expect to see PASSED for the tests

### Update Prerequisite checker
- [ ] N/A

### Update example CNFs cnf-conformance.yml, if needed
- [ ] continue, If there is an update to cnf-conformance.yml
- [ ] for each CNF Example
- [ ] Update the example CNF's cnf-conformance.yml to include the new changes
- [ ] Update the example CNF's README if needed
- [ ] Test the example CNF following it's README

### Update yml validator, if needed
- [ ] Service name should not longer be required

### I would expect a CNF that has multiple services to run normally test.
- [x]  Follow common steps above
- [x]  Prepare the test suite to use the CNF by running: `./cnf-conformance cnf_setup cnf-config=./sample-cnfs/sample_statefulset-cnf/cnf-conformance.yml`
- [x]  Run  `./cnf-conformance secrets_used`
- [x]  I expect to see the output from the test
- [x]  I expect to see PASSED for the test


### Screenshots of all command and workload command output
- [ ] I can see a screenshot of the output

**Comment by williscool** [comment]
following AC I ran into this bug on master


![image](https://user-images.githubusercontent.com/394931/110006846-1b776b00-7ce8-11eb-8e99-91c104f5baf1.png)

**Comment by nupejosh** [comment]
![Screen Shot 2021-03-04 at 1 47 11 PM](https://user-images.githubusercontent.com/3164983/110021247-20d8b380-7cf0-11eb-851e-2df280c52c49.png)

**Comment by agentpoyo** [comment]
@lixuna 5pts
