### ISSUE TITLE
[BUG] cnf-conformance.yml helm repo is not added when running cnf_setup

### ISSUE THREAD

**Issue by agentpoyo** [cncf/cnf-conformance#546]
**Describe the bug**
When running cnf_setup against a cnf-conformance.yml, the listed helm chart and repo is not getting added to the list of available helm repos, resulting in a "resource not found" error.

```
./cnf-conformance cnf_setup cnf-config=./path/to/cnf-conformance.yml
```

Check [usage documentation](https://github.com/cncf/cnf-conformance/blob/master/USAGE.md) for more info about invoking commands and loggin

**To Reproduce**
1. Download or git clone cnf-conformance
2. Run common setup steps, `shards install` (if source) and `setup`
3. wget our sample cnf-conformance.yml with the bitnami helm repo from "./sample-cnfs/sample-statefulset-cnf/cnf-conformance.yml"
4. `./cnf-conformance cnf_setup cnf-config=./sample-cnfs/sample-statefulset-cnf/cnf-conformance.yml`
5. See screenshots of errors:

![helm_repo_bug1](https://user-images.githubusercontent.com/14348948/103237363-f859c500-490c-11eb-87f8-d3852d8642b2.jpg)
![helm_repo_bug2](https://user-images.githubusercontent.com/14348948/103237383-03acf080-490d-11eb-9dff-f6b51df27575.jpg)

**Expected behavior**
cnf-conformance should add the helm repo if listed in the cnf-conformance.yml file

**Work Around**
Manually add the repo and rerun the cnf_setup which should show a successful setup:
![helm_repo_bug3](https://user-images.githubusercontent.com/14348948/103237447-41aa1480-490d-11eb-93e5-e4cfb20f25b1.jpg)

**Workstation (please complete the following information):**
 - OS = Linux
 - Distro = Ubuntu
 - Version = 18.04
 - Architecture - amd64; x86

**CNF-CONFORMANCE Version Info**
```
pair@cnfdev03:~/workspace/drew/cnf-conformance$ ./cnf-conformance version
I, [2020-12-28 19:05:04 +00:00 #12811]  INFO -- cnf-conformance: Results file
I, [2020-12-28 19:05:04 +00:00 #12811]  INFO -- cnf-conformance: file exists?:false
I, [2020-12-28 19:05:04 +00:00 #12811]  INFO -- cnf-conformance: VERSION: master-2630095
CNF Conformance version: master-2630095
```

**Comment by wavell** [comment]
Steps to test:

```
helm repo remove cncf
helm repo remove stable
./cnf-conformance cnf_setup cnf-path=sample-cnfs/sample-coredns-cnf 
```
expect to see:
Successfully setup coredns  

after the test add the cncf repo back to the dev box:
```
helm repo add cncf http://cncf.gitlab.io/stable
```

**Comment by agentpoyo** [comment]
LGTM. Running through the same steps is successful, removing the repo from helm, it gets added back when running cnf_setup with the helm repo configured.

**Comment by lixuna** [comment]
Please add level of effort in pts (scale: 0,1,2,3,5,8,13,21)

@agentpoyo 
@wavell 
@denverwilliams

**Comment by agentpoyo** [comment]
2 pts
