### ISSUE TITLE
Configuration test: is there a liveness entry in the Helm chart?

### ISSUE THREAD

**Issue by lixuna** [cncf/cnf-conformance#56]
[Acceptance Criteria](https://github.com/cncf/cnf-conformance/issues/56#issuecomment-594160001)
---

### Configuration test: is there a liveness entry in the Helm chart?

Short Description: 
- to check for a liveness entry in the deployment file of the Helm chart

EPIC: CNF Conformance Test Suite

Release: v0.0.1

Test Category: Configuration and Lifecycle

Type of test (static or runtime) = Runtime

- [x]  example code: #72   

---

**Environment set up tasks:**

**Upstream tool set up tasks: (conformance suite + upstream tools)**
- N/A

**CNF setup Tasks** 

**Sample CNF tasks:**

**Code implementation tasks:**

**Documentation tasks:**
- [ ] Update [Test Categories md](https://github.com/cncf/cnf-conformance/blob/master/TEST-CATEGORIES.md#scaling-tests) if needed 
- [ ] Update [Pseudo Code md](https://github.com/cncf/cnf-conformance/blob/master/PSEUDO-CODE.md#scaling-tests) if needed
- [ ] Update [USAGE md](https://github.com/cncf/cnf-conformance/blob/master/USAGE.md#scaling-tests) if needed 
- [ ] Update [installation instructions](https://github.com/cncf/cnf-conformance#installation)  if needed 

**QA tasks**

Dev Review: 
- [x] walk through A/C
- [x] do you get the expected result?
- [x] if yes, move to `Needs Peer Review` column
- [ ] if no, document what additional tasks will be needed

Peer review:
- [ ] walk through A/C
- [ ] do you get the expected result?
- [ ] if yes, move to `Reviewer Approved` column
- [ ] if no, document what did not go as expected, including error messages and screenshots (if possible)

**Comment by taylor** [comment]
@wavell @denverwilliams @williscool please add A/C before moving to Needs Peer Review

**Comment by lixuna** [comment]
### Acceptance Criteria: 

https://hackmd.io/WDbQfXFPRRCH5Xe-zA_ePA

**Comment by lixuna** [comment]
### Level of effort in pts: 0, 1, 2, 3, 5, 8, 13, 21 = 5 pts

@wavell 5 pts
@denverwilliams 5 pts
@taylor 3 pts
@lixuna 5 pts
