### ISSUE TITLE
[Enhancement] Add existing destructive flag to the `reasonable_startup_time` and `helm_deploy` tests

### ISSUE THREAD

**Issue by lixuna** [cncf/cnf-conformance#562]
[Acceptance Criteria](https://github.com/cncf/cnf-conformance/issues/562#issuecomment-758853622) 

### [Enhancement] Add existing destructive flag to the `reasonable_startup_time` and `helm_deploy` tests

**Is your feature request related to a problem? Please describe.**

The reasonable_startup_time and helm_deploy tests currently cause conflicts for global K8s resource objects, such as CRDs and RBAC, which already exist in the K8s cluster after cnf_setup does the initial CNF deployment. 

Note: There are also conflicts if the cluster has these resource objects prior to the test suite running, but that is not being addressed in this enhancement.

**Describe the solution you'd like**
Add the destructive tag/flag to these two tests so that they can be skipped by default. They can still be run when the destructive option is set to true (config or command line).

**Describe alternatives you've considered**
- Only doing deployments at the start of the test run and not for individual tests. Then refactoring the two tests.
- Disabling the two tests completely.  (commenting out)
- Updating the global resource names to be unique for every deployment

**Additional context**
Related ticket [[BUG] Fix resource conflict issue affecting all tests that need to install the CNF #552
](https://github.com/cncf/cnf-conformance/issues/552)

References:

- https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/
- https://kubernetes.io/docs/reference/access-authn-authz/rbac/

**Comment by lixuna** [comment]
DRAFT - Acceptance Criteria: building on A/C from #531 
---

### Documentation is updated, as needed:
- [ ]  USAGE is updated
- [ ]  Test Categories md is updated
- [ ]  Installation instructions is updated

Note: CNF configuration may or may not change in this ticket. Update docs accordingly.

###  Common steps
- [ ]  Find or create a K8s cluster to use
   - Talk with team for access to an existing cluster
   - [Kind K8s clusters](https://github.com/cncf/cnf-conformance/blob/master/KIND-INSTALL.md) will work as well
- [ ]  Set the KUBECONFIG environment variable for accessing the target K8s cluster
- [ ]  Set the GITHUB_USER environment variable for running the specs
- [ ]  Set the GITHUB_TOKEN environment variable for running the specs
- [ ]  Set the DOCKERHUB_USERNAME environment variable for running the specs
- [ ]  Set the DOCKERHUB_PASSWORD environment variable for running the specs
- [ ]  As a developer, Pull down latest version of CNF conformance test code from {FEATURE} branch
     - [ ]  Check that {FEATURE} Branch passes all A/C 
     - [ ]  Check that {FEATURE} Branch passes tests in GHA CI
- [ ]  As a peer reviewer, check that PR passes GHA CI tests
     - [ ] if yes, merge PR to master
     - [ ]  if no, make a comment and request that developer make changes to pass tests 
- [ ]   As a peer reviewer, Pull down latest version of CNF conformance test code from `master` branch
- [ ]  Run `shards install`

### Spec test should pass
- [ ]  Run `crystal spec`
- [ ]   I expect to see PASSED for the tests

### Update Prerequistite checker
- TBD

### Update cnf-conformance.yml
- [ ] N/A
- [ ] Update cnf-conformance.yml
   - [ ] Remove configuration items which are now determined dynamically
   - [ ] Remove configuration items which are not used anywhere anymore
- [ ] continue, If there is an update to cnf-conformance.yml
- [ ] for each CNF Example
- [ ] Update the example CNF's cnf-conformance.yml to include the new changes
- [ ] Update the example CNF's README if needed
- [ ] Test the example CNF following it's README

Note: CNF configuration may or may not change in this ticket. Update example CNFs and cnf-conformance.yml example files accordingly. 

### Update yml validator, if needed
- [ ] N/A
- [ ] Update yaml to support any changes in CNF configuration

### Using `crystal spec spec/workload` command with good samples of the workload resource types Deployment, ReplicaSet, StatefulSet, and DaemonSet should PASS and with a "bad" samples should FAIL:
- [ ]  Run `crystal spec spec/workload`
- [ ]  I expect to see the output and results from all workload tests in the spec/workload directory
- [ ]  I expect to see PASSED for all specs
  - Bad CNFs fail as expected
  - Good CNFs pass as expected

### I would expect the CNF to show results without exceptions/errors when I run the entire test suite (`workload`) for a  CNF which has all of the workload resource types:  Deployment, ReplicaSet, StatefulSet, and DaemonSet
- [ ]  Follow common steps above
- [ ]   Prepare the test suite to use the CNF by running: `./cnf-conformance cnf_setup cnf-config=./sample-cnfs/sample-statefulset-cnf/cnf-conformance.yml`
- [ ]  Run  `./cnf-conformance workload`
- [ ]   I expect to see individual FAILURE test messages for any container from any of the supported Workload Resource types
- [ ]  I expect to see a final FAILURE or PASS test message for each test for the entire CNF (or K8s Workload)
- [ ]  I expect to see the specific Workload Resource and Container that failed in any final FAILURE message for a test
- [ ]  I do not expect to see any stack traces, exceptions, or unexpected application errors


### Screenshots of spec and tests runs with results in the comments
- [ ]  I can see a screenshot of the spec run in the comments of this ticket
- [ ]   I can see a screenshot of the test run in the comments of this ticket
- [ ]  I can see the test results in the comments of this ticket

**Comment by taylor** [comment]
Potential warnings/communication:

- disabled tests which have conflicts
- test suite could clobber global data. Don’t run on shared cluster nor production

**Comment by lixuna** [comment]
Level of effort in pts: 0,1,2,3,5,8,13,21: 
---

- @denverwilliams 
- @wavell 
- @williscool 
- @nupejosh n/a
- @agentpoyo 
- @taylor 
- @lixuna

**Comment by agentpoyo** [comment]
![562_peer_review](https://user-images.githubusercontent.com/14348948/105245959-32973a80-5b38-11eb-9e3b-2c0f1ee8c012.png)

**Comment by agentpoyo** [comment]
![562_peer_review_1](https://user-images.githubusercontent.com/14348948/105246142-768a3f80-5b38-11eb-9095-2f8a2d0866ed.png)

**Comment by agentpoyo** [comment]
![562_peer_review_2](https://user-images.githubusercontent.com/14348948/105247202-0381c880-5b3a-11eb-8a64-a74489b39315.png)

**Comment by agentpoyo** [comment]
![562_peer_review_3](https://user-images.githubusercontent.com/14348948/105247569-9b7fb200-5b3a-11eb-9cff-0d33b57a0703.png)

**Comment by agentpoyo** [comment]
LGTM :+1:
