### ISSUE TITLE
[Feature] cnf installation refactor for samples, examples, and end-user supplied cnfs to use cnf manager

### ISSUE THREAD

**Issue by wavell** [cncf/cnf-conformance#569]
**Is your feature request related to a problem? Please describe.**
The cnf installation procedure for samples is not consistent and is problematic for #552 (resource conflict affecting CNF installation)

**Describe the solution you'd like**
The cnf installation procedure should be refactored to assist with  #552 

Specifically use the CNF Manager for all samples

**Comment by lixuna** [comment]
@wavell @denverwilliams @agentpoyo  What are your estimates in points for this refactoring?

Scale: 0,1,2,3,5,8,13,21

**Comment by williscool** [comment]
@wavell @denverwilliams 

reiviewd from what I can tell the refactor makes all of the samples go through

`sample_setup` in `src/tasks/utils/cnf_manager.cr`

Which will make it easier to make sure cnf install relataed all happen in one place to to make potentially destrutivce changes easier to avoid and fix

https://github.com/cncf/cnf-conformance/issues/552

correct?

can you update the descrption a bit?

**Comment by agentpoyo** [comment]
3pts

**Comment by taylor** [comment]
@williscool do you approve this as complete (re: needs peer review).

fyi I updated the description based on what you said.

**Comment by wavell** [comment]
2 pts

**Comment by williscool** [comment]
Ok or matches description now.

Lgtm
