### ISSUE TITLE
Configuration test: is there a readiness entry in the Helm chart?

### ISSUE THREAD

**Issue by lixuna** [cncf/cnf-conformance#57]
[Acceptance Criteria](https://github.com/cncf/cnf-conformance/issues/57#issuecomment-594174746) 
---

### Configuration test: is there a readiness entry in the Helm chart?

EPIC: CNF Conformance Test Suite

Release: v0.0.1

Test Category: Configuration and Lifecycle

Type of test (static or runtime) = 

- [ ]  example code: #72  

---

**Environment set up tasks:**

**Upstream tool set up tasks: (conformance suite + upstream tools)**
- N/A

**CNF setup Tasks** 

**Sample CNF tasks:**

**Documentation tasks:**
- [ ] Update [Test Categories md](https://github.com/cncf/cnf-conformance/blob/master/TEST-CATEGORIES.md) if needed 
- [ ] Update [Pseudo Code md](https://github.com/cncf/cnf-conformance/blob/master/PSEUDO-CODE.md) if needed
- [ ] Update [USAGE md]**Code implementation tasks:**
(https://github.com/cncf/cnf-conformance/blob/master/USAGE.md) if needed 
- [ ] Update [installation instructions](https://github.com/cncf/cnf-conformance#installation)  if needed 

**QA tasks**

Dev Review: 
- [x] walk through A/C
- [x] do you get the expected result?
- [x] if yes, move to `Needs Peer Review` column
- [ ] if no, document what additional tasks will be needed

Peer review:
- [ ] walk through A/C
- [ ] do you get the expected result?
- [ ] if yes, move to `Reviewer Approved` column
- [ ] if no, document what did not go as expected, including error messages and screenshots (if possible)

**Comment by taylor** [comment]
@wavell @denverwilliams @williscool please add A/C before moving to Needs Peer Review

**Comment by lixuna** [comment]
### Acceptance Criteria:

###  Common steps
- [ ]  Find or create a K8s cluster to use
  - [ ] Steps for creating will be in another ticket  
  - [ ] Talk with team for access to an existing cluster
- [ ] Set the KUBECONFIG environment variable for accessing the target K8s cluster
- [ ]  As a developer, Pull down latest version of CNF conformance test code from `develop` branch
- [ ] As a peer reviewer, Pull down latest version of CNF conformance test code from `master` branch
- [ ]  Run shard install
- [ ] Run crystal spec
- [ ] I expect to see PASSED for the tests

### When using the test `crystal src/cnf-conformance.cr readiness` command the sample "good" CNF should PASS test successfully:
- [ ]  Run  `crystal src/cnf-conformance.cr sample_CoreDNS_CNF_setup`
- [ ]  Run  `crystal src/cnf-conformance.cr readiness` 
- [ ] I expect to see the output and results from the test
- [ ] I expect to see PASSED for the test

### When using the test `crystal src/cnf-conformance.cr readiness` command the sample "bad" CNF should FAIL test:
- [ ] Run `crystal src/cnf-conformance.cr  sample_coredns_cnf_cleanup` 
- [ ] Run  `crystal src/cnf-conformance.cr missing_readiness_setup`
- [ ]  Run  `crystal src/cnf-conformance.cr readiness` 
- [ ] I expect to see the output and results from the test
- [ ] I expect to see FAIL for the test

### I would expect the CNF to pass when I run the entire test category suite (`configuration_lifecycle`)
- [ ] Run `crystal src/cnf-conformance.cr missing_readiness_cleanup` 
- [ ]  Run  `crystal src/cnf-conformance.cr sample_CoreDNS_CNF_setup`
- [ ]  Run  `crystal src/cnf-conformance.cr configuration_lifecycle`
- [ ] I expect to see the output and results from all tests in the test category
- [ ] I expect to see PASSED for the test category

### I would expect the CNF to pass when I run the entire test suite (`all`)
- [ ]  Follow common steps above
- [ ]  Run  `crystal src/cnf-conformance.cr all`
- [ ] I expect to see the output from the test
- [ ] I expect to see PASSED for the test


-----

## Steps after A/C fails

If all A/C fails for peer reviewer
- [ ] Add a comment to the PR summarizing the problem tagging the developer
- [ ] Attach any console output or logs that can help the developer fix the issue

## Steps after A/C Passes

If all A/C passes for developer
- [ ]  open a Pull Request to master branch and mark as "developer approved"
- [ ] Tag team members for peer review


If all A/C passes for peer reviewer
- [ ] Mark the PR as approved and merge the PR into `master`

**Comment by lixuna** [comment]
### Level of effort in pts: 0, 1, 2, 3, 5, 8, 13, 21 = 5 pts

@wavell 5 pts
@denverwilliams 5 pts
@taylor 3 pts
@lixuna 3 pts
