### ISSUE TITLE
[BUG] After running cnf_setup, cnf-conformance errors "you must provide cnf-config or cnf-path" when running tests after the setup.

### ISSUE THREAD

**Issue by agentpoyo** [cncf/cnf-conformance#572]
**Describe the bug**
When running `cnf-conformance cnf_setup cnf-config=./path/to/cnf-conformance.yml`; running additional tests require cnf-config=path again when it should read from the cnfs/ directory.

**To Reproduce**
1. Setup a cnf-conformance.yml
2. Follow basic steps to setup cnf-conformance; `cnf-conformance setup; cnf-conformance cnf_setup cnf-config=./cnf-conformance.yml`
3. Upon successful install of your CNF, now run `cnf-conformance workload` to initiate workload tests which produces the following error:
```
$ LOG_LEVEL=error ./cnf-conformance workload
Error: You must supply either cnf-config or cnf-path
```

**Expected behavior**
cnf-conformance should proceed in running the workload tests from the copied cnf-conformance created in the cnfs/ directory, in my case it was created cnfs/wordpress:

```
$ ls -al cnfs/
total 12        
drwxrwxr-x  3 pair pair 4096 Jan 19 18:53 .
drwxrwxr-x 16 pair pair 4096 Jan 19 18:53 ..
drwxrwxr-x  3 pair pair 4096 Jan 19 18:53 wordpress
```

**Screenshots**

![cnf_setup_error](https://user-images.githubusercontent.com/14348948/105081148-7108f880-5a57-11eb-9fd6-55e810635da4.png)

**Device (please complete the following information):**
 - OS - Linux
 - Distro - Ubuntu
 - Version - 18.04
 - Architecture - x86

**Comment by agentpoyo** [comment]
@wavell @denverwilliams 

Using the example coredns cnf-conformance in master branch: https://raw.githubusercontent.com/cncf/cnf-conformance/master/example-cnfs/coredns/cnf-conformance.yml while following the INSTALL instructions, I could not reproduce the error above.

I'll see what might cause this by playing with some of the fields in the cnf-conformance.yml file or doing it outside of the checked out git repo where it has the example code included.

**Comment by agentpoyo** [comment]
This now passes after running workload and other tests without having to specify the cnf-config for each test.

**Comment by lixuna** [comment]
@agentpoyo @wavell What are your estimates in points for this bugfix?

Scale: 0,1,2,3,5,8,13,21

**Comment by agentpoyo** [comment]
I'm gonna say 1 pt
