### ISSUE TITLE
[BUG] typo in release name of latest stable (v0.10.0)

### ISSUE THREAD

**Issue by lixuna** [cncf/cnf-conformance#574]
**Describe the bug**
- the latest release name/tag/commit has a typo 
- what I see now: v1.10.0 

**To Reproduce**
1. Go to https://github.com/cncf/cnf-conformance/releases/tag/v1.10.0
2. Name of release, tag, commit, is currently called v1.10.0

**Expected behavior**
- what I would expect to see: Release name, tag, commit etc should be named v0.10.0 (the test suite is not ready for v1 quite yet)

**Comment by lixuna** [comment]
Actions taken:
- published new release and binary named v0.10.0
- deleted tag for v1.10.0

**Comment by lixuna** [comment]
Problems found:
- new commits may be referencing the invalid tag `v1.10.0` as the `v1.10.0` tag is appearing in the dropdown list unexpectedly
- Developers, please update your code to use `v0.10.0`

**Comment by wavell** [comment]
https://github.com/cncf/cnf-conformance/releases/tag/v0.10.0

**Comment by lixuna** [comment]
Please add level of effort in pts (scale: 0,1,2,3,5,8,13,21)

@agentpoyo
@wavell

**Comment by agentpoyo** [comment]
1pt
