### ISSUE TITLE
[BUG] Rollling Update ls root if cnf not installed

### ISSUE THREAD

**Issue by williscool** [cncf/cnf-conformance#576]
**Describe the bug**

**To Reproduce**

```
./cnf-conformance cleanup
./cnf-conformance rolling_update verbose
```

**Expected behavior**

I expect the testsuite to not do anything as a cnf is not installed at all

**Screenshots**

![rolling-update-bug](https://user-images.githubusercontent.com/394931/105326856-09d27c00-5bf0-11eb-9663-b7a9fefce342.gif)

**Device (please complete the following information):**
 - OS : Windows wsl 2
 - Distro: Ubuntu
 - Version: Ubuntu-20.04
 - Architecture [e.g. x86, arm]

**Additional context**

---

NOTE: you can enable higher logging level output via the command line or env var. to help with debugging

```
# cmd line
./cnf-conformance -l debug test

# make sure to use -- if running from source
crystal src/cnf-conformance.cr -- -l debug test 

# env var
LOGLEVEL=DEBUG ./cnf-conformance test
```

Also setting the verbose option for many tasks will add extra output to help with debugging

```
crystal src/cnf-conformance.cr test_name verbose
```

Check [usage documentation](https://github.com/cncf/cnf-conformance/blob/master/USAGE.md) for more info about invoking commands and loggin

**Comment by wavell** [comment]
See #603

**Comment by agentpoyo** [comment]
This has been peer reviewed in #603 and #620, which should meet the AC requirements.

**Comment by lixuna** [comment]
Estimate in points? (ex 0,1,2,3,5,8,13,21)

@wavell @williscool  @agentpoyo

**Comment by agentpoyo** [comment]
3 pts
