### ISSUE TITLE
[Documentation] Address, Fix, Update and Edit the INSTALLmd and other technical Documentation guides

### ISSUE THREAD

**Issue by agentpoyo** [cncf/cnf-conformance#577]
**Documentation Fix and Changes**

Need to address documentation for INSTALL and other technical documentation to align with proper steps for smoother guides to install cnf-conformance.

Example fix is on lines 101-102, we provide a wget on a tar.gz but then skip over the tar command to unpack the tarball:
```
wget https://github.com/cncf/cnf-conformance/releases/download/latest/latest.tar.gz
chmod +x cnf-conformance
```
Should be:
```
wget https://github.com/cncf/cnf-conformance/releases/download/latest/latest.tar.gz
tar xzf latest.tar.gz
chmod +x cnf-conformance
```

**Comment by agentpoyo** [comment]
Another potential issue found during a walk through of all steps is during the source installation guide.

We specify to git clone the cnf-conformance repository over SSH but using a local user without any github configurations or perhaps if users do not have an actual github account, this will result with permission denied errors:
```
drew@cnfdev03:~$ git clone git@github.com:cncf/cnf-conformance.git
Cloning into 'cnf-conformance'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```
But switching to HTTPS works:
```
drew@cnfdev03:~$ git clone https://github.com/cncf/cnf-conformance.git
Cloning into 'cnf-conformance'...
remote: Enumerating objects: 271, done.
remote: Counting objects: 100% (271/271), done.
remote: Compressing objects: 100% (212/212), done.
remote: Total 9490 (delta 178), reused 106 (delta 59), pack-reused 9219
Receiving objects: 100% (9490/9490), 1.65 MiB | 6.19 MiB/s, done.
Resolving deltas: 100% (6451/6451), done.
```

We need to update the INSTALL and SOURCE-INSTALL to make sure users are directed to git clone over HTTPS to prevent errors if they do not have direct access as a git user over SSH to github.

Line 118 in the INSTALL.md guide:
```
git clone git@github.com:cncf/cnf-conformance.git
```
Should be changed to:
```
git clone https://github.com/cncf/cnf-conformance.git
```

And line 80 in SOURCE-INSTALL.md should be updated as well.

**Comment by agentpoyo** [comment]
Need to add instructions on how to set the DOCKER user/pass for pulling public Docker Images for cn-conformance in the INSTALL.md docs.

Link to the K8's https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/ for private registry secrets

**Comment by agentpoyo** [comment]
Update k8s-infra in the k8's cluster support to Testbed.

**Comment by agentpoyo** [comment]
```
On https://github.com/cncf/cnf-conformance/blob/master/TEST-CATEGORIES.md#configuration-and-lifecycle-tests, I can see a new sentence about immutable_configmap
```
Needs to be added.

**Comment by lixuna** [comment]
Please add level of effort in pts (scale: 0,1,2,3,5,8,13,21)
@taylor 
@agentpoyo

**Comment by agentpoyo** [comment]
2pts
