### ISSUE TITLE
[BUG] (v0.10.0) Binary installation is missing directories and files

### ISSUE THREAD

**Issue by michaelspedersen** [cncf/cnf-conformance#579]
**Describe the bug**
When installing v0.10.0 using binary, files needed for (at least) the resilience tests are missing. Files are present in source under `spec/`, but when installing from binary they are not added.

**To Reproduce**
1. Download and extract the [v0.10.0 binary](https://github.com/cncf/cnf-conformance/releases/download/v0.10.0/cnf-conformance-v0.10.0.tar.gz)
2. Follow the [installation guide](https://github.com/cncf/cnf-conformance/blob/v0.10.0/INSTALL.md), using `setup` and `cnf_setup` with CoreDNS example
3. Run `all` or `resilience` tests (with loglevel DEBUG)
4. Wait for messages about "Waiting for CRD", which refers to a resource file expected, but not available, in `spec/fixtures/`

**Expected behavior**
The references files should be present, and the "Waiting for CRD" should resolve itself and the test continue

**Device (please complete the following information):**
 - OS: Linux
 - Distro: Ubuntu
 -  - Version: 18.04.5 (5.4.0-52-generic)
 - Architecture: x86

**Comment by wavell** [comment]
I think these references are the problem:

./src/tasks/chaos_mesh_setup.cr:23:  wait_for_resource("#{current_dir}/spec/fixtures/chaos_network_loss.yml")
./src/tasks/chaos_mesh_setup.cr:24:  wait_for_resource("#{current_dir}/spec/fixtures/chaos_cpu_hog.yml")
./src/tasks/chaos_mesh_setup.cr:25:  wait_for_resource("#{current_dir}/spec/fixtures/chaos_container_kill.yml")

We are currently packaging any yml files that need to be distributed with the binary directly in the binary by using macros.  See: src/tasks/utils/embedded_file_manager.cr
e.g.
```
  macro reboot_daemon
    REBOOT_DAEMON = Base64.decode_string("{{ `cat ./tools/reboot_daemon/manifest.yml | base64` }}")
  end 
```

**Comment by agentpoyo** [comment]
This looks good but the changes won't reflect in the current v0.10.0 binary, should get added on the next stable release.

**Comment by agentpoyo** [comment]
![579-cnf-conformance-no_error](https://user-images.githubusercontent.com/14348948/106509169-de268000-6492-11eb-8faf-a9fbdff4c7db.png)

Screenshot using the latest master build binary to show no more complains about missing chaos yml files.

**Comment by lixuna** [comment]
Please add level of effort in pts (scale: 0,1,2,3,5,8,13,21)

@agentpoyo
@wavell
@denverwilliams
@williscool

**Comment by agentpoyo** [comment]
2pts
