### ISSUE TITLE
[BUG] Debug type output is displayed when LOG_LEVEL=error

### ISSUE THREAD

**Issue by agentpoyo** [cncf/cnf-conformance#580]
** Describe the Bug **
Creating a cnf-conformance.yml with all empty lines for each of the values "helm_chart, helm_directory, or manifest_directory" results in error:

```
$ LOG_LEVEL=error ./cnf-conformance cnf_setup cnf-config=./cnf-conformance.yml
Successfully created directories for cnf-conformance
Error: Must populate at lease one installation type in ./cnf-conformance.yml: choose either helm_chart, helm_directory, or manifest_directory in cnf-conformance.yml!
```

Crystal code should likely only display when in DEBUG as this is what follows after the error above:

```
src/tasks/utils/cnf_manager.cr:423:7 in 'cnf_installation_method'
src/tasks/utils/cnf_manager.cr:39:24 in 'parse_config_yml'
src/tasks/utils/cnf_manager.cr:692:5 in 'sample_setup'
src/tasks/cnf_setup.cr:110:3 in '->'
../../../.crenv/versions/0.35.1/share/crystal/src/primitives.cr:255:3 in 'call'
lib/sam/src/sam/execution.cr:20:7 in 'invoke'
lib/sam/src/sam.cr:35:5 in 'invoke'
lib/sam/src/sam.cr:53:7 in 'process_tasks'
src/cnf-conformance.cr:94:3 in '__crystal_main'
../../../.crenv/versions/0.35.1/share/crystal/src/crystal/main.cr:105:5 in 'main_user_code'
../../../.crenv/versions/0.35.1/share/crystal/src/crystal/main.cr:91:7 in 'main'
../../../.crenv/versions/0.35.1/share/crystal/src/crystal/main.cr:114:3 in 'main'
__libc_start_main
_start
???
Error: Must populate at lease one installation type in ./cnf-conformance.yml: choose either helm_chart, helm_directory, or manifest_directory in cnf-conformance.yml!
```

![547_conformance_output](https://user-images.githubusercontent.com/14348948/105102896-3910ae00-5a75-11eb-8391-18b4871811c7.png)

**Comment by taylor** [comment]
@wavell needs checking

**Comment by wavell** [comment]
- [ ] create a cnf-conformance.yml that doesn't not have any of the following tags `helm_chart, helm_directory, or manifest_directory`
- [ ] `LOG_LEVEL=error ./cnf-conformance cnf_setup cnf-config=./cnf-conformance.yml`
- [ ] I should not see any stack trace

**Comment by agentpoyo** [comment]
![image](https://user-images.githubusercontent.com/14348948/114788435-0cec8c80-9d47-11eb-95de-668031243d40.png)

**Comment by lixuna** [comment]
@wavell @agentpoyo what was the level of effort in pts to make this change? (0,1,2,3,5,8,13,21)

**Comment by agentpoyo** [comment]
3 pts
