### ISSUE TITLE
[Feature] Enhance usability for closed-source CNFs : image size

### ISSUE THREAD

**Issue by clementnuss** [cncf/cnf-conformance#587]
**Is your feature request related to a problem? Please describe.**
When using cnf-conformance to test closed-source CNF (a real 5G Core CNF from a vendor :)), it is not possible to do the `reasonable_image_size` test, because the images are (obviously) not published on Docker.io

**Describe the solution you'd like**
The image size should be looked up by reading the local registries instead (parsing the output of `docker image ls`)

**Comment by taylor** [comment]
@clementnuss we are looking into this and any other workload test that does not support user/password protected registries. See #594

**Comment by williscool** [comment]
lgtm tests pass and we use `wc` on the image now

https://github.com/cncf/cnf-conformance/commit/3bbbad40c86a798834e4b935de09cfceeba7f6c5#diff-12273f6a8e593c98cbde8172a228325c8a4ce51061caee489da9068878394851R173

**Comment by lixuna** [comment]
Please add level of effort in pts (scale: 0,1,2,3,5,8,13,21)

@agentpoyo
@williscool

**Comment by agentpoyo** [comment]
@lixuna  3pts

**Comment by williscool** [comment]
3 pts

**Comment by clementnuss** [comment]
Well done! Thanks for implementing this 👏🏼
