### ISSUE TITLE
[Feature] cnf_manager references to kubectl get should be moved to KubectlClient Module

### ISSUE THREAD

**Issue by wavell** [cncf/cnf-conformance#590]
**Is your feature request related to a problem? Please describe.**
cnf_manager references to kubectl get should be moved to KubectlClient Module

**Describe the solution you'd like**
cnf_manager references to kubectl get should be moved to KubectlClient Module

**Describe alternatives you've considered**
Leave the code as is.

**Additional context**
Will assist with implementation of ticket #545

**Comment by lixuna** [comment]
Please add level of effort in pts (scale: 0,1,2,3,5,8,13,21)

@agentpoyo
@wavell
@denverwilliams

**Comment by agentpoyo** [comment]
5pts

**Comment by williscool** [comment]
mostly there but I found a couple of spots that are not using kubectl client

https://github.com/cncf/cnf-conformance/blob/master/src/tasks/utils/cnf_manager.cr#L889
https://github.com/cncf/cnf-conformance/blob/master/src/tasks/utils/cnf_manager.cr#L890

https://github.com/cncf/cnf-conformance/blob/master/src/tasks/utils/cnf_manager.cr#L949

**Comment by williscool** [comment]
ltgm after update
