### ISSUE TITLE
[Open Beta Test] Create clusters for beta testing phase 2

### ISSUE THREAD

**Issue by lixuna** [cncf/cnf-conformance#592]
ISSUE IN PLANNING:
---

## Description
- clusters needed for beta testing cnf test suite

---

Tasks:
- [ ] Determine smallest cluster sized required for MVP = 2 nodes, 1 master and 1 worker
- [ ] Determine smallest machine size needed = t1.small works as expected for MVP set of tests. (Any *.small)
- [ ] Determine available facilities
- [ ] Spin up required number of clusters in x and y facilities
    - [ ] Create n clusters in x facilities
    - [ ] Create n clusters in y facilities
    - Using CNF Testbed tooling (+k8s-infra)
    - [ ] Split load across  in x and y facilities
       - [ ]  n clusters in x facilities
       - [ ]  n clusters in y facilities
    - [ ] 1 cluster for each tester
    - [ ] 11 testers total = 11 clusters =   22 nodes (machines)
- [ ] Save kubeconfig files to secure location
- [ ] Test access to each cluster using `kubectl cluster-info` and KUBECONFIG environment set for each cluster
- [ ] Add comment with cluster name and IP info to this ticket for each cluster

**Comment by lixuna** [comment]
Beta cluster 1: 
- requested on 2/23/2021
- shared on 2/24/2021

**Comment by lixuna** [comment]
Beta cluster 2: 
- requested on 3/1/2021
- shared on tbd

**Comment by agentpoyo** [comment]
> Beta cluster 2:
> 
> * requested on 3/1/2021
> * shared on tbd

Started now. Once cluster is ready, will draft email to send.

**Comment by agentpoyo** [comment]
Email sent to second request and shared on 3/3/2021 for Beta Cluster 2

**Comment by agentpoyo** [comment]
Put back in "Ready for Dev" in case we get any more signups.

**Comment by lixuna** [comment]
@agentpoyo, Please add level of effort in pts for setting up these clusters (scale: 0,1,2,3,5,8,13,21)


After points are assigned, we can close this issue. The beta testing phase 2 period ended on Fri, March 5.

**Comment by agentpoyo** [comment]
5pts @lixuna
