### ISSUE TITLE
[Research] Determine Docker Hub API support in registries used by end users for v0.10.0 Beta Testing

### ISSUE THREAD

**Issue by taylor** [cncf/cnf-conformance#597]
**Is your feature request related to a problem? Please describe.**

Some tests depend on Docker Hub API, including
- image size check
- observability prometheus check (SHA has check)

If end-users are using a registry other than Docker HUB then we need to determine if that registry has Docker Hub API compatibility.

**Describe the solution you'd like**
Review registries in use by current end users of test suite.

List registries known registries and provide links to public docs if available.

Determine if registry has Docker Hub API compatibility.

**Other details*

Some registries:
- "Official" Docker Registry 2.0 - https://docs.docker.com/registry/
- Gitlab registry
- Harbor - https://vmware.github.io/harbor/
- Quay - https://quay.io/
- Atomic Registry - http://www.projectatomic.io/registry/
- Portus - http://port.us.org/
- Sonatype Nexus Repository Manager OSS 3.xx - https://www.sonatype.com/nexus-repository-oss
- Amazon Elastic Container Registry (ECR)
- Azure Container Registry
- Google Container Registry

**Comment by lixuna** [comment]
Please add level of effort in pts (scale: 0,1,2,3,5,8,13,21)

@agentpoyo

**Comment by agentpoyo** [comment]
2pts

**Comment by taylor** [comment]
CONFIRMED: Docker Hub is in use by some of the current end users.

**Comment by taylor** [comment]
querying docker hub api for image data. Example: https://hub.docker.com/v2/repositories/library/busybox/?page_size=100

**Comment by taylor** [comment]
https://docs.docker.com/registry/spec/api/#api-version-check

**Comment by taylor** [comment]
orgs and images go under /v2 for the official Docker Regsitry API. see https://docs.docker.com/registry/spec/api/#overview

>This section covers client flows and details of the API endpoints. The URI layout of the new API is structured to support a rich authentication and authorization model by leveraging namespaces. All endpoints will be prefixed by the API version and the repository name:

> 
> /v2/<name>/
> For example, an API endpoint that will work with the library/ubuntu repository, the URI prefix will be:
> 
> /v2/library/ubuntu/

**Comment by taylor** [comment]
/v2/_catalog is Docker Registry API  call for viewing available repos.  See https://docs.docker.com/registry/spec/api/#listing-repositories

It is turned off for public Docker Hub -- try https://hub.docker.com/v2/_catalog -- , but may be on for private registries using the official Docker Registry software
