### ISSUE TITLE
[Feature] Update Specs to test binary without source code in same directory

### ISSUE THREAD

**Issue by williscool** [cncf/cnf-conformance#599]
**Is your feature request related to a problem? Please describe.**

As a follow up to https://github.com/cncf/cnf-conformance/issues/579

There is no automated, CI validation that the binary works without source code in the same directory.

We should make sure we run each test with and without the codebase in the root (many people who download the binary will use the test suite like this)

**Describe the solution you'd like**

use the https://github.com/cncf/cnf-conformance/tree/master/tools/curl_install_tester_docker_setup

to test the binary works without being in a source code checkout

**Describe alternatives you've considered**

I guess we could manually add it to the test checklist but I think it's simple enough to automate that that's not necessary

**Additional context**

The reason to do this is because currently all of the specs run the test with a binary that's run in the directory with all the source code.

this leads to us at times inadvertently adding dependencies on files that are not shipped with the binaries to our tests.

This becomes an issue at times because many new users and customers use the binary installs or the curl installs at first and don't always have the source code so they are the first ones to catch these bugs which is a bad user experience.

**Comment by williscool** [comment]
1. install binary somewhere (spec or github action?)
    a. in a docker container (with no source)
    b. remember, don't mount the source
3. install cnf
4. run cnf-conformance workload
5. (optional) check for exit code > 0 (this is a failure)
    a. Do something nice with the answer/message
6. return exit code from step 3

h/t @wavell @denverwilliams @agentpoyo

**Comment by williscool** [comment]
tryin to sort out this 

![image](https://user-images.githubusercontent.com/394931/110073705-d25a0200-7d4d-11eb-84a2-548f827da933.png)

**Comment by agentpoyo** [comment]
Testing binary now runs successfully in github actions on master. LGTM :+1: 

![599_test_binary_without_source_gh](https://user-images.githubusercontent.com/14348948/112043391-9cbb6400-8b16-11eb-8512-beddca8ffce0.png)

**Comment by agentpoyo** [comment]
### Acceptance Criteria for peer review 
--
### Documentation is updated:
- [ ] n/a

###  Common steps
- [ ]  n/a

### Spec test should pass
- [ ]  n/a

### Update Prerequisite checker
- [ ] N/A

### Update yml validator, if needed
- [ ] N/A

### I would expect that the `Test Binary without Source` runs on `master` branch merges.
- [ ]  Browse to https://github.com/cncf/cnf-conformance/actions
- [ ]  Find the latest `master` branch github action in history.
- [ ]  Verify the `Test Binary Without Source` is running after the `Build Release` steps
- [ ]  I expect to not see FAILED for the binary test.

### Screenshots of all command and workload command output
- [ ] I can see a screenshot of the Github Action `Test Binary Without Source`

**Comment by lixuna** [comment]
Level of effort in points: 0,1,2,3,5,8,13,21: 
---
@wavell - 
@williscool - 
@agentpoyo -

**Comment by agentpoyo** [comment]
8pts @lixuna
