### ISSUE TITLE
Installable test: Is the CNF's helm chart valid (ie. does it pass linting)?

### ISSUE THREAD

**Issue by taylor** [cncf/cnf-conformance#6]
[WIP Acceptance Criteria](https://github.com/cncf/cnf-conformance/issues/6#issuecomment-590999144)
---

### Installable test: Is the CNF's helm chart valid / Does the CNF's helm chart pass linting?

EPIC: CNF Conformance Test Suite

Release: v0.0.1

Test Category: Installable + Upgradeable

Type of test (static or runtime) = static

---

**Environment set up tasks:**
- [x] Follow the [installation instructions](https://github.com/cncf/cnf-conformance#installation) to set up the the conformance suite for development and testing
- [x] Update installation instructions to cover new setup and existing workstation updates.  Example:
   - You should have a working conformance suite that compiles and runs correctly.  (eg. crystal-lang installed)
   - [x] If you have it installed, pull down latest version of CNF conformance test code from develop branch (eg. `git fetch ; get rebase` from the cnf-conformance directory)
   - [x] Run `shard install` to get dependencies

**Upstream tool set up tasks: (conformance suite + upstream tools)**
- [x] N/A linter is part of Helm, Helm is installed already

**Sample CNF tasks:**  (eg. Vendor CNF)
- [x] update [sample cnf-conformance.yml](https://github.com/cncf/cnf-conformance/blob/develop/sample-cnfs/sample-coredns-cnf/cnf-conformance.yml) for using CoreDNS as a valid CNF in the sample coredns folder
    - Example config:
    ```
    ---
    cnf_name: coredns
    deployment_name: coredns # coming in issue #24
    chart_path: cnfs/coredns 
    ```
- [x] Create a bad helm chart CNF Sample based on CoreDNS working chart
- [x] Create a sample configuration for testing a CNF
    - [x] cnf folder name (that's a subdir of the /cnfs/ folder)
    - [x] chart folder name
    ```
    ---
    cnf_name: badhelmchart
    deployment_name: badhelmchart # coming in issue #24
    chart_path: cnfs/sample-bad-helm-chart
    ```
**Target CNF Tasks** (eg. How do we use the sample CNF)

DEFERRED See https://github.com/cncf/cnf-conformance/issues/6#issuecomment-592070922
- [ ] Check /cnfs folder for CNFs.
    - [ ] For each folder check inside for a cnf-conformance.yml. If the file is found run conformance tests for that CNF
- [ ] Update documentation to say that each CNF should be in a subfolder of the CNF

    
**Code implementation tasks:**
- [x] If one test blows up (eg. CNF code not found for static) the suite should continue to run
- [x] Add code to run helm linter
- [x] Add code for checking results in output from the linter
- [x] Add code for specifying the helm chart path
    - [x] Support finding helm chart path from target CNF configuration file. Example pseudo configuration:
    ```
    ---
    cnf_name: coredns
    deployment_name: coredns # coming in issue #24
    chart_path: cnfs/coredns 
    ```
    - [x] Support finding helm chart path from CLI option. Example pseudo code: `--cnf-chart-path cnfs/coredns/cnf-conformance.yml`
- [x] Print the name of the chart that was tested
- [x] Print if the test was PASS or FAIL
- [x] Make PASS green and RED fail
- [x] Add the this new test to as a dependent test to the appropriate category so that it runs when that category runs

**Documentation tasks:**
- [x] Update [Test Categories md](https://github.com/cncf/cnf-conformance/blob/master/TEST-CATEGORIES.md) if needed 
- [x] Update [Pseudo Code md](https://github.com/cncf/cnf-conformance/blob/master/PSEUDO-CODE.md) if needed
- [x] Update [USAGE md](https://github.com/cncf/cnf-conformance/blob/master/USAGE.md) if needed 
- [x] Update [installation instructions](https://github.com/cncf/cnf-conformance#installation) if needed 

**QA tasks**

Dev Review: 
- [x] walk through A/C
- [x] do you get the expected result?
- [x] if yes, move to `Needs Peer Review` column
- [x] if no, document what additional tasks will be needed

Peer review:
- [ ] walk through A/C
- [ ] do you get the expected result?
- [ ] if yes, move to `Reviewer Approved` column
- [ ] if no, document what did not go as expected, including error messages and screenshots (if possible)

**Comment by lixuna** [comment]
### [WIP] Acceptance Criteria for peer review:
---
###  Common steps
- [ ]  Find or create a K8s cluster to use
       - [ ] Steps for creating will be in another ticket 
       - [ ] Talk with team for access to an existing cluster
- [ ] Set the KUBECONFIG environment variable for accessing the target K8s cluster
- [ ]  Pull down latest version of CNF conformance test code from `develop` branch
- [ ]  Run shard install
- [ ]  Find the names of the containers in the CNF's helm chart
- [ ] Create an environment variable called TARGET_CONTAINER with the list of container names

**Comment by lixuna** [comment]
Level of effort in pts: 0, 1, 2, 3, 5, 8, 13, 21, infinity: 5 pts
---

@wavell 8 pts
@williscool 5 pts
@lixuna 5 pts
@denverwilliams 5 pts
@taylor 5 pts
ashleigh 5 pts
nupejosh 8 pts

**Comment by lixuna** [comment]
Added new task above: 
- [ ]   If one test blows up (eg. CNF code not found for static) the suite should continue to run

**Comment by lixuna** [comment]
Added to A/C: 

Steps to test a sample CNF w/ a valid Helm chart against all tests in the test category:

- [ ]  Follow Steps to test a CNF w/ a valid Helm chart from above
- [ ]  Run crystal src/cnf-conformance.cr installability
- [ ]  I expect to see PASSED for the helm valid test

**Comment by taylor** [comment]
### Target CNF Tasks (eg. How do we use the sample CNF)

 - Check /cnfs folder for CNFs.
 - For each folder check inside for a cnf-conformance.yml. If the file is found run conformance tests for that CNF
 - Update documentation to say that each CNF should be in a subfolder of the CNF

**Comment by taylor** [comment]
@williscool please add a sample invalid CNF helm chart and test that the linter fails.  The CoreDNS working helm chart can be modified to be invalid.  See [A/C for testing.](https://github.com/cncf/cnf-conformance/issues/6#issuecomment-590999144)

**Comment by taylor** [comment]
@williscool, it looks like the setup task uses a different directory https://github.com/cncf/cnf-conformance/commit/89d81ce077881df3fa946a74fd5537837b871dc0#diff-d8bebbf3115bd02eeb3a3e284a0535f7R75

Please match the cnf-conformance.yml to the cnf directory from setup

**Comment by taylor** [comment]
@williscool Please update the CNF [README](https://github.com/cncf/cnf-conformance/blob/develop/sample-cnfs/sample-bad_helm_coredns-cnf/README.md) to match the new sample cnf name, directory, etc

**Comment by taylor** [comment]
@williscool It looks like some steps are not needed in this sample cnf including the helm chart install https://github.com/cncf/cnf-conformance/blob/develop/sample-cnfs/sample-bad_helm_coredns-cnf/README.md#core-dns-installation

Please review and remove the steps that are invalid for this sample

**Comment by taylor** [comment]
@williscool the [cnf-conformance.yml points to the coredns folder](https://github.com/cncf/cnf-conformance/blob/ae3f8da9dc2224a2ae3f5815d45b6a7d24ab60c4/sample-cnfs/sample-bad_helm_coredns-cnf/cnf-conformance.yml#L2) instead of a the ["cnfs/bad_helm_chart" folder created in setup](https://github.com/cncf/cnf-conformance/commit/89d81ce077881df3fa946a74fd5537837b871dc0#diff-d8bebbf3115bd02eeb3a3e284a0535f7R75)

**Comment by taylor** [comment]
@wharris3, please add a comment with updated A/C steps for testing _Steps to test a CNF w/ an invalid Helm chart:_

It appears a new setup command is needed for that to run. Something like

```
rosenberg% crystal src/cnf-conformance.cr bad_helm_cnf_setup
Successfully created directories for cnf-conformance
Cloning into '/home/taylor/p/w/cncf/test/cnf-conformance/cnfs/bad_helm_coredns'...
remote: Enumerating objects: 58, done.
remote: Counting objects: 100% (58/58), done.
remote: Compressing objects: 100% (39/39), done.
remote: Total 55328 (delta 35), reused 30 (delta 19), pack-reused 55270
Receiving objects: 100% (55328/55328), 94.72 MiB | 3.04 MiB/s, done.
Resolving deltas: 100% (29285/29285), done.
```

Then run the test
```
rosenberg% crystal src/cnf-conformance.cr helm_chart_valid
FAILURE: Helm Chart stable/coredns Lint Failed
```

**Comment by taylor** [comment]
@denverwilliams @wavell @williscool with the latest updates ([PR 86](https://github.com/cncf/cnf-conformance/pull/86), [PR 87](https://github.com/cncf/cnf-conformance/pull/87)) is this ready for peer review again?  If so please move to the peer review column and tag someone.

**Comment by taylor** [comment]
A/C passes for helm chart.  (PASS and FAIL scenarios)
