### ISSUE TITLE
[Feature] Silence kubectl apply commands

### ISSUE THREAD

**Issue by wavell** [cncf/cnf-conformance#601]
### [Acceptance Criteria](https://github.com/cncf/cnf-conformance/issues/601#issuecomment-789250752)

**Is your feature request related to a problem? Please describe.**
```
Error from server (AlreadyExists): error when creating .... already exists 

```
Shows when a kubectl apply is run on a manifest file and the resource already exists.
This creates output noise.

**Describe the solution you'd like**
A tool should  be created that handles kubectl apply in a silent way, with optional output being put into the logging info output

**Comment by wavell** [comment]
./cnf-conformance cnf_setup cnf-path=./sample-cnfs/sample-minimal-cnf/
#LOG_LEVEL=error ./cnf-conformance workload ~k8s_conformance

**Comment by wavell** [comment]
### Documentation is updated:

###  Common steps
- [ ]  Find or create a K8s cluster to use
   - Talk with team for access to an existing cluster
   - [Kind K8s clusters](https://github.com/cncf/cnf-conformance/blob/master/KIND-INSTALL.md) will work as well
- [ ]  Set the KUBECONFIG environment variable for accessing the target K8s cluster
- [ ]  As a developer, Pull down latest version of CNF conformance test code from {FEATURE} branch
     - [ ]  Check that {FEATURE} Branch passes all A/C 
     - [ ]  Check that {FEATURE} Branch passes tests in GitHub Actions
- [ ]  As a peer reviewer, check that PR passes in GitHub Actions
     - [ ] if yes, merge PR to master
     - [ ]  if no, make a comment and request that developer make changes to pass tests 
- [ ]   As a peer reviewer, Pull down latest version of CNF conformance test code from `master` branch
- [ ]  Run `shards install`

### Spec test should pass
- [ ]  Run `crystal spec`
- [ ]  I expect to see PASSED for the tests

### Update Prerequisite checker
- [ ] N/A

### Update example CNFs cnf-conformance.yml, if needed
- [ ] continue, If there is an update to cnf-conformance.yml
- [ ] for each CNF Example
- [ ] Update the example CNF's cnf-conformance.yml to include the new changes
- [ ] Update the example CNF's README if needed
- [ ] Test the example CNF following it's README

### Update yml validator, if needed
- [ ] Service name should not longer be required

### I would expect a CNF that has multiple services to run normally test.
- [ ]  Follow common steps above
- [ ]  Prepare the test suite to use the CNF by running: `./cnf-conformance cnf_setup cnf-path=../sample-cnfs/sample-minimal-cnf/`
- [ ]  Run  `./cnf-conformance workload`
- [ ]  I expect to see the output from the test
- [ ]  I expect to see PASSED for the test
- [ ] - [ ]  I expect to see less line noise (no `Error from server (AlreadyExists): error when creating .... already exists`) for the test

### Screenshots of all command and workload command output
- [ ] I can see a screenshot of the output

**Comment by lixuna** [comment]
@nupejosh please review the https://github.com/cncf/cnf-conformance/issues/601#issuecomment-789250752 and check the items that are working as expected during the peer review process

**Comment by agentpoyo** [comment]
![601_kubectl_output](https://user-images.githubusercontent.com/14348948/110008454-5de97980-7ce1-11eb-9ea6-44ece0bb007d.png)
