### ISSUE TITLE
[Feature] Implement scoring for SKIPPED tests

### ISSUE THREAD

**Issue by wavell** [cncf/cnf-conformance#603]
**Is your feature request related to a problem? Please describe.**
Currently the test suite shows a failure, but with zero points, for tests that are not applicable.  An example of this would be the immutable config map test where if a CNF does not use a config map, the outcome is zero points, but if the CNF uses a *immutable* config map, there are positive points. K8s secrets is another example test that should not show failure when not found.

Addresses: Usability for understanding results.

**Describe the solution you'd like**
The should another test outcome, SKIPPED, where the test outputs a Yellow message of Not Applicable and assigns zero points to the outcome of the test.

**Describe alternatives you've considered**
The alternative is the leave the test suite with the red outcome message, but assign 0 points to the outcome.

See #576

**Comment by lixuna** [comment]
@wavell @agentpoyo @taylor is this issue done?

I see it listed as a completed item in v0.10.1 https://github.com/cncf/cnf-conformance/releases/edit/v0.10.1

**Comment by thewolfpack** [comment]
It's isn't done.  That's a mistake.

**Comment by lixuna** [comment]
ok. I'll edit the release notes and remove #603.

**Comment by wavell** [comment]
### Acceptance Criteria for peer review 
--
### Documentation is updated:
- [ ] n/a

###  Common steps
- [ ]  Find or create a K8s cluster to use
   - Talk with team for access to an existing cluster
   - [Kind K8s clusters](https://github.com/cncf/cnf-conformance/blob/master/KIND-INSTALL.md) will work as well
- [ ]  Set the KUBECONFIG environment variable for accessing the target K8s cluster
- [ ]  As a developer, Pull down latest version of CNF conformance test code from {FEATURE} branch
     - [ ]  Check that {FEATURE} Branch passes all A/C 
     - [ ]  Check that {FEATURE} Branch passes tests in GitHub Actions
- [ ]  As a peer reviewer, check that PR passes in GitHub Actions
     - [ ] if yes, merge PR to master
     - [ ]  if no, make a comment and request that developer make changes to pass tests 
- [ ]   As a peer reviewer, Pull down latest version of CNF conformance test code from `master` branch
- [ ]  Run `shards install`

### Spec test should pass
- [ ]  Run `crystal spec`
- [ ]  I expect to see PASSED for the tests

### Update Prerequisite checker
- [ ] N/A

### Update yml validator, if needed
- [ ] N/A

### I would expect that the results.yml to be able to be updated with a skipped task 
- [ ]  Follow common steps above
- [ ]  Follow the Setup cluster on non-native ports steps
- [ ]  Prepare the test suite to use the CNF by running: `crystal spec --tag "upsert_skipped_task" -v`
- [ ]  I expect to see no exception errors from the test
- [ ]  I expect to see PASSED for the test

### Screenshots of all command and workload command output
- [ ] I can see a screenshot of the passing spec

**Comment by williscool** [comment]
@wavell is this ticket just to make skips possible not to also implement them in places?

by that I mean would for instance implementing a skip when you detect that there are no config maps in a cnf is a separate ticket?

if so it looks good to me.

**Comment by lixuna** [comment]
@williscool please check the checkboxes that you have verified in the Acceptance Criteria (https://github.com/cncf/cnf-conformance/issues/603#issuecomment-797061140)

**Comment by agentpoyo** [comment]
LGTM

![image](https://user-images.githubusercontent.com/14348948/113187752-d4b15e00-921e-11eb-9df8-ca4ac10091f1.png)
