### ISSUE TITLE
[Feature] Minimal cnf-conformance.yml automated spec test

### ISSUE THREAD

**Issue by wavell** [cncf/cnf-conformance#608]
**Is your feature request related to a problem? Please describe.**
cnf-conformance.yml has many options, and it would be good to test the minimum required options from an end user perspective

**Describe the solution you'd like**
There should be a test that installs a cnf with the minimum required configuration in the cnf-conformance.yml file

**Describe alternatives you've considered**
Relying on the yml validator only

**Comment by agentpoyo** [comment]
### Acceptance Criteria for peer review (based on https://github.com/cncf/cnf-conformance/issues/82)
--
### Documentation is updated:
- [ ] cnf-conformance.yml documentation update 

###  Common steps
- [ ]  Find or create a K8s cluster to use
   - Talk with team for access to an existing cluster
   - [Kind K8s clusters](https://github.com/cncf/cnf-conformance/blob/master/KIND-INSTALL.md) will work as well
- [ ]  Set the KUBECONFIG environment variable for accessing the target K8s cluster
- [ ]  As a developer, Pull down latest version of CNF conformance test code from {FEATURE} branch
     - [ ]  Check that {FEATURE} Branch passes all A/C 
     - [ ]  Check that {FEATURE} Branch passes tests in GitHub Actions
- [ ]  As a peer reviewer, check that PR passes in GitHub Actions
     - [ ] if yes, merge PR to master
     - [ ]  if no, make a comment and request that developer make changes to pass tests 
- [ ]   As a peer reviewer, Pull down latest version of CNF conformance test code from `master` branch
- [ ]  Run `shards install`

### Spec test should pass
- [ ]  Run `crystal spec`
- [ ]  I expect to see PASSED for the tests

### Update Prerequisite checker
- [ ] N/A

### Update yml validator, if needed
- [ ] N/A

### I would expect that the cnf-conformance.yml to be able to handle a minimal cnf-conformance.yml
- [ ]  Follow common steps above
- [ ]  Prepare the test suite to use the CNF by running: `./cnf-conformance cnf_setup cnf-config=./sample-cnfs/sample-minimal-cnf/cnf-conformance.yml'
- [ ]  Run  `./cnf-conformance workload`
- [ ]  I expect to see the output from the test
- [ ]  I expect to see no exception errors from the test
- [ ]  I expect to see PASSED for the test

### Screenshots of all command and workload command output
- [ ] I can see a screenshot of `sample_minimal-cnf` workload

**Comment by agentpoyo** [comment]
Screenshot of cnf_setup with minimal cnf-conformance.yml config file:

![608_minimal_cnf-config](https://user-images.githubusercontent.com/14348948/109900374-e4a84300-7c5c-11eb-8018-ce3cf385436d.png)

**Comment by lixuna** [comment]
Please add level of effort in pts (scale: 0,1,2,3,5,8,13,21)

@wavell
@williscool
@agentpoyo
@denverwilliams

**Comment by agentpoyo** [comment]
@lixuna 3pts
