### ISSUE TITLE
[BUG] Chaos mesh status attribute now missing

### ISSUE THREAD

**Issue by wavell** [cncf/cnf-conformance#610]
**Describe the bug**

It looks like the 'status' flag is now missing on the litmus config map, which is causing a timeout/error

See
https://github.com/cncf/cnf-conformance/runs/1887556441?check_suite_focus=true#step:7:330

**To Reproduce**
1. crystal spec spec/cnf_conformance_all/cnf_conformance_network_chaos_spec.cr:16 

**Expected behavior**
Some status should be present in the response

**Screenshots**
![image](https://user-images.githubusercontent.com/29548/107776140-d1155680-6d06-11eb-9165-f51e4ccd6f6b.png)

**Comment by lixuna** [comment]
Please add level of effort in pts (scale: 0,1,2,3,5,8,13,21)

@wavell
@williscool
@agentpoyo
@denverwilliams

**Comment by agentpoyo** [comment]
5pts

**Comment by agentpoyo** [comment]
This test was removed and replaced with Litmus.
