### ISSUE TITLE
[BUG] ip_addresses test fails but does not report the reason why it failed

### ISSUE THREAD

**Issue by sishbi** [cncf/cnf-conformance#615]
**Describe the bug**
The ip_addresses test should look for "any (non-declarative) hardcoded IP addresses or subnet masks"

**To Reproduce**
1. Run cnf-conformance ip_addresses
2. test reports: FAILURE: IP addresses found
3. test output does not show the reason why the test failed

**Expected behavior**
Test should pass or give a clear explanation for why it failed.

**Screenshots**
See log of test run with DEBUG enabled:
$ cnf-conformance -lDEBUG ip_addresses
I, [2021-02-18 15:14:18 +00:00 #7672]  INFO -- cnf-conformance: Results file
I, [2021-02-18 15:14:18 +00:00 #7672]  INFO -- cnf-conformance: file exists?:false
I, [2021-02-18 15:14:18 +00:00 #7672]  INFO -- cnf-conformance: task_runner args: #<Sam::Args:0x7fccef267460 @arr=[], @named_args={}>
I, [2021-02-18 15:14:18 +00:00 #7672]  INFO -- cnf-conformance: check_cnf_config args: #<Sam::Args:0x7fccef267460 @arr=[], @named_args={}>
I, [2021-02-18 15:14:18 +00:00 #7672]  INFO -- cnf-conformance: check_cnf_config cnf: 
I, [2021-02-18 15:14:18 +00:00 #7672]  INFO -- cnf-conformance: cnf_config_list
I, [2021-02-18 15:14:18 +00:00 #7672]  INFO -- cnf-conformance: find: find cnfs/* -name cnf-conformance.yml
I, [2021-02-18 15:14:18 +00:00 #7672]  INFO -- cnf-conformance: find response: ["cnfs/chf/cnf-conformance.yml"]
I, [2021-02-18 15:14:18 +00:00 #7672]  INFO -- cnf-conformance: cnf_config_list
I, [2021-02-18 15:14:18 +00:00 #7672]  INFO -- cnf-conformance: find: find cnfs/* -name cnf-conformance.yml
I, [2021-02-18 15:14:18 +00:00 #7672]  INFO -- cnf-conformance: find response: ["cnfs/chf/cnf-conformance.yml"]
D, [2021-02-18 15:14:18 +00:00 #7672] DEBUG -- cnf-conformance: single_task_runner args: #<Sam::Args:0x7fccef2670a0 @arr=[], @named_args={"cnf-config" => "cnfs/chf/cnf-conformance.yml"}>
D, [2021-02-18 15:14:18 +00:00 #7672] DEBUG -- cnf-conformance: parse_config_yml config_yml_path: cnfs/chf/cnf-conformance.yml
I, [2021-02-18 15:14:18 +00:00 #7672]  INFO -- cnf-conformance: ensure_cnf_conformance_yml_path
I, [2021-02-18 15:14:18 +00:00 #7672]  INFO -- cnf-conformance: cnf_installation_method
I, [2021-02-18 15:14:18 +00:00 #7672]  INFO -- cnf-conformance: cnf_installation_method config: #<Totem::Config:0x7fccef296dc0>
I, [2021-02-18 15:14:18 +00:00 #7672]  INFO -- cnf-conformance: cnf_installation_method config: cnfs/chf/cnf-conformance.yml
D, [2021-02-18 15:14:18 +00:00 #7672] DEBUG -- cnf-conformance: install type count install_type: helm_chart
D, [2021-02-18 15:14:18 +00:00 #7672] DEBUG -- cnf-conformance: install_type: helm_directory not found in cnfs/chf/cnf-conformance.yml
D, [2021-02-18 15:14:18 +00:00 #7672] DEBUG -- cnf-conformance: install_type: manifest_directory not found in cnfs/chf/cnf-conformance.yml
D, [2021-02-18 15:14:18 +00:00 #7672] DEBUG -- cnf-conformance: installation_type_count: 1
I, [2021-02-18 15:14:18 +00:00 #7672]  INFO -- cnf-conformance: generate_and_set_release_name
I, [2021-02-18 15:14:18 +00:00 #7672]  INFO -- cnf-conformance: ensure_cnf_conformance_yml_path
D, [2021-02-18 15:14:18 +00:00 #7672] DEBUG -- cnf-conformance: predefined_release_name: chf
I, [2021-02-18 15:14:18 +00:00 #7672]  INFO -- cnf-conformance: cnf_destination_dir config_file: cnfs/chf/cnf-conformance.yml
I, [2021-02-18 15:14:18 +00:00 #7672]  INFO -- cnf-conformance: cnf_destination_dir parsed_config_file config: #<Totem::Config:0x7fccef296c80>
I, [2021-02-18 15:14:18 +00:00 #7672]  INFO -- cnf-conformance: release_name: chf
I, [2021-02-18 15:14:18 +00:00 #7672]  INFO -- cnf-conformance: cnf destination dir: /home/sbillingsley/cnf/cnfs/chf
I, [2021-02-18 15:14:18 +00:00 #7672]  INFO -- cnf-conformance: ensure_cnf_conformance_yml_dir
I, [2021-02-18 15:14:18 +00:00 #7672]  INFO -- cnf-conformance: ip_addresses args #<Sam::Args:0x7fccef2670a0 @arr=[], @named_args={"cnf-config" => "cnfs/chf/cnf-conformance.yml"}>
I, [2021-02-18 15:14:18 +00:00 #7672]  INFO -- cnf-conformance: current directory: /home/sbillingsley/cnf/cnfs/chf/exported_chart
✖️  FAILURE: IP addresses found
D, [2021-02-18 15:14:18 +00:00 #7672] DEBUG -- cnf-conformance: results yaml: {"name" => "cnf conformance", "status" => nil, "points" => nil, "exit_code" => 0, "items" => [{"name" => "ip_addresses", "status" => "failed", "points" => -1}]}

**Device (please complete the following information):**
 - OS Linux
 - Distro CentOS
 - Version 7.9
 - Architecture x86_64

**Additional context**

**Comment by sishbi** [comment]
Found the cause of the failure by running the following command:
`cnf-conformance --loglevel=DEBUG  ip_addresses verbose`

This now outputs the following INFO:
`
I, [2021-02-18 16:10:56 +00:00 #3787]  INFO -- cnf-conformance-verbose: templates/NOTES.txt:  echo "Visit http://127.0.0.1:9098 to use your application"
`
Which is a comment in the NOTES.txt - it would have been helpful if this info was printed without requiring 'verbose' argument (also using 'verbose' as an argument is not immediately obvious)

**Comment by wavell** [comment]
Acceptance criteria
- [ ] `./cnf-conformance cnf_setup cnf-path=./sample-cnfs/sample_coredns_hardcoded_ips/ `
- [ ] `cnf-conformance ip_addresses`
- [ ] I should see a message that shows the file that contains the ip address failure

**Comment by agentpoyo** [comment]
![image](https://user-images.githubusercontent.com/14348948/114632730-e2d29600-9c84-11eb-9507-0cf62973110b.png)

**Comment by lixuna** [comment]
@wavell @agentpoyo @denverwilliams what was the level of effort in pts to make this change? (0,1,2,3,5,8,13,21)

**Comment by agentpoyo** [comment]
3 pts
