### ISSUE TITLE
[Feature] Support non standard Image URL ports

### ISSUE THREAD

**Issue by agentpoyo** [cncf/cnf-conformance#619]
### [Acceptance Criteria](https://github.com/cncf/cnf-conformance/issues/619#issuecomment-783724053)

**Is your feature request related to a problem? Please describe.**
Yes, test suite doesn't support non default image url port.

Example error when specifying an image using port 5000:

```
"image": "master:5000/image:tag"
the error:
"no image found for tag: 5000/image"
```

**Describe the solution you'd like**
Test Suite should be able to handle ports that are not the default port.

**Describe alternatives you've considered**
No other alternatives other than changing image url to use standard port.

**Comment by wavell** [comment]
All docker images can have from one to three segments.  The docker images that have multiple segments are separated by a slash.

## One segment
#### Official docker image string
e.g. `busybox`

If the docker image is only one segment,`docker.io` is used for the registry, the whole segment is used image name, and `latest` as the tag

## Two segments
#### Org/Image combination
e.g. `coredns/coredns`, 
`docker.io/busybox`,
`myhostname:5000/myimagename:mytag`

If the docker image has two segments, the first segment needs to be parsed to determine if it is an org name or a registry.

If the first segment has a period `.` in it, then the segment is a registry fully qualified domain name.

If the first segment has colon in it `:` everything after the colon is a port number

**If the first segment does not have a period `.` in it, but it does have a colon in it, then the segment is a host name**

If the first segment does **not** have a period or colon in it, then the segment is an org name.

If the first segment has colon in it `:` everything after the colon is a port number

Everthing in the second segment is an image or image:tag combination.

## Three segments
#### (Fully qualified) registry name with optional port /Org/image combination

e.g. `docker.io/coredns/coredns`
`docker.io:80/coredns/coredns`, `docker.io:80/coredns/coredns:latest`

If the docker image has three segments, the first segment is a fully qualified registry name.

If the first segment has a period `.` in it, then the segment is a fully qualified domain name. 

If the first segment has colon in it `:` everything after the colon is a port number

If the second segment has a period `.` in it, then the segment is a fully qualified domain name. 

If the second segment does **not** have a period in it, then the segment is an org name.

Everthing in the third segment is an image or image:tag combination.

**Comment by wavell** [comment]
wil 5
drew 5
watson 5
denver 5

**Comment by wavell** [comment]
### Acceptance Criteria for peer review (based on https://github.com/cncf/cnf-conformance/issues/82)
--
### Documentation is updated:
- [ ] cnf-conformance.yml documentation update 

###  Common steps
- [ ]  Find or create a K8s cluster to use
   - Talk with team for access to an existing cluster
   - [Kind K8s clusters](https://github.com/cncf/cnf-conformance/blob/master/KIND-INSTALL.md) will work as well
- [ ]  Set the KUBECONFIG environment variable for accessing the target K8s cluster
- [ ]  As a developer, Pull down latest version of CNF conformance test code from {FEATURE} branch
     - [ ]  Check that {FEATURE} Branch passes all A/C 
     - [ ]  Check that {FEATURE} Branch passes tests in GitHub Actions
- [ ]  As a peer reviewer, check that PR passes in GitHub Actions
     - [ ] if yes, merge PR to master
     - [ ]  if no, make a comment and request that developer make changes to pass tests 
- [ ]   As a peer reviewer, Pull down latest version of CNF conformance test code from `master` branch
- [ ]  Run `shards install`

### Spec test should pass
- [ ]  Run `crystal spec`
- [ ]  I expect to see PASSED for the tests

### Update Prerequisite checker
- [ ] N/A

### Update yml validator, if needed
- [ ] N/A

### I would expect that the cnf-conformance.yml to be able to handle a cnf that has a port (e.g. `mydockerregistry.io:8080/coredns/coredns:latest`)
- [x]  Follow common steps above
- [x]  Prepare the test suite to use the CNF by running: `./cnf-conformance cnf_setup cnf-config=./sample-cnfs/sample_port_registry/cnf-conformance.yml`
- [x]  Run  `./cnf-conformance workload`
- [x]  I expect to see the output from the test
- [x]  I expect to see no exception errors from the test
- [x]  I expect to see PASSED for the test

### Screenshots of all command and workload command output
- [x] I can see a screenshot of `sample_immutable_configmap_all` test for immutable_configmap for A/C above
- [ ] I can see a screenshot of `sample_immutable_configmap_some` test for immutable_configmap for A/C above
- [x]  I can see a screenshot of `immutable_configmap` for coredns for A/C above

**Comment by agentpoyo** [comment]
https://docs.docker.com/engine/reference/commandline/pull/#pull-from-a-different-registry  Docker mentions when port 5000 is used which is local registry pulls.

**Comment by wavell** [comment]
https://docs.docker.com/registry/insecure/ there is a need to call the local registration with http instead of https

**Comment by agentpoyo** [comment]
Added A/C to setup kind cluster using non-native port:

[ ] kubectl create -f tools/registry/manifest.yml
[ ] kubectl create -f tools/dockerd/manifest.yml
[ ] kubectl exec dockerd -ti -- docker pull coredns/coredns:1.6.7
[ ] kubectl exec dockerd -ti -- docker tag coredns/coredns:1.6.7 registry:5000/coredns:1.6.7
[ ] kubectl exec dockerd -ti -- docker push registry:5000/coredns:1.6.7

**Comment by agentpoyo** [comment]
![619_non-native-port](https://user-images.githubusercontent.com/14348948/109869956-228e7280-7c2f-11eb-86b7-9d7fac6a7350.png)

**Comment by sishbi** [comment]
Hi there @wavell @taylor @agentpoyo I get the following events when using this version:
```
Pulled  Successfully pulled image "localhost:32000/sba-5gc-networkfunctions-leader-sidecar:5220-SNAPSHOT"
Pulling Pulling image "localhost:5220-SNAPSHOT-2"
BackOff Back-off pulling image "localhost:5220-SNAPSHOT-2"
```
The first event shows the original image including the full path and tag.  The second event shows the invalid image name.
As you can see the image name is invalid as it is missing ':32000/sba-5gc-networkfunctions-leader-sidecar' 

I pulled the '#619_registry_port' branch that was merged into master into my local area before running this test.
I can see 'sample_local_registry' in my local area, so I am pretty sure I have the changes pulled correctly.
In fact I merged in origin master today and as this was merged 6 days ago I would already have the changes from that branch in my local area.
I will start work on creating a new PR for this which works for me.  Maybe I should reopen #635 to cover the changes.

**Comment by agentpoyo** [comment]
This inadvertently tested the non-native port as well:

https://github.com/cncf/cnf-conformance/issues/635#issuecomment-799699979

You can see in the debug output the proper image pulled via port 5000 and the name with tag.

**Comment by agentpoyo** [comment]
![rollback_635_screenshot_debug](https://user-images.githubusercontent.com/14348948/111213388-b56bcd00-859e-11eb-9a67-ff9d8cb37c94.png)
