### ISSUE TITLE
[Feature] white_list_helm_chart_container_names in cnf-conformance.yml should be optional

### ISSUE THREAD

**Issue by wavell** [cncf/cnf-conformance#622]
**Is your feature request related to a problem? Please describe.**
If white_list_helm_chart_container_names is not found in in cnf-conformance.yml, the application errors

**Describe the solution you'd like**
white_list_helm_chart_container_names in cnf-conformance.yml should be optional

**Comment by lixuna** [comment]
Noting that the allowed container names code was written in early 2020, I'd like to suggest it be renamed to `allowlist_helm_chart_container_names` to follow recommendations from https://inclusivenaming.org/language/word-list/

**Comment by lixuna** [comment]
I created a followup issue to rename this https://github.com/cncf/cnf-conformance/issues/631

**Comment by agentpoyo** [comment]
The Minimal cnf-conformance.yml automated spec test https://github.com/cncf/cnf-conformance/issues/608 satisfies the A/C as it was run without `white_list_helm_chart_container_names` requirement.

**Comment by agentpoyo** [comment]
This screenshot shows the minimal config being configured without `white_list_helm_chart_container_names`

![608_minimal_cnf-config](https://user-images.githubusercontent.com/14348948/109903390-571b2200-7c61-11eb-8d69-82872610ea67.png)

**Comment by lixuna** [comment]
Please add level of effort in pts (scale: 0,1,2,3,5,8,13,21)

@wavell
@williscool
@agentpoyo
@denverwilliams

**Comment by agentpoyo** [comment]
@lixuna 3pts
