### ISSUE TITLE
[Feature] Rename `master` branch to `main` for GitHub repo

### ISSUE THREAD

**Issue by lixuna** [cncf/cnf-conformance#626]
**Is your feature request related to a problem? Please describe.**

**From https://inclusivenaming.org/language/word-list/**
In computing, A “master” often refers to the original or main version of an entity.

- main
- original
- source
- control plane

Reasoning:

While master in and of itself is potentially neutral, the propensity in which it is associated with the term slave in computing makes master on its own guilty by association. Though it is used as a standalone, it’s impossible to remove the association with command and control entirely, and thus we recommend moving away from even singular use.

Recommendation: Adopt immediately.

**Describe the solution you'd like**
https://github.com/github/renaming#rename-existing

**Describe alternatives you've considered**
- N/A 

**Additional context**
https://inclusivenaming.org/language/word-list/

**Comment by agentpoyo** [comment]
LGTM :+1: 

We successfully created a new tag v0.10.4 from `main` branch and passed github actions: https://github.com/cncf/cnf-conformance/actions/runs/730983043

![image](https://user-images.githubusercontent.com/14348948/114101097-dd430d80-988a-11eb-9753-30ff546737a0.png)

**Comment by lixuna** [comment]
@agentpoyo @denverwilliams what was the level of effort in pts to make this change? (0,1,2,3,5,8,13,21)

**Comment by agentpoyo** [comment]
5pts
