### ISSUE TITLE
[BUG] rollback, rolling_version_change tests do not handle images that use a local registry with port

### ISSUE THREAD

**Issue by sishbi** [cncf/cnf-conformance#635]
**Describe the bug**
When running the rollback or rolling_version_change tests the image name is being split at the first colon but this separates the host and port for when a local registry is used, such as 'hostname:port'
where as the tag to be removed is the value after the last colon, such as: image_name:tag_name.
This causes the container to get an invalid tag and then the pull from the registry fails with ImagePullError and the test fails.

**To Reproduce**
1. Run rollback or rolling_version_change test
2. Observe that the pod/container has an ImagePullError or ImagePullBackoff status

**Expected behavior**
The image name and image tag should be identified correctly and only the image tag should be replaced during the test.

**Screenshots**
Here is a log extract:
D, [2021-03-04 17:11:26 +00:00 #548998] DEBUG -- cnf-conformance-verbose: image_name: chf
D, [2021-03-04 17:11:26 +00:00 #548998] DEBUG -- cnf-conformance-verbose: rollback: setting new version
D, [2021-03-04 17:11:26 +00:00 #548998] DEBUG -- cnf-conformance: set image: deployment.apps/chf-bridge-cnf image updated

D, [2021-03-04 17:11:26 +00:00 #548998] DEBUG -- cnf-conformance-verbose: change successful? true
D, [2021-03-04 17:11:26 +00:00 #548998] DEBUG -- cnf-conformance-verbose: rollback: checking status new version
error: timed out waiting for the condition
D, [2021-03-04 17:11:56 +00:00 #548998] DEBUG -- cnf-conformance: Waiting for deployment "chf-bridge-cnf" rollout to finish: 1 old replicas are pending termination...

D, [2021-03-04 17:11:56 +00:00 #548998] DEBUG -- cnf-conformance: rollout? false
Rolling update failed on resource: chf-bridge-cnf and container: chf
D, [2021-03-04 17:11:56 +00:00 #548998] DEBUG -- cnf-conformance-verbose: rollback: rolling back to old version
D, [2021-03-04 17:11:56 +00:00 #548998] DEBUG -- cnf-conformance: deployment.apps/chf-bridge-cnf rolled back

The following events are observed:
│   Warning  InspectFailed  0s (x5 over 29s)  kubelet, sbillingsley-k8s  Failed to apply default image tag "localhost:": couldn't parse image reference "localhost:": invalid reference format              │

**Device (please complete the following information):**
 - OS Linux
 - Distro Ubuntu
 - Version 20.04

**Additional context**
We use a local registry within kubernetes which has the following address: 'localhost:32000' therefore an image has the following name: 'localhost:32000/sba-5gc-networkfunctions-chf-bridge:5220-SNAPSHOT'

**Comment by taylor** [comment]
Possibly related to https://github.com/cncf/cnf-conformance/issues/619

cc: @wavell @denverwilliams

**Comment by sishbi** [comment]
@taylor Looking at the PR on that bug it does look the same, this can be closed a duplicate of bug, I can verify the PR in my local environment if that helps...

**Comment by sishbi** [comment]
Duplicate of #619

**Comment by sishbi** [comment]
@taylor Please can this issue be reopened, I have created a PR for it (#642)

**Comment by wavell** [comment]
We are going to write a spec that uses a local registry with a port in order to help use make sure that these tests are working as intended. See: https://github.com/cncf/cnf-conformance/blob/e66509362fc5edd41cb569b41fcaf4b55240ed2a/spec/workload/microservice_spec.cr#L74

**Comment by wavell** [comment]
### Acceptance Criteria for peer review (based on https://github.com/cncf/cnf-conformance/issues/82)
--
### Documentation is updated:
- [ ] n/a

###  Common steps
- [ ]  Find or create a K8s cluster to use
   - Talk with team for access to an existing cluster
   - [Kind K8s clusters](https://github.com/cncf/cnf-conformance/blob/master/KIND-INSTALL.md) will work as well
- [ ]  Set the KUBECONFIG environment variable for accessing the target K8s cluster
- [ ]  As a developer, Pull down latest version of CNF conformance test code from {FEATURE} branch
     - [ ]  Check that {FEATURE} Branch passes all A/C 
     - [ ]  Check that {FEATURE} Branch passes tests in GitHub Actions
- [ ]  As a peer reviewer, check that PR passes in GitHub Actions
     - [ ] if yes, merge PR to master
     - [ ]  if no, make a comment and request that developer make changes to pass tests 
- [ ]   As a peer reviewer, Pull down latest version of CNF conformance test code from `master` branch
- [ ]  Run `shards install`

### Spec test should pass
- [ ]  Run `crystal spec`
- [ ]  I expect to see PASSED for the tests

### Update Prerequisite checker
- [ ] N/A

### Update yml validator, if needed
- [ ] N/A

### Setup cluster on non-native ports
- [ ] kubectl create -f tools/registry/manifest.yml
- [ ] kubectl create -f tools/dockerd/manifest.yml
- [ ] kubectl exec dockerd -ti -- docker pull coredns/coredns:1.6.7
- [ ] kubectl exec dockerd -ti -- docker tag coredns/coredns:1.6.7 registry:5000/coredns:1.6.7
- [ ] kubectl exec dockerd -ti -- docker push registry:5000/coredns:1.6.7
- [ ] kubectl exec dockerd -ti -- docker pull coredns/coredns:1.8.0
- [ ] kubectl exec dockerd -ti -- docker tag coredns/coredns:1.8.0 registry:5000/coredns:1.8.0
- [ ] kubectl exec dockerd -ti -- docker push registry:5000/coredns:1.8.0

### I would expect that the cnf-conformance.yml to be able to handle a cnf that has a port (e.g. `mydockerregistry.io:8080/coredns/coredns:1.8.0`)
- [ ]  Follow common steps above
- [ ]  Follow the Setup cluster on non-native ports steps
- [ ]  Prepare the test suite to use the CNF by running: `./cnf-conformance cnf_setup cnf-config=./sample-cnfs/sample_local_registry/cnf-conformance.yml`
- [ ]  Run  `./cnf-conformance rolling_version_change`
- [ ]  I expect to see the output from the test
- [ ]  I expect to see no exception errors from the test
- [ ]  I expect to see PASSED for the test

### Screenshots of all command and workload command output
- [ ] I can see a screenshot of `rolling_version_change`

**Comment by agentpoyo** [comment]
![rollback_635_screenshot](https://user-images.githubusercontent.com/14348948/111211349-4c835580-859c-11eb-8de1-06e5c591d93c.png)

![rollback_635_screenshot_debug](https://user-images.githubusercontent.com/14348948/111211360-4f7e4600-859c-11eb-8b6b-150bd5daa487.png)
