### ISSUE TITLE
[BUG] pod_network_latency seems to run in infinite loop during the workload test; interrupt to end test is required.

### ISSUE THREAD

**Issue by agentpoyo** [cncf/cnf-conformance#636]
**Describe the bug**
Running `workload` runs until the pod_network_latency test runs but never seems to complete.

**To Reproduce**
1. Run cnf_setup against sample or example cnf, e.g.:
    `./cnf-conformance cnf_setup cnf-path=./sample-cnfs/sample-minimal-cnf/`

**Expected behavior**
The pod_network_latency test should eventually complete or have a set timeout and the test suite should finish with final results.

**Screenshots**

![pod_latency_infinite_error](https://user-images.githubusercontent.com/14348948/110009767-12d06600-7ce3-11eb-8d27-1c9015839c9b.png)

**Device (please complete the following information):**
 - OS Linux
 - Distro Ubuntu
 - Version 18.04
 - Architecture x86

---

NOTE: you can enable higher logging level output via the command line or env var. to help with debugging

```
# cmd line
./cnf-conformance -l debug test

# make sure to use -- if running from source
crystal src/cnf-conformance.cr -- -l debug test 

# env var
LOGLEVEL=DEBUG ./cnf-conformance test
```

Also setting the verbose option for many tasks will add extra output to help with debugging

```
crystal src/cnf-conformance.cr test_name verbose
```

Check [usage documentation](https://github.com/cncf/cnf-conformance/blob/master/USAGE.md) for more info about invoking commands and loggin

**Comment by agentpoyo** [comment]
![bug_636_pod_network](https://user-images.githubusercontent.com/14348948/110162411-52b34e00-7db4-11eb-8760-702104d7968c.png)

**Comment by agentpoyo** [comment]
LGTM :+1:

**Comment by lixuna** [comment]
Please add level of effort in pts (scale: 0,1,2,3,5,8,13,21)

@wavell
@agentpoyo
@denverwilliams

**Comment by agentpoyo** [comment]
@lixuna 5pts
