### ISSUE TITLE
[Integration] implement/automated integration tests

### ISSUE THREAD

**Issue by lixuna** [cncf/cnf-conformance#64]
- [x] Choose automated test framework (eg. Crystal Spec)
- [x] Add base framework including test setup code (eg. before_all)
- [x] Add coverage for 1 or more tests

**Comment by wavell** [comment]
### Acceptance Criteria for peer review:
---
###  Common steps
- [ ]  Find or create a K8s cluster to use
       - [ ] Steps for creating will be in another ticket 
       - [ ] Talk with team for access to an existing cluster
- [ ] Set the KUBECONFIG environment variable for accessing the target K8s cluster
- [ ]  Pull down latest version of CNF conformance test code from `develop` branch
- [ ]  Run shard install

**Note: Running the setup or clean tasks for the automated tests is not mandatory (but doesn't hurt)**
### Run the conformance automated tests:
```
crystal spec
```
- [ ] You should see all tests passing
```
Finished in 2:11 minutes
2 examples, 0 failures, 0 errors, 0 pending
```

**Comment by taylor** [comment]
A/C passed on `develop`  => https://github.com/cncf/cnf-conformance/issues/64#issuecomment-592767947

**Comment by lixuna** [comment]
Note: spec hung with zero output until cleanup and setup was run manually. After manually running cleanup and setup, spec worked as expected.

Closing issue, reviewed in #76
