### ISSUE TITLE
[Feature] Speed up the test suite

### ISSUE THREAD

**Issue by wavell** [cncf/cnf-conformance#640]
**Is your feature request related to a problem? Please describe.**
The test suite (as of 3-4-2021) is taking around 15-20 minutes .

**Describe the solution you'd like**
Speed up the test suite by breaking up some of the tests so that they run concurrently

**Comment by agentpoyo** [comment]
LGTM, GH Action builds are now between 11-14 minutes.

**Comment by lixuna** [comment]
Estimate in points? (ex 0,1,2,3,5,8,13,21)

@wavell @denverwilliams @agentpoyo

**Comment by williscool** [comment]
5 pt

**Comment by agentpoyo** [comment]
I'm torn between 5 pts and 8 pts, it was a couple days and tedious.
