### ISSUE TITLE
[BUG] reasonable_image_size test should not fail if dockerd is not installed or if docker command fails

### ISSUE THREAD

**Issue by sishbi** [cncf/cnf-conformance#645]
### [Acceptance criteria](https://github.com/cncf/cnf-conformance/issues/645#issuecomment-796101510)

**Describe the bug**
The reasonable_image_size test attempts to install dockerd into the cluster as a pod, if this fails (such as if dockerd manifest is not present in 'tools' directory then overall test also fails.  Secondly, if the dockerd pod IS installed then if the dockerd command fails then the reasonable_image_size test fails.

**To Reproduce**
1. Install a CNF
2. Run test: reasonable_image_size
3. If dockerd is installed but the docker commands fail then the test also fails
4. If dockerd is not installed and cannot be installed because 'tools/dockerd/manifest.yml' does not exist then the test also fails.

**Expected behavior**
The test should be ignored if dockerd is not installed or if dockerd cannot run commands.

**Screenshots**
Log extract:
```
D, [2021-03-10 11:26:06 +00:00 #385748] DEBUG -- cnf-conformance: kubectl get kind: Secret resource name: chf-charging-bridge-docker-registry-creds
Error from server (NotFound): secrets "chf-charging-bridge-docker-registry-creds" not found
D, [2021-03-10 11:26:06 +00:00 #385748] DEBUG -- cnf-conformance: kubectl get resource: 
str_auths: {"auths":{}}
I, [2021-03-10 11:26:06 +00:00 #385748]  INFO -- cnf-conformance: KubectlClient.exec command: dockerd -ti -- mkdir -p /root/.docker/
I, [2021-03-10 11:26:07 +00:00 #385748]  INFO -- cnf-conformance: KubectlClient.exec output: 
I, [2021-03-10 11:26:07 +00:00 #385748]  INFO -- cnf-conformance: KubectlClient.exec stderr: Unable to use a TTY - input is not a terminal or the right kind of file

I, [2021-03-10 11:26:07 +00:00 #385748]  INFO -- cnf-conformance: KubectlClient.cp command: cnfs/cnf//config.json default/dockerd:/root/.docker/config.json
I, [2021-03-10 11:26:07 +00:00 #385748]  INFO -- cnf-conformance: KubectlClient.cp output: 
I, [2021-03-10 11:26:07 +00:00 #385748]  INFO -- cnf-conformance: KubectlClient.cp stderr: 
I, [2021-03-10 11:26:07 +00:00 #385748]  INFO -- cnf-conformance: KubectlClient.exec command: dockerd -ti -- docker pull localhost:32000/diameter-proxy:5220-SNAPSHOT
I, [2021-03-10 11:26:07 +00:00 #385748]  INFO -- cnf-conformance: KubectlClient.exec output: 
I, [2021-03-10 11:26:07 +00:00 #385748]  INFO -- cnf-conformance: KubectlClient.exec stderr: Unable to use a TTY - input is not a terminal or the right kind of file
Error response from daemon: Get http://localhost:32000/v2/: dial tcp [::1]:32000: connect: connection refused
command terminated with exit code 1

I, [2021-03-10 11:26:07 +00:00 #385748]  INFO -- cnf-conformance: KubectlClient.exec command: dockerd -ti -- docker save localhost:32000/diameter-proxy:5220-SNAPSHOT -o /tmp/image.tar
I, [2021-03-10 11:26:07 +00:00 #385748]  INFO -- cnf-conformance: KubectlClient.exec output: 
I, [2021-03-10 11:26:07 +00:00 #385748]  INFO -- cnf-conformance: KubectlClient.exec stderr: Unable to use a TTY - input is not a terminal or the right kind of file
Error response from daemon: reference does not exist
command terminated with exit code 1

I, [2021-03-10 11:26:07 +00:00 #385748]  INFO -- cnf-conformance: KubectlClient.exec command: dockerd -ti -- gzip -f /tmp/image.tar
I, [2021-03-10 11:26:07 +00:00 #385748]  INFO -- cnf-conformance: KubectlClient.exec output: 
I, [2021-03-10 11:26:07 +00:00 #385748]  INFO -- cnf-conformance: KubectlClient.exec stderr: Unable to use a TTY - input is not a terminal or the right kind of file
gzip: /tmp/image.tar: No such file or directory
command terminated with exit code 1

I, [2021-03-10 11:26:07 +00:00 #385748]  INFO -- cnf-conformance: KubectlClient.exec command: dockerd -ti -- wc -c /tmp/image.tar.gz | awk '{print$1}'
I, [2021-03-10 11:26:08 +00:00 #385748]  INFO -- cnf-conformance: KubectlClient.exec output: 
I, [2021-03-10 11:26:08 +00:00 #385748]  INFO -- cnf-conformance: KubectlClient.exec stderr: Unable to use a TTY - input is not a terminal or the right kind of file
wc: /tmp/image.tar.gz: No such file or directory
command terminated with exit code 1

I, [2021-03-10 11:26:08 +00:00 #385748]  INFO -- cnf-conformance: compressed_size: localhost:32000/diameter-proxy:5220-SNAPSHOT = ''
E, [2021-03-10 11:26:08 +00:00 #385748] ERROR -- cnf-conformance: invalid compressed_size: localhost:32000/diameter-proxy:5220-SNAPSHOT = '', Invalid Int64: 
D, [2021-03-10 11:26:08 +00:00 #385748] DEBUG -- cnf-conformance: yield resp: false
D, [2021-03-10 11:26:08 +00:00 #385748] DEBUG -- cnf-conformance-verbose: {kind: "Service", name: "chf-bridge-cnf"}
D, [2021-03-10 11:26:08 +00:00 #385748] DEBUG -- cnf-conformance: kubectl get resource volumes kind: Service resource_name: chf-bridge-cnf
D, [2021-03-10 11:26:08 +00:00 #385748] DEBUG -- cnf-conformance: kubectl get resource volumes: 
D, [2021-03-10 11:26:08 +00:00 #385748] DEBUG -- cnf-conformance-verbose: check_service: false
D, [2021-03-10 11:26:08 +00:00 #385748] DEBUG -- cnf-conformance-verbose: check_containers: true
D, [2021-03-10 11:26:08 +00:00 #385748] DEBUG -- cnf-conformance-verbose: {kind: "Service", name: "diameter-proxy-cnf"}
D, [2021-03-10 11:26:08 +00:00 #385748] DEBUG -- cnf-conformance: kubectl get resource volumes kind: Service resource_name: diameter-proxy-cnf
D, [2021-03-10 11:26:08 +00:00 #385748] DEBUG -- cnf-conformance: kubectl get resource volumes: 
D, [2021-03-10 11:26:08 +00:00 #385748] DEBUG -- cnf-conformance-verbose: check_service: false
D, [2021-03-10 11:26:08 +00:00 #385748] DEBUG -- cnf-conformance-verbose: check_containers: true
D, [2021-03-10 11:26:08 +00:00 #385748] DEBUG -- cnf-conformance: workload resource test intialized: true test_passed: false
W, [2021-03-10 11:26:08 +00:00 #385748]  WARN -- cnf-conformance: ****Warning**** task reasonable_image_size not found in points.yml
✖️  FAILURE: Image size too large 🦖 ⚖️👀
```

**Device (please complete the following information):**
 - OS Linux
 - Distro Ubuntu
 - Version 20.04
 - Architecture x86_64

**Additional context**
The dockerd manifest could not be found as I am running the tests OUTSIDE of the source directory and my 'tools' directory does not contain the dockerd/manifest.yml file.  I fixed the dockerd install by manually copying the manifest.
Before this I tried re-running 'setup' but this did not copy the manifest into my local 'tools' directory.
I added lots of extra debug to my 'bug/#635_rollback_port' branch which is tracked in PR: #642

**Comment by sishbi** [comment]
FYI: @wavell @taylor

**Comment by sishbi** [comment]
This error can be seen in the following PR test: https://github.com/cncf/cnf-conformance/runs/2076208091?check_suite_focus=true

**Comment by lixuna** [comment]
Thank you @sishbi.

We're discussing adding a "skip" to this test if the dockerd install is unsuccessful. 

This is also related to a new feature in planning for how skipped tests are scored in the test results #603

**Comment by lixuna** [comment]
### Level of effort in points: 0,1,2,3,5,8,13,21: 

@denverwilliams - 
@agentpoyo - 
@wavell - 
@williscool -  
@nupejosh - 
@taylor - 
@lixuna -

**Comment by taylor** [comment]
Will need something to make the reasonable_image_size test SKIP if the size of the image can not be determined.

Error causing test failure here https://github.com/cncf/cnf-conformance/issues/645#issuecomment-795312394 was addressed partially in https://github.com/cncf/cnf-conformance/pull/642/files#diff-12273f6a8e593c98cbde8172a228325c8a4ce51061caee489da9068878394851R211-R218

This still marks the test as failed.  


cc: @wavell @denverwilliams

**Comment by agentpoyo** [comment]
The samples do not exist in the AC. 

Also, need to come up with a good way to test as an end user to avoid the test from installing dockerd which satisfies the dependency on it.

**Comment by agentpoyo** [comment]
@wavell @denverwilliams 

Also need to update the USAGE documentation 
"I expect to see an explanation of PASSED (green), FAILED (red), and SKIPPED (yellow) results"

**Comment by agentpoyo** [comment]
SKIPPED: Unable to test image size due to problem with dockerd: screenshot:

![645_reasonable_image_skipped](https://user-images.githubusercontent.com/14348948/112041307-40efdb80-8b14-11eb-866b-70da669cc7ff.png)

**Comment by lixuna** [comment]
@agentpoyo has the usage guide been updated per your comment [here](https://github.com/cncf/cnf-conformance/issues/645#issuecomment-799764719)?

I didn't see any explanation of passed, failed, skipped on https://github.com/cncf/cnf-conformance/blob/master/USAGE.md, but perhaps it's in another branch.

**Comment by agentpoyo** [comment]
> @agentpoyo has the usage guide been updated per your comment [here](https://github.com/cncf/cnf-conformance/issues/645#issuecomment-799764719)?
> 
> I didn't see any explanation of passed, failed, skipped on https://github.com/cncf/cnf-conformance/blob/master/USAGE.md, but perhaps it's in another branch.

Looks like it got missed. I can do an update to add the documentation to USAGE.md @lixuna

**Comment by agentpoyo** [comment]
@lixuna 

https://github.com/cncf/cnf-conformance/blob/doc/%23645_usage_updates/USAGE.md#results-output

If looks good, I can create a PR for final review and merge.

**Comment by lixuna** [comment]
Thanks for the documentation update, @agentpoyo 

LGTM as a first pass

<img width="760" alt="Screen Shot 2021-03-23 at 10 17 42 AM" src="https://user-images.githubusercontent.com/11701267/112170455-11e37380-8bc1-11eb-804e-6f25c741d95e.png">
