### ISSUE TITLE
[BUG] rename FAILURE to FAILED in test results

### ISSUE THREAD

**Issue by lixuna** [cncf/cnf-conformance#649]
**Describe the bug**
- test result outcomes are currently: PASSED, SKIPPED, FAILURE

**Expected behavior**
- we would like to see: PASSED, SKIPPED, FAILED
- all test outcomes would be past tense

**Comment by iamayushdas** [comment]
I want to fix this.
@lixuna

**Comment by thewolfpack** [comment]
Ayush, take a stab at it, submit a pr and I'll assist you with getting it
in. :)

**Comment by iamayushdas** [comment]
Also , getting error while building! 
Help needed !

![Screenshot from 2021-03-17 21-12-26](https://user-images.githubusercontent.com/40708551/111495648-98352b00-8765-11eb-85bd-85b126ced2f3.png)

**Comment by agentpoyo** [comment]
> Also , getting error while building!
> Help needed !
> 

Hello @iamayushdas ,

Make sure you're using crystal 0.35.1 as ameba version is locked at version 0.12.1. If you're using a newer version of Crystal, you'll likely see this error as it will want a newer version of ameba as well.

**Comment by iamayushdas** [comment]
> > Also , getting error while building!
> > Help needed !
> 
> Hello @iamayushdas ,
> 
> Make sure you're using crystal 0.35.1 as ameba version is locked at version 0.12.1. If you're using a newer version of Crystal, you'll likely see this error as it will want a newer version of ameba as well.

i am not able to downgrade crystal version to 0.35.1. and the new version of ameba i.e; 0.13.4 gives error.
help needed!

**Comment by agentpoyo** [comment]
@iamayushdas ,

We have not tested the cnf-conformance test suite with newer versions > 0.35.1. Expect unlikely results if attempting such versions not yet verified or tested against.

**Comment by iamayushdas** [comment]
I was using 0.36 version of crystal and 0.14.1 ameba.
I think we should now make cnf-conformance supportable for latest version .

**Comment by agentpoyo** [comment]
> I think we should now make cnf-conformance supportable for latest version .

If you are up for the challenge, feel free to take a go at it.

**Comment by agentpoyo** [comment]
> i am not able to downgrade crystal version to 0.35.1. and the new version of ameba i.e; 0.13.4 gives error.
> help needed!

https://github.com/crenv/crenv gives you the ability to change crystal versions.

**Comment by agentpoyo** [comment]
### Acceptance Criteria for peer review 
--
### Documentation is updated:
- [ ] n/a

###  Common steps
- [ ]  Find or create a K8s cluster to use
   - Talk with team for access to an existing cluster
   - [Kind K8s clusters](https://github.com/cncf/cnf-conformance/blob/master/KIND-INSTALL.md) will work as well
- [ ]  Set the KUBECONFIG environment variable for accessing the target K8s cluster
- [ ]  As a developer, Pull down latest version of CNF conformance test code from {FEATURE} branch
     - [ ]  Check that {FEATURE} Branch passes all A/C 
     - [ ]  Check that {FEATURE} Branch passes tests in GitHub Actions
- [ ]  As a peer reviewer, check that PR passes in GitHub Actions
     - [ ] if yes, merge PR to master
     - [ ]  if no, make a comment and request that developer make changes to pass tests 
- [ ]   As a peer reviewer, Pull down latest version of CNF conformance test code from `master` branch
- [ ]  Run `shards install`

### Spec test should pass
- [ ]  Run `crystal spec`
- [ ]  I expect to see PASSED for the tests

### Update Prerequisite checker
- [ ] N/A

### Update yml validator, if needed
- [ ] N/A

### I would expect that the results.yml to be able to be updated with a skipped task 
- [ ]  Follow common steps above
- [ ]  Setup an example cnf to test output with known failures: `cnf-conformance cnf_setup cnf-config=./sample-cnfs/sample_coredns_bad_liveness/cnf-conformance.yml`
- [ ]  Prepare the test suite to use the CNF by running: `cnf-conformance all`
- [ ]  I expect to see FAILED tests output as `FAILED` and not `FAILURE`
- [ ]  I expect to see PASSED for tests that pass.

### Screenshots of all command and workload command output
- [ ] I can see a screenshot of example output of `FAILED`

**Comment by agentpoyo** [comment]
![FAILED_649_screenshot](https://user-images.githubusercontent.com/14348948/112034581-a213b100-8b0c-11eb-9b31-0e1fc52c6ffd.png)
