### ISSUE TITLE
[BUG] Not all tests are present in 'points-v1.yml' causing test to report '0 of 10'

### ISSUE THREAD

**Issue by sishbi** [cncf/cnf-conformance#652]
**Describe the bug**
There are tests missing from the default point.yml file, which is downloaded from here: https://github.com/cncf/cnf-conformance/blob/master/scoring_config/points_v1.yml
The specific example I have is the 'statelessness' suite runs the 'volume_hostpath_not_found' test but this test is not present in the local points.yml so no points are awarded and the total remains '0 of 10'.

**To Reproduce**
1. Run the 'statelessness' suite
2. Verify that no points are awarded even though the test passes
3. Verify that the total is '0 of 10'

**Expected behavior**
All tests that are run via the 'workload' suite should be included in the points_v1.yml and points awarded appropriately.

**Screenshots**
See log below showing the result of not finding the test:
```
✔️  PASSED: hostPath volumes not found 🖥️  💾
Statelessness final score: 0 of 10
```

See below for a detailed log for that specific test, with some additional debug showing how points are calculated.
I can now see from the log below that the warning about the task missing is present so I guess it doesn't get displayed when running with no logging enabled.
It is worth nothing that adding the following to the points.yml fixes this issue:
```yaml
- name: volume_hostpath_not_found
  tags: statelessness, dynamic
```
However the other 2 tests that are associated with the statelessness suite are not run, so the points are never increased for those: reset_cnf, check_reaped.

**Device (please complete the following information):**
 - OS Linux
 - Distro Ubuntu
 - Version 20.04
 - Architecture x86_64

```
D, [2021-03-12 12:16:46 +00:00 #173211] DEBUG -- cnf-conformance: cnf_workload_resource yield resp: true
D, [2021-03-12 12:16:46 +00:00 #173211] DEBUG -- cnf-conformance: cnf_workload_resource yield resp: true
D, [2021-03-12 12:16:46 +00:00 #173211] DEBUG -- cnf-conformance: cnf_workload_resource yield resp: true
D, [2021-03-12 12:16:46 +00:00 #173211] DEBUG -- cnf-conformance: cnf_workload_resource yield resp: true
W, [2021-03-12 12:16:46 +00:00 #173211]  WARN -- cnf-conformance: ****Warning**** task volume_hostpath_not_found not found in points.yml
I, [2021-03-12 12:16:46 +00:00 #173211]  INFO -- cnf-conformance: task_points: task: volume_hostpath_not_found is worth: 5 points
I, [2021-03-12 12:16:46 +00:00 #173211]  INFO -- cnf-conformance: upsert_task: task: volume_hostpath_not_found has status: passed and is awarded: 5 points
✔️  PASSED: hostPath volumes not found 🖥️  💾
D, [2021-03-12 12:16:46 +00:00 #173211] DEBUG -- cnf-conformance: total_points: statelessness, found tasks: ["reset_cnf", "check_reaped"]
D, [2021-03-12 12:16:46 +00:00 #173211] DEBUG -- cnf-conformance: total_points: statelessness, volume_hostpath_not_found = 5
I, [2021-03-12 12:16:46 +00:00 #173211]  INFO -- cnf-conformance: total_points: statelessness = 0
I, [2021-03-12 12:16:46 +00:00 #173211]  INFO -- cnf-conformance: task_points: task: reset_cnf is worth: 5 points
I, [2021-03-12 12:16:46 +00:00 #173211]  INFO -- cnf-conformance: task_points: task: check_reaped is worth: 5 points
I, [2021-03-12 12:16:46 +00:00 #173211]  INFO -- cnf-conformance: total_max_points: statelessness = 10
Statelessness final score: 0 of 10
D, [2021-03-12 12:16:46 +00:00 #173211] DEBUG -- cnf-conformance: results yaml: {"name" => "cnf conformance", "status" => nil, "points" => nil, "exit_code" => 0, "items" => [{"name" => "volume_hostpath_not_found", "status" => "passed", "points" => 5}]}
```

**Comment by sishbi** [comment]
I have updated PR #653 to merge in tests mentioned in points.yml and points-all.yml into points-v1.yml (which is the default for the local points.yml) And to add the 'workload' suite so that the points are calculated correctly.
I see you merged the SKIPPED logic into master which I merged into my branch, I guess that needs to be implemented for the other tests that are skipped.
Please review my PR @lixuna @taylor @wavell 
Thanks!

**Comment by agentpoyo** [comment]
LGTM :+1: 

![image](https://user-images.githubusercontent.com/14348948/113195947-84d79480-9228-11eb-984a-c672a9d2fb8e.png)
