### ISSUE TITLE
[BUG] secrets_used should ignore service-account, docker-config-json and helm secret types

### ISSUE THREAD

**Issue by sishbi** [cncf/cnf-conformance#667]
**Describe the bug**
I have run secrets_used and it is failing but I don't think the failure is valid.
I have added additional debug to show the secrets that are defined for a CNF and the list only includes the following types:
- kubernetes.io/service-account-token
- kubernetes.io/dockerconfigjson
- helm.sh/release.v1
None of these secrets are referenced by the deployment either as a volume or as an environment variable, so the test fails.
I think the test should pass if any of these types of secret exist without being referenced
OR if any secret (excluding these types) exist that are referenced as a volume or as an environment variable

**To Reproduce**
1. Create a CNF that is installed via Helm and that uses a ServiceAccount and/or ImagePullSecret
2. Install the CNF
3. Run secrets_used
4. See failure

**Expected behavior**
The test should pass, see reason above.

**Log**
I, [2021-03-24 16:42:34 +00:00 #322071]  INFO -- cnf-conformance: volumes: []
I, [2021-03-24 16:42:34 +00:00 #322071]  INFO -- cnf-conformance-verbose: secret name: chf-charging-bridge-cnf-token-shcrk, type: kubernetes.io/service-account-token
I, [2021-03-24 16:42:34 +00:00 #322071]  INFO -- cnf-conformance-verbose: secret name: chf-charging-bridge-docker-registry-creds, type: kubernetes.io/dockerconfigjson
I, [2021-03-24 16:42:34 +00:00 #322071]  INFO -- cnf-conformance-verbose: secret name: default-token-bxskf, type: kubernetes.io/service-account-token
I, [2021-03-24 16:42:34 +00:00 #322071]  INFO -- cnf-conformance-verbose: secret name: pod-network-latency-sa-token-72mbr, type: kubernetes.io/service-account-token
I, [2021-03-24 16:42:34 +00:00 #322071]  INFO -- cnf-conformance-verbose: secret name: sh.helm.release.v1.cnf.v1, type: helm.sh/release.v1
I, [2021-03-24 16:42:34 +00:00 #322071]  INFO -- cnf-conformance-verbose: container envs [{"name" => "MTX_DIAM_LOG_LEVEL", "value" => "info"}, {"name" => "MTX_MAPPING_TRACE", "value" => "false"}, {"name" => "MTX_MAPPING_SPECIFICATION_VERSION", "value" => "R15-2019-12"}, {"name" => "MTX_HTTP_CONNECTION_HOST", "value" => "chf-bridge-cnf"}, {"name" => "MTX_HTTP_CONNECTION_PORT", "value" => "80"}, {"name" => "MTX_DIAMETER_HOST", "valueFrom" => {"fieldRef" => {"apiVersion" => "v1", "fieldPath" => "metadata.name"}}}, {"name" => "MTX_DIAMETER_REALM", "value" => "diameter-proxy-cnf.default.svc.cluster.local"}, {"name" => "MTX_DIAMETER_MODE", "value" => "ClientServer"}]
No Secret Volumes or Container secretKeyRefs found for resource: {kind: "Deployment", name: "diameter-proxy-cnf"}
I, [2021-03-24 16:42:34 +00:00 #322071]  INFO -- cnf-conformance: upsert_task: task: secrets_used has status: failed and is awarded: -1 points
✖️  FAILED: Secret Volume not found 🧫

**Device (please complete the following information):**
 - OS Linux
 - Distro Ubuntu
 - Version 18.04
 - Architecture x86_64

**Comment by sishbi** [comment]
I found the original design for secrets_used in #517 which I agree with.
@taylor @wavell @lixuna Please review.
I will create a PR with the debug changes I made for this issue.

**Comment by taylor** [comment]
ref https://kubernetes.io/docs/concepts/configuration/secret/

**Comment by sishbi** [comment]
As discussed in WG meeting.
The test should NOT fail if any secrets found of type: kubernetes.io/service-account-token, kubernetes.io/dockerconfigjson, helm.sh/release.v1 that are NOT used, but should continue to verify that if they are used then they are used correctly.
Test SHOULD fail if any other type of secret is defined (such as Opaque, TLS, Basic-Auth) that is not used by the container.

**Comment by sishbi** [comment]
Hi @denverwilliams @wavell @taylor 
I have created a new PR for this: #675 
With my change the result is now:
  PASSED: Secret Volume or Reference found or ignored 🧫

**Comment by williscool** [comment]
after merging #693 

with https://github.com/cncf/cnf-conformance/pull/693/files?file-filters%5B%5D=.cr&file-filters%5B%5D=.json&file-filters%5B%5D=.lock&file-filters%5B%5D=.md&file-filters%5B%5D=.txt&file-filters%5B%5D=dotfile

lgtm

**Comment by williscool** [comment]
need to add A/C

**Comment by agentpoyo** [comment]
### Acceptance Criteria for peer review
--
### Documentation is updated:
- [ ] cnf-conformance.yml documentation update 

###  Common steps
- [x]  Find or create a K8s cluster to use
   - Talk with team for access to an existing cluster
   - [Kind K8s clusters](https://github.com/cncf/cnf-conformance/blob/master/KIND-INSTALL.md) will work as well
- [x]  Set the KUBECONFIG environment variable for accessing the target K8s cluster
- [ ]  As a developer, Pull down latest version of CNF conformance test code from {FEATURE} branch
     - [ ]  Check that {FEATURE} Branch passes all A/C 
     - [ ]  Check that {FEATURE} Branch passes tests in GitHub Actions
- [ ]  As a peer reviewer, check that PR passes in GitHub Actions
     - [ ] if yes, merge PR to master
     - [ ]  if no, make a comment and request that developer make changes to pass tests 
- [x]   As a peer reviewer, Pull down latest version of CNF conformance test code from `master` branch
- [x]  Run `shards install`

### Spec test should pass
- [x]  Run `crystal spec`
- [x]  I expect to see PASSED for the spec

### Update Prerequisite checker
- [ ] N/A

### Update yml validator, if needed
- [ ] N/A

### I would expect that the cnf-conformance.yml to not error or fail for `secrets_used`:
- [x]  Follow common steps above
- [x]  Follow the Setup cluster instructions above
- [x]  When running `LOG_LEVEL=info crystal spec --tag "secrets_used" -v` I should see skipped documentation.
- [x]  I expect to see the output from the test

### Screenshots of rolling
- [x] I can see a screenshot of output without errors for `secrets_used`

**Comment by agentpoyo** [comment]
![image](https://user-images.githubusercontent.com/14348948/113952177-cc3ac380-97da-11eb-9727-b7434d570cc2.png)
