### ISSUE TITLE
[BUG] immutable_configmap should not fail if immutable config-maps are not supported/enabled for cluster

### ISSUE THREAD

**Issue by sishbi** [cncf/cnf-conformance#669]
**Describe the bug**
I have run the immutable_configmap test and it fails, however I am using k8s 1.18 and it is not supported by this version.
Also, we have to support this version as a minimum so cannot enable immutable config maps, 
I think the test is valid ONLY IF they are enabled/supported by the k8s cluster that the test is running on.

**To Reproduce**
1. Install the CNF on Kubernetes v1.18 (without enabling the immutable config map feature flag)
2. Run the immutable_configmap test
4. See the failure

**Expected behavior**
The test should be SKIPPED if the immutable config map feature is not supported

**Log**
I, [2021-03-24 16:57:21 +00:00 #335436]  INFO -- cnf-conformance: KubectlClient.apply stderr: 
I, [2021-03-24 16:57:21 +00:00 #335436]  INFO -- cnf-conformance: kubectl apply failed for: /home/sbillingsley/chf-cnf-conformance/cnfs/cnf/test_config_map.yml
I, [2021-03-24 16:57:21 +00:00 #335436]  INFO -- cnf-conformance: upsert_task: task: immutable_configmap has status: failed and is awarded: -1 points
✖️  FAILED: immmutable configmaps are not enabled in this k8s cluster.
I, [2021-03-24 16:57:22 +00:00 #335436]  INFO -- cnf-conformance: upsert_task: task: immutable_configmap has status: failed and is awarded: -1 points
✖️  FAILED: Found mutable configmap(s) ⚖️

**Comment by taylor** [comment]
Pre 1.19 does not have immutable config maps enabled by default on the cluster
App developers may have no control over the cluster used
Should be skipped

**Comment by taylor** [comment]
Check version in K8s. Probably add to https://github.com/cncf/cnf-conformance/blob/master/src/tasks/utils/kubectl_client.cr
If 1.19 or greater check for mutable config maps and fail if they are found
If a lower version skip mutable config check

**Comment by sishbi** [comment]
I added a PR for this: #677

**Comment by agentpoyo** [comment]
### Acceptance Criteria

---
###  Common steps
- [x]  Find or create a K8s cluster to use
   - Talk with team for access to an existing cluster
   - [Kind K8s clusters](https://github.com/cncf/cnf-conformance/blob/master/KIND-INSTALL.md) will work as well
- [x]  Set the KUBECONFIG environment variable for accessing the target K8s cluster
- [ ]  As a developer, Pull down latest version of CNF conformance test code from {FEATURE} branch
     - [ ]  Check that {FEATURE} Branch passes all A/C 
     - [ ]  Check that {FEATURE} Branch passes tests in GitHub Actions
- [x]  As a peer reviewer, check that PR passes in GitHub Actions
     - [ ] if yes, merge PR to master
     - [ ]  if no, make a comment and request that developer make changes to pass tests 
- [x]   As a peer reviewer, Pull down latest version of CNF conformance test code from `master` branch
- [x]  Run `shards install`

### Spec test should pass
- [x]  Run `crystal spec`
- [x]  I expect to see PASSED for the tests

### Update documentation 
- [ ] n/a

### Update Prerequisite checker
- [ ] N/A 

### Update yml validator, if needed
- [ ] n/a

### Create a kind cluster using k8s v1.18.x
- [x] kind create cluster --name kind-v1-18 --kubeconfig ./kind-v18.conf --image kindest/node:v1.18.0

### Create a kind cluster using latest k8s version
- [x] kind create cluster --name kind-latest --kubeconfig ./kind-latest.conf --image kindest/node:latest

### When using k8s version 1.18.x, we should see SKIPPED for immutable_configmap as this was not enabled by default until v1.19.x and greater:
- [x] Follow common steps above
- [x] Use k8s v1.18 cluster created by `export KUBECONFIG=./kind-v18.conf`
- [x] Run `LOG_LEVEL=error ./cnf-conformance cnf_setup cnf-config=./sample-cnfs/sample-coredns-cnf/cnf-conformance.yml `
- [x] Run `LOG_LEVEL=error ./cnf-conformance immutable_configmap`
- [x] I expect to see the output from the spec
- [x] I would expect to see that `immutable_configmap` is SKIPPED.

### When using k8s version latest, we should see FAILED for immutable_configmap:
- [x] Follow common steps above
- [x] Use k8s latest cluster created by `export KUBECONFIG=./kind-latest.conf`
- [x] Run `LOG_LEVEL=error ./cnf-conformance cnf_setup cnf-config=./sample-cnfs/sample-coredns-cnf/cnf-conformance.yml `
- [x] Run `LOG_LEVEL=error ./cnf-conformance immutable_configmap`
- [x] I expect to see the output from the spec
- [x] I would expect to see that `immutable_configmap` is FAILED.

### When using k8s version latest, we should see PASSED for immutable_configmap on CNF where it is enabled.
- [x] Follow common steps above
- [x] Use k8s latest cluster created by `export KUBECONFIG=./kind-latest.conf`
- [x] Run `LOG_LEVEL=error ./cnf-conformance cnf_setup cnf-config=./sample-cnfs/sample_immutable_configmap_all/cnf-conformance.yml `
- [x] Run `LOG_LEVEL=error ./cnf-conformance immutable_configmap`
- [x] I expect to see the output from the spec
- [x] I would expect to see that `immutable_configmap` is PASSED.

### Screenshots of all command and workload command output
- [x] I can see a screenshot from output for k8s version 1.18.x and SKIPPED.
- [x] I can see a screenshot from output for k8s version latest and FAILED.
- [x] I can see a screenshot from output for k8s version latest and PASSED.

**Comment by agentpoyo** [comment]
![image](https://user-images.githubusercontent.com/14348948/113943155-b53ea600-97c7-11eb-9698-da4a71d7cd40.png)

**Comment by agentpoyo** [comment]
![image](https://user-images.githubusercontent.com/14348948/113943190-c5568580-97c7-11eb-89eb-02fb7eedc917.png)

**Comment by agentpoyo** [comment]
![image](https://user-images.githubusercontent.com/14348948/113943275-efa84300-97c7-11eb-9c57-1199f924d46e.png)
