### ISSUE TITLE
[Feature] Combine all points.yml files into an embedded file

### ISSUE THREAD

**Issue by wavell** [cncf/cnf-conformance#676]
**Is your feature request related to a problem? Please describe.**
There are multiple points.yml files that need to be updated each time a new test is added

**Describe the solution you'd like**
I would like to have the points.yml file in once place, and then embedded upon compilation so that it gets distributed with the binary.

**Comment by agentpoyo** [comment]
I plan to add A/C for this.

**Comment by agentpoyo** [comment]
### Acceptance Criteria for peer review (based on https://github.com/cncf/cnf-conformance/issues/82)
--
### Documentation is updated:
- [ ] cnf-conformance.yml documentation update 

###  Common steps
- [ ]  Find or create a K8s cluster to use
   - Talk with team for access to an existing cluster
   - [Kind K8s clusters](https://github.com/cncf/cnf-conformance/blob/master/KIND-INSTALL.md) will work as well
- [ ]  Set the KUBECONFIG environment variable for accessing the target K8s cluster
- [ ]  As a developer, Pull down latest version of CNF conformance test code from {FEATURE} branch
     - [ ]  Check that {FEATURE} Branch passes all A/C 
     - [ ]  Check that {FEATURE} Branch passes tests in GitHub Actions
- [ ]  As a peer reviewer, check that PR passes in GitHub Actions
     - [ ] if yes, merge PR to master
     - [ ]  if no, make a comment and request that developer make changes to pass tests 
- [ ]   As a peer reviewer, Pull down latest version of CNF conformance test code from `master` branch
- [ ]  Run `shards install`

### Spec test should pass
- [ ]  Run `crystal spec`
- [ ]  I expect to see PASSED for the test

### Update Prerequisite checker
- [ ] N/A

### Update yml validator, if needed
- [ ] N/A

### I would expect that the test suite runs without a required points.yml file:
- [ ]  Follow common steps above
- [ ]  Prepare the test suite to use the CNF by running: `./cnf-conformance cnf_setup cnf-config=./sample-cnfs/sample_coredns_cnf/cnf-conformance.yml`
- [ ]  Make sure there is no points.yml file by rm or moving it to another location, eg. /tmp
- [ ]  Run  `./cnf-conformance all`
- [ ]  I expect to see the output from the test
- [ ]  I expect to see points added for PASSED tests and points removed for FAILED tests.

### I would expect that the test suite runs without a required points.yml file from the binary install
- [ ]  Follow common steps above.
- [ ]  Install the binary only via the [Binary Installation Steps](https://github.com/cncf/cnf-conformance/blob/main/INSTALL.md#Curl-Binary-Installation)
- [ ]  Pull down a sample cnf config: `wget -O cnf-conformance.yml https://raw.githubusercontent.com/cncf/cnf-conformance/main/example-cnfs/coredns/cnf-conformance.yml`
- [ ]  Prepare the test suite to use the CNF by running: `./cnf-conformance cnf_setup cnf-config=./cnf-conformance.yml`
- [ ]  Make sure there is no points.yml file by removing or moving it to another location, eg. /tmp
- [ ]  Run  `./cnf-conformance all`
- [ ]  I expect to see the output from the test
- [ ]  I expect to see points added for PASSED tests and points removed for FAILED tests.

### Screenshots of resilience test:
- [ ]  I can see a screenshots of output without a points.yml file present.
- [ ]  I can see a screenshot of the binary test results.

**Comment by agentpoyo** [comment]
![image](https://user-images.githubusercontent.com/14348948/114609915-f241e700-9c64-11eb-9a95-b665f33fdd15.png)

**Comment by agentpoyo** [comment]
![image](https://user-images.githubusercontent.com/14348948/114624347-2a055a80-9c76-11eb-85e8-f23d46787dc2.png)

**Comment by agentpoyo** [comment]
![image](https://user-images.githubusercontent.com/14348948/114636262-30063600-9c8c-11eb-9d33-c43b10d5ce6c.png)

**Comment by agentpoyo** [comment]
![image](https://user-images.githubusercontent.com/14348948/114638907-3ac3c980-9c92-11eb-9feb-3b551cb61d80.png)
