### ISSUE TITLE
[BUG] rolling_version_change fails if the version is an integer

### ISSUE THREAD

**Issue by sishbi** [cncf/cnf-conformance#682]
**Describe the bug**
When the version_test tags configured in the cnf-conformance.yml are integers they are ignored when converting the YAML to an object.

**To Reproduce**
1. Configure the cnf-conformance.yml with a rolling_version_change_test_tag with an integer value, such as 1234
2. Setup the CNF
3. Run the rolling_version_change test
4. See the test fail

**Expected behavior**
The test should pass.

**Screenshots**
The issue is that the cnf-conformance is read in and the rolling_version_change_test_tag is empty, so the test cannot identify the new version to change to.

**Device (please complete the following information):**
 - OS Linux
 - Distro Ubuntu
 - Version 20.04
 - Architecture x86_64

**Additional context**
Enclosing the version in double-quotes causes it to be interpreted as a string which solves the problem.
Extract from cnf-conformance.yml:
container_names:
  - name: app
    rollback_from_tag: 1234
    rolling_update_test_tag: 4321
    rolling_downgrade_test_tag: 1357
    rolling_version_change_test_tag: 9876

**Comment by williscool** [comment]
lgtm but don't have a cnf with an integer version to test.

**Comment by williscool** [comment]
need to add A/C

**Comment by agentpoyo** [comment]
### Acceptance Criteria for peer review (based on https://github.com/cncf/cnf-conformance/issues/82)
--
### Documentation is updated:
- [ ] cnf-conformance.yml documentation update 

###  Common steps
- [ ]  Find or create a K8s cluster to use
   - Talk with team for access to an existing cluster
   - [Kind K8s clusters](https://github.com/cncf/cnf-conformance/blob/master/KIND-INSTALL.md) will work as well
- [ ]  Set the KUBECONFIG environment variable for accessing the target K8s cluster
- [ ]  As a developer, Pull down latest version of CNF conformance test code from {FEATURE} branch
     - [ ]  Check that {FEATURE} Branch passes all A/C 
     - [ ]  Check that {FEATURE} Branch passes tests in GitHub Actions
- [ ]  As a peer reviewer, check that PR passes in GitHub Actions
     - [ ] if yes, merge PR to master
     - [ ]  if no, make a comment and request that developer make changes to pass tests 
- [ ]   As a peer reviewer, Pull down latest version of CNF conformance test code from `master` branch
- [ ]  Run `shards install`

### Spec test should pass
- [ ]  Run `crystal spec`
- [ ]  I expect to see PASSED for the te

### Update Prerequisite checker
- [ ] N/A

### Update yml validator, if needed
- [ ] N/A

### Setup a cluster with a registry to pull and push images to create tags with integers only
- [ ] kubectl create -f tools/registry/manifest.yml
- [ ] kubectl create -f tools/dockerd/manifest.yml
- [ ] kubectl exec dockerd -ti -- docker pull coredns/coredns:1.6.7
- [ ] kubectl exec dockerd -ti -- docker tag coredns/coredns:1.6.7 registry:5000/coredns:167
- [ ] kubectl exec dockerd -ti -- docker push registry:5000/coredns:167
- [ ] kubectl exec dockerd -ti -- docker pull coredns/coredns:1.8.0
- [ ] kubectl exec dockerd -ti -- docker tag coredns/coredns:1.8.0 registry:5000/coredns:180
- [ ] kubectl exec dockerd -ti -- docker push registry:5000/coredns:180

### I would expect that the cnf-conformance.yml to PASS a rolling_version_change when the tag is only an integer:
- [ ]  Follow common steps above
- [ ]  Follow the Setup cluster instructions above
- [ ]  Edit the `./sample-cnfs/sample_local_registry/cnf-conformance.yml` file with the new values; change 1.6.7 to 167 and 1.8.0 to 180.
- [ ]  Prepare the test suite to use the CNF by running: `./cnf-conformance cnf_setup cnf-config=./sample-cnfs/sample_local_registry/cnf-conformance.yml`
- [ ]  Run  `./cnf-conformance rolling_version_change`
- [ ]  I expect to see the output from the test
- [ ]  I expect to see PASSED for the test and no errors about the tags as integers

### Screenshots of all command and workload command output
- [ ] I can see a screenshot of output without errors for the `rolling_version_change` test.

**Comment by agentpoyo** [comment]
![image](https://user-images.githubusercontent.com/14348948/114076864-c68dbe00-986c-11eb-94d9-18d95f605793.png)

**Comment by agentpoyo** [comment]
LGTM :+1:
