### ISSUE TITLE
[BUG] Running CNF test displays a failed test but then PASSED on next line output afterwards

### ISSUE THREAD

**Issue by agentpoyo** [cncf/cnf-conformance#684]
**Describe the bug**
When running a CNF test, the output when using LOG_LEVEL=error displays an error but then it passes. (see screenshot attached)

**To Reproduce**
1. Follow common install steps to cnf-conformance
2. Setup and use the sample-coredns-cnf `cnf-conformance cnf_setup cnf-config=./sample-cnfs/sample_coredns/cnf-conformance.yml`
3. Then run a `workload` by doing `LOG_LEVEL=error ./cnf-conformance workload`
4. See output

**Expected behavior**
A passed test should not also output as failed. If a pod is passing but another is failing, it should be more precise in the output on what is actually failing or passing.

**Screenshots**

![image](https://user-images.githubusercontent.com/14348948/113192870-edbd0d80-9224-11eb-8321-5b0427c6e760.png)

![image](https://user-images.githubusercontent.com/14348948/113192978-0c230900-9225-11eb-871e-74132aec66e0.png)

**Device (please complete the following information):**
 - OS Linux
 - Distro Ubuntu
 - Version 18.04
 - Architecture x86

**Comment by agentpoyo** [comment]
Acceptance Criteria:

Steps to reproduce the behavior:
 - [ ] Follow common install steps to cnf-conformance
 - [ ] Setup and use the sample-coredns-cnf `cnf-conformance cnf_setup cnf-config=./sample-cnfs/sample_coredns/cnf-conformance.yml`
- [ ] Run a `workload` by doing `LOG_LEVEL=error ./cnf-conformance workload`
- [ ] Should not see any tests with FAILED and PASSED during the test suite run.
- [ ] I can see a screenshot of the output.

**Comment by agentpoyo** [comment]
![image](https://user-images.githubusercontent.com/14348948/115307843-6c73df00-a12f-11eb-8efb-ee329213ea39.png)

**Comment by lixuna** [comment]
@wavell @agentpoyo @denverwilliams  what was the level of effort in pts to make this change? (0,1,2,3,5,8,13,21)

**Comment by agentpoyo** [comment]
3pt
