### ISSUE TITLE
[BUG] dockerd failed error when dockerd pod already installed on cluster

### ISSUE THREAD

**Issue by agentpoyo** [cncf/cnf-conformance#686]
**Describe the bug**
Running a CNF on a cluster that has dockerd already installed errors with:

```
E, [2021-03-31 17:58:43 +00:00 #2638392] ERROR -- cnf-conformance: Dockerd_Install failed.
```

**To Reproduce**
1. Follow common install steps to cnf-conformance
2. Setup and use the sample-coredns-cnf `cnf-conformance cnf_setup cnf-config=./sample-cnfs/sample_coredns_cnf/cnf-conformance.yml`
3. Then run a `workload` by doing `LOG_LEVEL=error ./cnf-conformance workload`
4. See output

**Expected behavior**
The output should not display a failure on installing dockerd if it's already installed.

**Screenshots**

![image](https://user-images.githubusercontent.com/14348948/113194253-8acc7600-9226-11eb-803b-37ff54e28173.png)

**Device (please complete the following information):**
 - OS Linux
 - Distro Ubuntu
 - Version 18.04
 - Architecture x86

**Comment by agentpoyo** [comment]
Acceptance Criteria:

 - [ ] Follow common install steps to cnf-conformance
 - [ ] Setup and use the sample-coredns-cnf: `cnf-conformance cnf_setup cnf-config=./sample-cnfs/sample-coredns-cnf/cnf-conformance.yml`
 - [ ] Then run a workload by doing `LOG_LEVEL=error ./cnf-conformance workload`

**Comment by agentpoyo** [comment]
The dockerd failed error no longer shows up (since dockerd is already installed):

![image](https://user-images.githubusercontent.com/14348948/115074547-75f71000-9ebf-11eb-91ef-8ab9152189d2.png)

**Comment by lixuna** [comment]
@wavell @agentpoyo @denverwilliams  what was the level of effort in pts to make this change? (0,1,2,3,5,8,13,21)

**Comment by agentpoyo** [comment]
3pts
