### ISSUE TITLE
[BUG] debug output is present in LOG_LEVEL=error output

### ISSUE THREAD

**Issue by agentpoyo** [cncf/cnf-conformance#688]
**Describe the bug**
debug output is seen when running with LOG_LEVEL=error as the standard output during CNF Test Suite tests. (see screenshot)

**To Reproduce**
1. Follow common install steps to cnf-conformance
2. Setup and use the sample-coredns-cnf `cnf-conformance cnf_setup cnf-config=./sample-cnfs/sample_coredns_cnf/cnf-conformance.yml`
3. Then run a `workload` by doing `LOG_LEVEL=error ./cnf-conformance workload`
4. See output

**Expected behavior**
When running log level error, you should not see any type of line noise that isn't an error or debug output messages.

**Screenshots**
![image](https://user-images.githubusercontent.com/14348948/113195541-04189880-9228-11eb-82e0-40d619a14fb3.png)

**Device (please complete the following information):**
 - OS Linux
 - Distro Ubuntu
 - Version 18.04
 - Architecture x86

**Comment by agentpoyo** [comment]
Acceptance Criteria:

 - [ ] Follow common install steps to cnf-conformance
 - [ ] Setup and use the sample-coredns-cnf: `cnf-conformance cnf_setup cnf-config=./sample-cnfs/sample-coredns-cnf/cnf-conformance.yml`
 - [ ] Then run a workload by doing `LOG_LEVEL=error ./cnf-conformance workload`

**Comment by agentpoyo** [comment]
The `install.go` debug errors no longer show up:

![image](https://user-images.githubusercontent.com/14348948/115073954-a5f1e380-9ebe-11eb-9268-217bd19012f0.png)

**Comment by lixuna** [comment]
@wavell @agentpoyo @denverwilliams  what was the level of effort in pts to make this change? (0,1,2,3,5,8,13,21)

**Comment by agentpoyo** [comment]
3pts
