### ISSUE TITLE
[Feature] Remove curl as a cnf-conformance dependency. Switch to using a crystal library or curl instead.

### ISSUE THREAD

**Issue by wavell** [cncf/cnf-conformance#689]
[Feature] Remove curl as a cnf-conformance dependency. Switch to using a crystal library or curl instead.

**Is your feature request related to a problem? Please describe.**
Curl is a unneeded dependency.

**Describe the solution you'd like**
Remove curl as a cnf-conformance dependency. Switch to using a crystal library or curl instead.

Reference:
- related ticket on removing wget https://github.com/cncf/cnf-conformance/issues/679

**Comment by agentpoyo** [comment]
### Acceptance Criteria

---
###  Common steps
- [x]  Find or create a K8s cluster to use
   - Talk with team for access to an existing cluster
   - [Kind K8s clusters](https://github.com/cncf/cnf-conformance/blob/master/KIND-INSTALL.md) will work as well
- [x]  Set the KUBECONFIG environment variable for accessing the target K8s cluster
- [ ]  As a developer, Pull down latest version of CNF conformance test code from {FEATURE} branch
     - [ ]  Check that {FEATURE} Branch passes all A/C 
     - [ ]  Check that {FEATURE} Branch passes tests in GitHub Actions
- [x]  As a peer reviewer, check that PR passes in GitHub Actions
     - [ ] if yes, merge PR to master
     - [ ]  if no, make a comment and request that developer make changes to pass tests 
- [x]   As a peer reviewer, Pull down latest version of CNF conformance test code from `master` branch
- [x]  Run `shards install`

### Spec test should pass
- [x]  Run `crystal spec`
- [x]  I expect to see PASSED for the tests

### Update documentation 
- [ ] n/a

### Update Prerequisite checker
- [ ] N/A 

### Update yml validator, if needed
- [ ] n/a

### When a long running cnf is installed and then uninstalled, the resource_wait_for_uninstall function should want foer uninstall:
- [ ] Follow common steps above
- [ ] Run `LOG_LEVEL=error ./cnf-conformance setup `
- [ ] I expect to see the output from the spec
- [ ] I would expect to see that `curl` is no longer a requirement or pre-req.

### Screenshots of all command and workload command output
- [x] I can see a screenshot from output that curl is no longer required.

**Comment by agentpoyo** [comment]
![image](https://user-images.githubusercontent.com/14348948/113780388-c7034900-96f4-11eb-8645-65600dfe8e89.png)
