### ISSUE TITLE
[Workload] Resilience test: is CNF healthy after litmus disk fill chaos test?

### ISSUE THREAD

**Issue by lixuna** [cncf/cnf-conformance#690]
Child issue of #499
---

[Acceptance Criteria] (TBD)
---

### [Workload] Resilience test: is CNF healthy after litmus disk fill chaos test?

**Short description of workload test:** 
- adds a litmus disk fill chaos experiment to check the resiliency of the CNF application when subject to disk stress for a certain amount of given memory either in the percentage of total ephemeral-storage limit or the memory in Mi unit. It can also be used to test the Ephemeral Storage Limits, to ensure those parameters are sufficient and the application's resiliency to disk stress/replica evictions. For More information checkout experiment docs.

**Test Category**
- Resilience (USAGE.md#resilience-tests)

**Type of test (static or runtime)** 
- runtime

**PR**
- #663 

---

### Implementation Tasks: TBD

**Environment set up tasks:**
- [ ] 

**Upstream tool set up tasks: (conformance suite + upstream tools)**
- [ ] 

**CNF setup Tasks** 
- [ ] 

**Sample CNF tasks:**
- [ ] 

**Code implementation tasks:**
- [ ] 

**Documentation tasks:**
- [ ] Update [Test Categories md](https://github.com/cncf/cnf-conformance/blob/master/TEST-CATEGORIES.md) if needed 
- [ ] Update [Pseudo Code md](https://github.com/cncf/cnf-conformance/blob/master/PSEUDO-CODE.md) if needed
- [ ] Update [USAGE md](https://github.com/cncf/cnf-conformance/blob/master/USAGE.md) if needed 
- [ ] Update [installation instructions](https://github.com/cncf/cnf-conformance#installation)  if needed 

### QA tasks

Dev Review: 
- [ ] walk through A/C
- [ ] do you get the expected result?
- [ ] if yes, 
   - [ ] move to `Needs Peer Review` column  
   - [ ] create Pull Request and follow check list
   - [ ] Assign 1 or more people for peer review
- [ ] if no, document what additional tasks will be needed

Peer review:
- [ ] walk through A/C
- [ ] do you get the expected result?
- [ ] if yes, 
   - [ ] move to `Reviewer Approved` column
   - [ ] Approve pull request
- [ ] if no, 
   - [ ] document what did not go as expected, including error messages and screenshots (if possible)
   - [ ] Add comment to pull request
   - [ ] request changes to pull request

**Comment by williscool** [comment]
big thanks to @uditgaurav  !

lgtm

https://github.com/cncf/cnf-conformance/pull/674

**Comment by williscool** [comment]
need to add A/C

**Comment by agentpoyo** [comment]
### Acceptance Criteria for peer review (based on https://github.com/cncf/cnf-conformance/issues/82)
--
### Documentation is updated:
- [ ] cnf-conformance.yml documentation update 

###  Common steps
- [x]  Find or create a K8s cluster to use
   - Talk with team for access to an existing cluster
   - [Kind K8s clusters](https://github.com/cncf/cnf-conformance/blob/master/KIND-INSTALL.md) will work as well
- [x]  Set the KUBECONFIG environment variable for accessing the target K8s cluster
- [ ]  As a developer, Pull down latest version of CNF conformance test code from {FEATURE} branch
     - [ ]  Check that {FEATURE} Branch passes all A/C 
     - [ ]  Check that {FEATURE} Branch passes tests in GitHub Actions
- [ ]  As a peer reviewer, check that PR passes in GitHub Actions
     - [ ] if yes, merge PR to master
     - [ ]  if no, make a comment and request that developer make changes to pass tests 
- [x]   As a peer reviewer, Pull down latest version of CNF conformance test code from `master` branch
- [x]  Run `shards install`

### Spec test should pass
- [x]  Run `crystal spec`
- [x]  I expect to see PASSED for the te

### Update Prerequisite checker
- [ ] N/A

### Update yml validator, if needed
- [ ] N/A

### I would expect that the chaos `disk_fill` passes without errors:
- [x]  Follow common steps above
- [x]  Prepare the test suite to use the CNF by running: `./cnf-conformance cnf_setup cnf-config=./sample-cnfs/sample_coredns_cnf/cnf-conformance.yml`
- [x]  Run  `./cnf-conformance disk_fill`
- [x]  I expect to see the output from the test
- [x]  I expect to see PASSED for the test.

### Screenshots of rolling
- [x] I can see a screenshot of output without errors for the `disk_fill` test.

**Comment by agentpoyo** [comment]
![image](https://user-images.githubusercontent.com/14348948/114086618-71f04000-9878-11eb-9837-471209ca39c8.png)

**Comment by lixuna** [comment]
@agentpoyo has this test been added to the "points" as well?

**Comment by agentpoyo** [comment]
5 pts

**Comment by lixuna** [comment]
@agentpoyo would an end user see a score for this test? 

User stories: 
Given that I have run my CNF in the test suite
When my CNF passed this test
Then I can see x points added to my final score

and 

Given that I have run my CNF in the test suite
When my CNF failed this test
Then I can see y points removed from my final score

**Comment by agentpoyo** [comment]
![image](https://user-images.githubusercontent.com/14348948/114091646-8c2d1c80-987e-11eb-9e29-62b3e2265ef7.png)
