### ISSUE TITLE
[BUG] tags for points.yml scores are getting added for workload `reslilience` tests when they're tagged as `platform:resilience`

### ISSUE THREAD

**Issue by agentpoyo** [cncf/cnf-conformance#701]
**Describe the bug**

**To Reproduce**
1. Setup cnf-conformance test suite
2. Configure a sample test (coredns)
3. Run `cnf-conformance resilience`
4. You will see the score output of 10 of 20 as some of the resilience tests are improperly tagged as scalability but worker_reboot_recovery has a tag of `platform:resilience` that is getting tallied in the total points.

After manually fixing the pod_network_latency and disk_fill to be tagged as resilience, we then got a score of 20 of 25 since worker_reboot_recovery has resilience in the tag.

**Expected behavior**
Tests should be tagged properly and a tag of `platform:resilience` should not get added during a `workload` test.

**Screenshots**
![image](https://user-images.githubusercontent.com/14348948/114096090-e41a5200-9883-11eb-8abe-1040a01aac12.png)

**Device (please complete the following information):**
 - OS - Linux
 - Distro - Ubuntu
 - Version - 18.04
 - Architecture x86

**Comment by wavell** [comment]
- [ ] I expect `LOG_LEVEL=error crystal spec --tag "points" -v ` to return all passed tests

**Comment by wavell** [comment]
I believe chaos_network_loss needed to be commented out as well

**Comment by agentpoyo** [comment]
![image](https://user-images.githubusercontent.com/14348948/114236935-f231a680-9947-11eb-8e25-063d4306cdad.png)

**Comment by agentpoyo** [comment]
![image](https://user-images.githubusercontent.com/14348948/114237386-a8958b80-9948-11eb-967c-eb5872d7f69f.png)

**Comment by agentpoyo** [comment]
### Acceptance Criteria for peer review (based on https://github.com/cncf/cnf-conformance/issues/82)
--
### Documentation is updated:
- [ ] cnf-conformance.yml documentation update 

###  Common steps
- [x]  Find or create a K8s cluster to use
   - Talk with team for access to an existing cluster
   - [Kind K8s clusters](https://github.com/cncf/cnf-conformance/blob/master/KIND-INSTALL.md) will work as well
- [x]  Set the KUBECONFIG environment variable for accessing the target K8s cluster
- [ ]  As a developer, Pull down latest version of CNF conformance test code from {FEATURE} branch
     - [ ]  Check that {FEATURE} Branch passes all A/C 
     - [ ]  Check that {FEATURE} Branch passes tests in GitHub Actions
- [ ]  As a peer reviewer, check that PR passes in GitHub Actions
     - [ ] if yes, merge PR to master
     - [ ]  if no, make a comment and request that developer make changes to pass tests 
- [x]   As a peer reviewer, Pull down latest version of CNF conformance test code from `master` branch
- [x]  Run `shards install`

### Spec test should pass
- [x]  Run `crystal spec`
- [x]  I expect to see PASSED for the te

### Update Prerequisite checker
- [ ] N/A

### Update yml validator, if needed
- [ ] N/A

### I would expect that the points add up correctly when running `resilience` test:
- [x]  Follow common steps above
- [x]  Prepare the test suite to use the CNF by running: `./cnf-conformance cnf_setup cnf-config=./sample-cnfs/sample_coredns_cnf/cnf-conformance.yml`
- [x]  Run  `./cnf-conformance resilience`
- [x]  I expect to see the output from the test
- [x]  I expect to see 5 points give for each PASS and -1 for FAILED tests.

### Screenshots of rolling
- [x] I can see a screenshots of output with correct points given.

**Comment by agentpoyo** [comment]
![image](https://user-images.githubusercontent.com/14348948/114237862-48ebb000-9949-11eb-89db-582cef648736.png)

**Comment by lixuna** [comment]
@agentpoyo @denverwilliams @wavell what was the level of effort in pts to make this change? (0,1,2,3,5,8,13,21)

**Comment by agentpoyo** [comment]
3 pts
