### ISSUE TITLE
Installable test: Can the CNF perform a rolling version upgrade?

### ISSUE THREAD

**Issue by lixuna** [cncf/cnf-conformance#71]
[Acceptance Criteria](https://github.com/cncf/cnf-conformance/issues/71#issuecomment-594821908)
---

### Installable test: Can the CNF perform a rolling version upgrade?

Short description: 
- to check if a CNF version can be upgraded through a rolling update
- reference https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#updating-a-deployment

EPIC: CNF Conformance Test Suite

Release: vN.N.N

Test Category: Installable + Upgradeable

Type of test (static or runtime) = Runtime

- [x]  example code: #7 

- [ ] similar to #24 
---

**Environment set up tasks:**

**Upstream tool set up tasks: (conformance suite + upstream tools)**
- N/A

**CNF setup Tasks** 

**Sample CNF tasks:**

**Code implementation tasks:**
- [ ] 

**Documentation tasks:**
- [ ] Update [Test Categories md](https://github.com/cncf/cnf-conformance/blob/master/TEST-CATEGORIES.md) if needed > crystal src/cnf-conformance.cr rolling_deployment_update
- [ ] Update [Pseudo Code md](https://github.com/cncf/cnf-conformance/blob/master/PSEUDO-CODE.md) if needed > crystal src/cnf-conformance.cr rolling_deployment_update
- [ ] Update [USAGE md](https://github.com/cncf/cnf-conformance/blob/master/USAGE.md) if needed  > crystal src/cnf-conformance.cr rolling_deployment_update
- [ ] Update [installation instructions](https://github.com/cncf/cnf-conformance#installation)  if needed  > crystal src/cnf-conformance.cr rolling_deployment_update

**QA tasks**

Dev Review: 
- [x] walk through A/C
- [x] do you get the expected result?
- [x] if yes, 
   - [x] move to `Needs Peer Review` column  
   - [ ] create Pull Request and follow check list
   - [ ] Assign 1 or more people for peer review
- [ ] if no, document what additional tasks will be needed

Peer review:
- [ ] walk through A/C
- [ ] do you get the expected result?
- [ ] if yes, 
   - [ ] move to `Reviewer Approved` column
   - [ ] Approve pull request
- [ ] if no, 
   - [ ] document what did not go as expected, including error messages and screenshots (if possible)
   - [ ] Add comment to pull request
   - [ ] request changes to pull request

**Comment by lixuna** [comment]
### Acceptance Criteria:

**Comment by taylor** [comment]
Update of CNF will use Deployments as seen in https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#updating-a-deployment vs directly using a ReplicationController (https://kubernetes.io/docs/tasks/run-application/rolling-update-replication-controller/)

**Comment by lixuna** [comment]
### Level of effort in pts: 0, 1, 2, 3, 5, 8, 13, 21 = 3 pts

@taylor 3 pts
@denverwilliams 3 pts
@lixuna 3 pts

**Comment by taylor** [comment]
See https://github.com/cncf/cnf-conformance/issues/24 for test which updates the Deployment.

**Comment by williscool** [comment]
merged into master re #120

**Comment by lixuna** [comment]
@williscool please check the tasks that have been completed and update the documentation for this new test

**Comment by taylor** [comment]
```
pair@cnfdev03:~/workspace/taylor/qa/cnf-conformance$ ./cnf-conformance rolling_update
error: timed out waiting for the condition
Waiting for deployment "envoy" rollout to finish: 0 out of 2 new replicas have been updated...
Waiting for deployment "envoy" rollout to finish: 2 old replicas are pending termination...
Waiting for deployment "envoy" rollout to finish: 1 old replicas are pending termination...
FAILURE: CNF envoy Rolling Update Failed
```

**Comment by taylor** [comment]
A/C passes for envoy and coredns.

the error in the last comment is probably a timeout for the test.
