### ISSUE TITLE
[Bugfix] Creation of manifest should probably run dynamically

### ISSUE THREAD

**Issue by wavell** [cncf/cnf-conformance#73]
On the following line:
https://github.com/cncf/cnf-conformance/blob/f5f2486d833cbc3142a7788b27aecd1b3c1a8bf8/src/tasks/sample_coredns_setup.cr#L58

the setup creates a manifest file.  This works for the sample CNF but not for a manually copied CNF.   I think this line should run dynamically when the liveness/readiness test is run

Related to #56 #57

**Comment by wavell** [comment]
### Acceptance Criteria for peer review:
---
###  Common steps
- [ ]  Find or create a K8s cluster to use
       - [ ] Steps for creating will be in another ticket 
       - [ ] Talk with team for access to an existing cluster
- [ ] Set the KUBECONFIG environment variable for accessing the target K8s cluster
- [ ]  Pull down latest version of CNF conformance test code from `develop` branch
- [ ]  Run shard install
- [ ]  Run the clean task
- [ ]  Run the setup task
### There should be no manifest file in the sample_coredns directory:
```
-> ls cnfs/coredns/helm_chart/coredns 
Chart.yaml  README.md  templates  values.yaml  
```
### When using the test configuration_lifecycle command the CNF should PASS the liveness and readiness tests successfully:
- [ ]  Run  `crystal src/cnf-conformance.cr configuration_lifecycle`

- [ ] I expect to see PASSED for the increase test
- [ ] I expect to see PASSED for the decrease test

### There should be a manifest file in the sample cnf's directory:
```
-> ls cnfs/coredns/helm_chart/coredns 
Chart.yaml  manifest.yml  README.md  templates  values.yaml  
```

**Comment by taylor** [comment]
[A/C](https://github.com/cncf/cnf-conformance/issues/73#issuecomment-592680837) passes on kind cluster

```
crystal src/cnf-conformance.cr cleanup
crystal src/cnf-conformance.cr setup
```

checking for manifest
```
% ls cnfs/coredns/helm_chart/coredns/manifest.yml
ls: cannot access 'cnfs/coredns/helm_chart/coredns/manifest.yml': No such file or directory
```

Run the test
```% crystal src/cnf-conformance.cr configuration_lifecycle
FAILURE: IP addresses found
PASSED: Helm liveness probe found
PASSED: Helm readiness probe found
```

Check for the manifest:
```
% ls cnfs/coredns/helm_chart/coredns/manifest.yml
cnfs/coredns/helm_chart/coredns/manifest.yml
```

**Comment by taylor** [comment]
@wavell it seems like the manifest should not be there after the test is complete if it's automatically created for the test.   Eg.
- start test
- create manifest
- test checks manifest
- test deletes manifest

Ideally everything for default automatic testing, including using a sample CNF, would be cleaned up.  Also none of the sample CNFs should be used if the tester configures the use of a different target CNF.

I don't think anything further is needed in this ticket though.
