### ISSUE TITLE
[Process] semantic versioning of releases

### ISSUE THREAD

**Issue by lixuna** [cncf/cnf-conformance#83]
### [Process] semantic versioning of releases

Tasks:
- [x] Add a quick overview of the process you are researching
- [x] Investigate potential process for implementation and document findings => https://hackmd.io/f7Op9FgJQqW2QQXb-tVRgg?view
- [x] Select a process to use, minimal/least effort, and add selection to ticket
- [x] Add comment suggesting updates as needed for:
  - [ ] the [test categories markdown](https://github.com/cncf/cnf-conformance/blob/master/TEST-CATEGORIES.md)
  - [ ] the [pseudo code markdown](https://github.com/cncf/cnf-conformance/blob/master/PSEUDO-CODE.md)
  - [ ] slide content updates, LINK_TO_UPDATES
  - [ ] the [README](https://github.com/cncf/cnf-conformance/blob/master/README.md)
- [x] Tag 1 or more people to peer review

**Comment by lixuna** [comment]
Release tag created for v0.3.0 

https://github.com/cncf/cnf-conformance/tree/v0.3.0

v0.3.0 selected to reflect the 3 recreatable tests that pass integration tests on CNF Conformance Test Suite

**Comment by lixuna** [comment]
As of today, 1 Release displays on https://github.com/cncf/cnf-conformance/releases for v0.3.0

**Comment by taylor** [comment]
Notes on when to tag for a release => https://hackmd.io/f7Op9FgJQqW2QQXb-tVRgg?view

**Comment by taylor** [comment]
@lixuna @denverwilliams please peer review https://hackmd.io/f7Op9FgJQqW2QQXb-tVRgg?view

**Comment by williscool** [comment]
@taylor +1 pending 

I would just move the "Releases for new, non-breaking environment feature (eg. adding Kind support)"
section to the top of the doc.
that way everything is ordered from what increments the largest version to the smallest

**Comment by lixuna** [comment]
@taylor 
re: Releases for minor updates to existing tests

Can we rename this to "Releases for backwards compatible bug fixes and updates to existing tests"? Reference https://semver.org/

This would remove any confusion about using the word `minor` to mean 2 things.

**Comment by taylor** [comment]
@lixuna sounds good.  updated patch updates to match your wording.

**Comment by taylor** [comment]
I suggest creating a [RELEASE.md](https://github.com/cncf/cnf-conformance/blob/master/RELEASE.md) which describes the versioning and release process.

**Comment by lixuna** [comment]
@taylor re "Tag with new major version vMAJOR_VERSION.MINOR.PATCH, eg. v0.4.0"

Can we change the eg. from v0.4.0 to `v1.0.0`?

**Comment by taylor** [comment]
Switched to v2.0.0
